### ISSUE TITLE
Logpush Job not removed from state when deleted from UI manually

### ISSUE THREAD

**Issue by trjstewart** [cloudflare/terraform-provider-cloudflare#797] opened 2020-09-10 12:14 UTC
### Terraform Version
v0.12.29 - however this isn't version specific

### Affected Resource(s)
- logpush_job

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "cloudflare_logpush_ownership_challenge" "ownership_challenge" {
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  destination_conf = "s3://my-bucket-path?region=us-west-2"
}

data "aws_s3_bucket_object" "challenge_file" {
  bucket = "my-bucket-path"
  key    = cloudflare_logpush_ownership_challenge.ownership_challenge.ownership_challenge_filename
}

resource "cloudflare_logpush_job" "example_job" {
  enabled = true
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  name = "My-logpush-job"
  logpull_options = "fields=RayID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339"
  destination_conf = "s3://my-bucket-path?region=us-west-2"
  ownership_challenge = aws_s3_bucket_object.challenge_file.body
  dataset = "http_requests"
}
```

### Expected Behavior
The provider should replace the resource if it has been manually deleted outside of Terraform.

### Actual Behavior
The provider catches the 404 and logs an INFO message, however it does not mark the resource for removal.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Delete the `example_job` Logpush Job via the Cloudflare Dashboard or UI.
3. `terraform plan`
4. result is no change detected.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by jacobbednarz** [comment] 2020-09-10 21:14
This looks to be a duplicate of #795

**Closed** 2020-09-22 22:43 UTC
