### ISSUE TITLE
Unable to create keyless-certificate in cloudflare_origin_ca_certificate

### ISSUE THREAD

**Issue by chr15murray** [cloudflare/terraform-provider-cloudflare#2199] opened 2023-01-30 17:43 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

N/A I can see in the codebase this is not supported. It's also missing from the official Cloudflare API Docs currently

### Affected resource(s)

cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
resource "tls_private_key" "keyless-key" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_cert_request" "keyless-csr" {
  private_key_pem = tls_private_key.keyless-key.private_key_pem

  subject {
    common_name = "Keyless Server Authentication Certificate"
  }
  dns_names = ["somthingsecure.my-domain.com"]
}

resource "cloudflare_origin_ca_certificate" "keyless" {
  # NO ZONE_ID Support
  csr                = tls_cert_request.keyless-csr.cert_request_pem
  hostnames          = tls_cert_request.keyless-csr.dns_names
  request_type       = "keyless-certificate"
  requested_validity = 1095
}
```

### Link to debug output

na

### Expected output

Certificate to be issued

### Actual output

When inspecting the http resquests sent to cloudflare for the above it results in a HTTP 500 with the below body
```
{
 "success": false,
 "messages": [],
 "errors": [
  {
   "code": 1000,
   "message": "API errors encountered"
  }
 ],
 "result": {},
 "result_info": {
  "count": 0,
  "total_count": 0
 }
}
```

Reproducing with curl and adding `zone_id: <id>` in the json request data allows the cert to be issued

### Steps to reproduce

Enterprise account with Keyless enabled required.

You can reproduce in terraform or curl as docuemented here.
https://api.cloudflare.com/#origin-ca-create-certificate

When using `request_type` of `keyless-certificate` you will get a error. Adding zone_id as an additional field resolves this and issues the certificate.

### References

Support for this field was adding to gokeyless directly in this PR: https://github.com/cloudflare/gokeyless/pull/205/files

https://github.com/cloudflare/gokeyless/blob/2693c99687729fc94db2bea484a6b9aa02c2e07e/cmd/gokeyless/initialize.go#L29

**Comment by jacobbednarz** [comment] 2023-02-01 22:53
this is not a bug but an enhancement to the provider functionality.

**Comment by jacobbednarz** [comment] 2024-03-25 00:55
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Closed by jacobbednarz** 2024-03-25 00:55 UTC
Labels: kind/enhancement, workflow/pending-upstream-library, service/tls
