### ISSUE TITLE
Managing R2 objects

### ISSUE THREAD

**Issue by SahAssar** [cloudflare/terraform-provider-cloudflare#2762] opened 2023-09-14 08:30 UTC
### Current Terraform and Cloudflare provider version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.14.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0

### Description

Currently it seems like it is not possible to upload/manage R2 objects with terraform. As was noted by @yonran in #1664:

> it seems that it is not possible to create a cloudflare object using terraform-provider-aws 4.x aws_s3_object (aka aws_s3_bucket_object), since that resource tries to read the tags using GetObjectTagging (GET /key?tagging=), but R2 does not recognize ?tagging and just returns the object itself.

Since the R2 S3 API does not support the required interface to use the AWS terraform provider and the cloudflare provider does not implement any object-level apis there is no way to manage R2 objects with terraform.

### Use cases

I'm trying to upload objects for use with workers that I deploy with the cloudflare provider. It can be frontend resources, backend data, anything object-like that is coupled to a deployment of a worker.

### Potential Terraform configuration

Either with the s3 provider (if the cloudflare s3 api starts supporting GetObjectTagging):
```hcl
resource "aws_s3_object" "dist" {
  bucket = cloudflare_r2_bucket.main_bucket.name
  key    = "test.txt"
  source = "${path.module}/example/dist/test.txt"
  source_hash   = filemd5("${path.module}/example/dist/test.txt")
}
```

Or with a r2 object resource:

```hcl
resource "cloudflare_r2_object" "dist" {
  bucket = cloudflare_r2_bucket.main_bucket.name
  key    = "test.txt"
  source = "${path.module}/example/dist/test.txt"
  source_hash   = filemd5("${path.module}/example/dist/test.txt")
}
```

### References

#1664 mentions the issue

**Comment by jacobbednarz** [comment] 2023-09-20 01:16
duplicate of #1664

**Closed by jacobbednarz** 2023-09-20 01:16 UTC
Labels: kind/enhancement, needs-triage, triage/duplicate
