### ISSUE TITLE
cloudflare_list is very slow when working with bulk redirect lists

### ISSUE THREAD

**Issue by thedoc31** [cloudflare/terraform-provider-cloudflare#4566] opened 2024-11-12 21:32 UTC
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.43.0

### Affected resource(s)

cloudflare_list

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 4"
    }
  }
}

provider "cloudflare" {
  api_token = "<redacted>"
}

variable "zone_id" {
  default = "<redacted>"
}

variable "account_id" {
  default = "<redacted>"
}

variable "domain" {
  default = "<redacted>"
}
```

### Link to debug output

https://gist.github.com/thedoc31/e27b01df01a13bd68977728c353617ca

### Panic output

N/A

### Expected output

Lists with a large number of items export as quickly as other objects being managed by the terraform provider

### Actual output

The longer the list, the longer the terraform provider takes to work through it. A list with more than 1800 items takes 90+  seconds to load, and a second list with 5700 items takes 7-10 minutes during every terraform plan/apply. It appears the terraform provider may iterate over each list item one at a time when it should load the whole thing as one big blob of data.

### Steps to reproduce

1. Generate a bulk redirect list with 5000+ items
2. Run the cloudflare_list operation on that bulk redirect list
3. Wait...

### Additional factoids

I am trying to migrate a full configuration set from one Cloudflare account to another.

### References

N/A

**Comment by jacobbednarz** [comment] 2024-11-12 22:05
duplicate of #4293

**Closed by jacobbednarz** 2024-11-12 22:05 UTC
Labels: triage/duplicate

**Comment by thedoc31** [comment] 2024-11-12 22:19
@jacobbednarz I don't know if this is really a dupe, because this is happening in 4.43. #4293 references 4.44.
