### ISSUE TITLE
cloudflare_api_token_permission_groups issue

### ISSUE THREAD

**Issue by abulfat-m** [cloudflare/terraform-provider-cloudflare#1650] opened 2022-05-27 07:54 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF 1.0.10
Cloudflare TF provider 3.1.15

### Affected resource(s)

cloudflare_api_token_permission_groups
cloudflare_api_token

### Terraform configuration files

```hcl
data "cloudflare_api_token_permission_groups" "all" {}

# Token allowed to edit DNS entries and TLS certs for specific zone.
resource "cloudflare_api_token" "dns_tls_edit" {
  name = "dns_tls_edit"

  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["Logs Write"],
    ]
    resources = {
      "com.cloudflare.api.account.zone.${var.zone_id}" = "*"
    }
  }
}
```

### Debug output

na

### Expected output

We expect zone-level "Logs Write" permission (id 3e0b5820118e47f3922f7c989e673882) granted instead of account-level one (id 96163bd1b0784f62b3e44ed8c2ab1eb6).

We believe that there is a bug with cloudflare_api_token_permission_groups data source since it does not differentiate between permissions with the same name. For example, "Logs Write" exists in both account and zone levels and the only argument it accepts is name, which is not unique.

### Actual output

na

### Steps to reproduce

na

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/api_token_permission_groups
https://github.com/cloudflare/terraform-provider-cloudflare/issues/1004

**Comment by jacobbednarz** [comment] 2022-05-31 04:56
duplicate of #1004

**Closed by jacobbednarz** 2022-05-31 04:56 UTC
Labels: triage/duplicate
