### ISSUE TITLE
Add the type 'saas' for creating Access Application

### ISSUE THREAD

**Issue by JBarnes94** [cloudflare/terraform-provider-cloudflare#1631] opened 2022-05-18 08:48 UTC
### Current Terraform and Cloudflare provider version

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

### Description

Currently with the API and console you can configure SAAS access Applications - https://api.cloudflare.com/#access-applications-create-access-application 

But this functionality is no available with terraform - cloudflare_access_application does not allow type saas

### Use cases

I need to configure Access (All Zero Trust Network Services) with Terraform. 

As part of this the ability to deploy saas applications is not currently possible. 

### Potential Terraform configuration

```hcl
resource "cloudflare_access_application" "staging_app" {
  account_id              = var.cloudflare_account_id
  name                       = "Example Saas application"
  domain                    = "staging.example.com"
  type                         = "saas"
  app_launcher_visible = "true" 
  session_duration          = "8"
  auto_redirect_to_identity = false
}
```

**Comment by jacobbednarz** [comment] 2022-05-19 05:20
duplicate of #1226

**Closed by jacobbednarz** 2022-05-19 05:20 UTC
Labels: kind/enhancement, needs-triage
