### ISSUE TITLE
support reading multiple DNS records with single data source

### ISSUE THREAD

**Issue by sebhoss** [cloudflare/terraform-provider-cloudflare#2109] opened 2022-12-27 12:26 UTC
### Current Terraform and Cloudflare provider version

```
$ terraform -v
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.30.0
```

### Description

The `cloudflare_record` data source only supports selecting a single record. This breaks in case there are multiple matches, like two `TXT` records that use the same hostname. Instead of doing some custom filtering within the data source, how about adding another data source called `cloudflare_records` (plural s) that is able to output a list (or map?) of records. Terraform users can then do the filtering themselves if necessary.

### Use cases

I have two existing records of type `TXT` that both use the same hostname and can not query them with the `cloudflare_record` data source at the moment. It seems that #1906 did some special handling for `MX`/`URI` types, however `TXT` can only be distinguished by their value if they are using the same hostname.

I would like to query any type of DNS record no matter how many there are of any given kind.

### Potential Terraform configuration

```terraform
data "cloudflare_records" "example" {
  zone_id  = "some-zone-id"
  hostname = "example.com"
  type     = "TXT"
}

locals {
  spf_records = [ 
    for record in data.cloudflare_records.example : record 
    if length(regexall("spf", record.value)) > 0
  ]
  verification_records = [ 
    for record in data.cloudflare_records.example : record 
    if length(regexall("verification", record.value)) > 0
  ]
}
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/874 shows a different approach using a custom filter as part of the `cloudflare_record` data source itself.

**Comment by jacobbednarz** [comment] 2023-02-20 01:06
duplicate of #1981

**Closed by jacobbednarz** 2023-02-20 01:06 UTC
Labels: kind/enhancement, triage/accepted, service/dns
