### ISSUE TITLE
Bug creating/updating non-anomaly WAF packages

### ISSUE THREAD

**Issue by kda-jt** [cloudflare/terraform-provider-cloudflare#723] opened 2020-06-26 16:37 UTC
Hi there,

I'm currently having issues creating/updating/managing WAF Packages through Terraform, in particular, the **Cloudflare Managed Ruleset**. This is blocking me from fully managing my organisation's Cloudflare resources with Terraform.

### Terraform Version
```
Terraform v0.12.27
+ provider.cloudflare v2.7.0
```

### Affected Resource(s)
`cloudflare_waf_package`

### Terraform Configuration Files
```hcl
resource "cloudflare_waf_package" "cf_managed_ruleset" {
    zone_id = cloudflare_zone.my_zone.id
    package_id = "1e334934fd7ae32ad***************"
}
```

#### When importing
I imported the WAF package and it worked fine.

#### When running apply

```
cloudflare_waf_package.cf_managed_ruleset: Modifying... [id=1e334934fd7ae32ad***************]

Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1027,\"message\":\"Only anomaly WAF packages can have their package attributes updated\"}],\"messages\":[],\"result\":null}"

  on main.tf line 182, in resource "cloudflare_waf_package" "cf_managed_ruleset":
 182: resource "cloudflare_waf_package" "cf_managed_ruleset" {
```

It fails with `Only anomaly WAF packages can have their package attributes updated` even though I'm not updating anything, just trying to check my configuration files are all good after the import.

### Expected Behavior
No errors.

### Steps to Reproduce
You'll need a Cloudflare account with a zone and the Cloudflare managed ruleset activated on your zone.
Then try to import/apply the resource above

### Important Factoids
I used the code in the [cloudflare_waf_packages data source documentation page](https://www.terraform.io/docs/providers/cloudflare/d/waf_packages.html) to fetch the WAF Packages I had in my account. It returned :
```

data "cloudflare_waf_packages" "test" {
    id       = "WAFPackages 2020-06-26 15:10:58.438902 +0000 UTC"
    packages = [
        {
            action_mode    = ""
            description    = ""
            detection_mode = "traditional"
            id             = "1e334934fd7ae32ad***************"
            name           = "CloudFlare"
            sensitivity    = ""
        },
    ]
    zone_id  = "**REDACTED**"

    filter {
        detection_mode = "traditional"
    }
}
```
If I set `action_mode = ""` and `sensitivity = ""` in the `cloudflare_waf_package` resource, apply fails because empty strings are not valid values for those keys.

Just in case, I'm also managing the OWASP Core ruleset with Terraform and that's working great so far.

### Any help?

Any help on this issue is greatly appreciated! I'm available for any additional info.
Thanks

**Comment by jacobbednarz** [comment] 2020-07-09 23:16
I was able to reproduce using the following setup.

```hcl
# terraform.tf

variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "cloudflare_zone_id" {}

provider "cloudflare" {
  version = "~> 2.0"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

data "cloudflare_waf_packages" "test" {
  zone_id = var.cloudflare_zone_id

  filter {
    detection_mode = "traditional"
  }
}

resource "cloudflare_waf_package" "cf_managed_ruleset" {
  zone_id     = var.cloudflare_zone_id
  package_id  = "1e334934fd7ae32ad705667f8c1057aa"
}

output "waf_packages" {
  value = data.cloudflare_waf_packages.test.packages
}
```

- Import the `1e334934fd7ae32ad705667f8c1057aa` resource (named "CloudFlare")

```javascript
// API payload

{
  "result": [
    {
      "id": "1e334934fd7ae32ad705667f8c1057aa",
      "name": "CloudFlare",
      "description": null,
      "zone_id": "0da42c8d2132a9ddaf714f9e7c920711",
      "detection_mode": "traditional"
    },
    // .. snip
}
```

```
$ terraform import -var "cloudflare_email=$CF_EMAIL" -var "cloudflare_api_key=$CF_API_KEY" -var "cloudflare_zone_id=$CF_ZONE_ID" \
  cloudflare_waf_package.cf_managed_ruleset $CF_ZONE_ID/1e334934fd7ae32ad705667f8c1057aa
```

- Check the state (notice the lack of `sensitivity` and `action_mode`. Important for later understanding)

```
$ terraform state show cloudflare_waf_package.cf_managed_ruleset
# cloudflare_waf_package.cf_managed_ruleset:
resource "cloudflare_waf_package" "cf_managed_ruleset" {
    id         = "1e334934fd7ae32ad705667f8c1057aa"
    package_id = "1e334934fd7ae32ad705667f8c1057aa"
    zone_id    = "0da42c8d2132a9ddaf714f9e7c920711"
}
```

- Attempt an `apply`

```
$ terraform apply -var "cloudflare_email=$CF_EMAIL" -var "cloudflare_api_key=$CF_API_KEY" -var "cloudflare_zone_id=$CF_ZONE_ID" \
cloudflare_waf_package.cf_managed_ruleset: Refreshing state... [id=1e334934fd7ae32ad705667f8c1057aa]
data.cloudflare_waf_packages.test: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_waf_package.cf_managed_ruleset will be updated in-place
  ~ resource "cloudflare_waf_package" "cf_managed_ruleset" {
      + action_mode = "challenge"
        id          = "1e334934fd7ae32ad705667f8c1057aa"
        package_id  = "1e334934fd7ae32ad705667f8c1057aa"
      + sensitivity = "high"
        zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_waf_package.cf_managed_ruleset: Modifying... [id=1e334934fd7ae32ad705667f8c1057aa]

Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1027,\"message\":\"Only anomaly WAF packages can have their package attributes updated\"}],\"messages\":[],\"result\":null}"

  on terraform.tf line 19, in resource "cloudflare_waf_package" "cf_managed_ruleset":
  19: resource "cloudflare_waf_package" "cf_managed_ruleset" {
```

As the above output shows, there are two missing properties on the resource which Terraform will try and correct due to not having a value for managing the state. 

Looking at the HTTP request made on `Import` neither of those are present which explains why the values are missing.

```javascript
// zones/$CF_ZONE_ID/firewall/waf/packages/1e334934fd7ae32ad705667f8c1057aa

{
  "result": {
    "id": "1e334934fd7ae32ad705667f8c1057aa",
    "name": "CloudFlare",
    "description": null,
    "zone_id": "0da42c8d2132a9ddaf714f9e7c920711",
    "detection_mode": "traditional"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

Due to the API response missing, Terraform will use the schema defaults ([here](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_waf_package.go#L42) and [here](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_waf_package.go#L49)) which trigger a resource change and subsequently the API exception.

To fix this, I think we need to remove the `Default`s on these schema attributes as they are optional and not enforcing values where they aren't required.

**Comment by kda-jt** [comment] 2020-07-10 09:25
Hi @jacobbednarz 

> Due to the API response missing, Terraform will use the schema defaults ([here](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_waf_package.go#L42) and [here](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_waf_package.go#L49)) which trigger a resource change and subsequently the API exception.

You're pretty much spot on.
I'd be glad to help any way I can (I have zero Go experience though unfortunately).

**Comment by jacobbednarz** [comment] 2020-07-10 13:18
All good. I have a branch locally fixing this one. I’m just in the process of ensuring all three scenarios are catered for as a part of the change and I’ll get it available for testing.

**Comment by jacobbednarz** [comment] 2020-07-13 22:18
There is a fix for this one in #733. Would you mind pulling this branch locally, build the provider per the README instructions and confirm it addresses your use case?

**Comment by kda-jt** [comment] 2020-07-14 08:15
Hi @jacobbednarz 
Yup, I'll try to get back to you tomorrow about this. Thanks

**Comment by jacobbednarz** [comment] 2020-07-14 21:44
Chatting with @XaF about this, you're attempting to manage a read-only resource in Cloudflare which doesn't quite fit the mould of a resource. Could you instead use the WAF package datasource instead for referencing?

**Comment by jacobbednarz** [comment] 2020-07-27 23:23
Closed due to necromancy.

**Closed by jacobbednarz** 2020-07-27 23:23 UTC

**Comment by kda-jt** [comment] 2020-07-28 11:04
Hi @jacobbednarz 
I'm terribly sorry. I've taken too long to get back to you, and that's inexcusable, but for what it's worth, I'd like to apologize.

I don't believe the documentation explicitly mentions that the `"cloudflare_waf_package" "cf_managed_ruleset"` is read-only. Intuitively, I thought we could manipulate that resource to activate/"turn on" the rules in that package.

Anyway, I currently have the following configuration to individually manage the groups within the CF Managed Ruleset package:

```
data "cloudflare_waf_packages" "fetch-cf-managed-ruleset" {
  zone_id = cloudflare_zone.zone.id
  filter {
    name   = "CloudFlare"
  }
}

locals {
  # Renaming the variable with locals for better legibility
  cf_managed_ruleset_id = data.cloudflare_waf_packages.fetch-cf-managed-ruleset.packages.0.id
}

resource "cloudflare_waf_group" "cf_flash" {
  # Part of the CF managed ruleset
  package_id = local.cf_managed_ruleset_id
  zone_id    = cloudflare_zone.zone.id
  group_id   = "cf6b50e84134de6c15b32edd3c03e201"
  mode       = "on"
}

resource "cloudflare_waf_group" "cf_drupal" {
  # Part of the CF managed ruleset
  package_id = local.cf_managed_ruleset_id
  zone_id    = cloudflare_zone.zone.id
  group_id   = "8df6c9aaddcbdf0eceb047bc50873697"
  mode       = "off"
}
# ...
# All other WAF rule groups are included as resources just like the above flash & drupal groups

```

I'm not sure if this is the "right" (both in the Terraform and Cloudflare senses) way to handle this situation. But it works fine, even if it adds a lot of clutter to the config files.

**Comment by jacobbednarz** [comment] 2020-07-28 21:07
> I'm terribly sorry. I've taken too long to get back to you, and that's inexcusable, but for what it's worth, I'd like to apologize.

All good! I assumed you had a solution and this was no longer an issue for you so I closed it in the interest of working through the issue tracker. Here, a closed issue doesn't mean the discussion is over, just there isn't any more work required from the maintainers. People have a pretty good way of piping up if things are still causing issues whereas silence usually follows a solution being found or them being unblocked 🙂 

> I don't believe the documentation explicitly mentions that the `"cloudflare_waf_package" "cf_managed_ruleset"` is read-only.

It most likely doesn't as we don't explicitly call out what is and isn't read-only or managed as the majority of the time, the subscription level denotes that. This _is_ a case where that isn't applicable and it's read-only across all plans however the sentiment still stands. The assumption with Terraform is that you're defining resources which you intend to manage. In my workflow (and others I've worked with on these things), you worked through the dashboard or API documentation for a particular service and work out if we need a reference (read-only entity) or a resource (changeable entity). If you encounter a read-only entity, you use a data source, otherwise a resource. You then proceed down the path of whether you import or replace it using Terraform.

> I'm not sure if this is the "right" (both in the Terraform and Cloudflare senses) way to handle this situation. But it works fine, even if it adds a lot of clutter to the config files.

Your approach is how I would have recommended tackling this one because you still want to manage the WAF groups but you don't need to manage the WAF ruleset itself. 

I don't agree that you end up with more any more clutter than another approach here as regardless, you're going to need a reference (from your WAF ruleset) to lean on for your WAF group resource management. It is subjective though so take my opinion with a grain of salt. 

Anyway, I'm glad you've got a solution!
