### ISSUE TITLE
constant drift on cloudflare_managed_headers

### ISSUE THREAD

**Issue by luisrx7** [cloudflare/terraform-provider-cloudflare#3428] opened 2024-07-02 15:59 UTC
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.0
on linux_amd64

### Affected resource(s)

cloudflare_managed_headers 

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.32.0"
    }
  }
}

provider "cloudflare" {
  api_token = "XXXXXXXXXXXXXXXXXXXXXX"
}

resource "cloudflare_managed_headers" "this" {
  zone_id = "XXXXXXXXXXXXXXXXXXXXXXX"

  managed_request_headers {
    id      = "add_true_client_ip_headers"
    enabled = false
  }

  managed_response_headers {
    id      = "remove_x-powered-by_header"
    enabled = false
  }

}
```

### Link to debug output

https://gist.github.com/luisrx7/d9499dd717624d8e24a5a165f674db1f

### Expected output

I was expecting no changes since the resource was already in disabled state

### Actual output
```hcl
Terraform will perform the following actions:

  cloudflare_managed_headers.this will be updated in-place
  ~ resource "cloudflare_managed_headers" "this" {
        id      = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        # (1 unchanged attribute hidden)

      + managed_request_headers {
          + enabled = false
          + id      = "add_true_client_ip_headers"
        }

      + managed_response_headers {
          + enabled = false
          + id      = "remove_x-powered-by_header"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Steps to reproduce

1. create a cloudflare_managed_headers with a managed_request_headers  or managed_response_headers  with a setting enabled
```hcl
resource "cloudflare_managed_headers" "this" {
  zone_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

  managed_request_headers {
    id      = "add_true_client_ip_headers"
    enabled = true
  }

  managed_response_headers {
    id      = "remove_x-powered-by_header"
    enabled = true
  }

}
```
2. terraform apply
3. change the setting to disabled
```hcl
resource "cloudflare_managed_headers" "this" {
  zone_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

  managed_request_headers {
    id      = "add_true_client_ip_headers"
    enabled = false
  }

  managed_response_headers {
    id      = "remove_x-powered-by_header"
    enabled = false
  }

}
```
5. terraform apply
6. terraform apply again
```hcl
Terraform will perform the following actions:

  # cloudflare_managed_headers.this will be updated in-place
  ~ resource "cloudflare_managed_headers" "this" {
        id      = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        # (1 unchanged attribute hidden)

      + managed_request_headers {
          + enabled = false
          + id      = "add_true_client_ip_headers"
        }

      + managed_response_headers {
          + enabled = false
          + id      = "remove_x-powered-by_header"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Additional factoids

Although there may be a constant drift present, if you set the settings to "disabled", it will modify the resources on Cloudflare.

### References

#2806  appears to be something similar

**Comment by jacobbednarz** [comment] 2024-07-02 23:21
you're correct here, this is a duplicate of #2806 as it is still using the SDKv2 internally.

**Closed by jacobbednarz** 2024-07-02 23:21 UTC
Labels: kind/bug, needs-triage, triage/debug-log-attached
