### ISSUE TITLE
Missmatch between permission names on cloudflare documentation and the provider object

### ISSUE THREAD

**Issue by MoreCodeLess** [cloudflare/terraform-provider-cloudflare#3041] opened 2024-01-04 23:02 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform -> 1.4.5
Provider -> 4.21.0

### Affected resource(s)

cloudflare_api_token

### Terraform configuration files

```hcl
resource "cloudflare_api_token" "api_token_create" {
  name = "api_token_create"

  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["Cache Rules Write"],
    ]
    resources = {
      "com.cloudflare.api.account.zone.*" = "*"
    }
  }
}
```

### Link to debug output

-

### Expected output

using this configuration it should succed and apply the permission to the API token, it doesnt because the object on the provider doesnt have Cache Rules Write/Read as the documentation(https://developers.cloudflare.com/fundamentals/api/reference/permissions/#zone-permissions), it has Cache Settings Write/Read (here an image after inspecting on the object in the tf_state 
![Screenshot from 2024-01-04 14-34-42](https://github.com/cloudflare/terraform-provider-cloudflare/assets/77852607/6143c62e-c86d-464e-8ec7-b98358dea6db)
)

### Actual output

![Screenshot from 2023-11-22 13-25-09](https://github.com/cloudflare/terraform-provider-cloudflare/assets/77852607/1801b7d0-25c6-407e-9629-ef35a56646bf)

### Steps to reproduce

Try to add a permission call "Cache Rules Write" as the documentation says, instead of "Cache Settings Write" as it is on the object

### Additional factoids

It would be good to match the names of the permissions in the documentation and in the provider objects.

**Comment by jacobbednarz** [comment] 2024-01-05 00:09
thanks for the issue! the mismatch you're talking about here is the UI vs the API. the API still requires the names used here (terraform is just another HTTP client) whereas the UI wraps them up nicely for you. this is working as intended so i'm going to close this out however, i'll let our IAM folks know about the potential enhancement here.

**Closed by jacobbednarz** 2024-01-05 00:09 UTC
Labels: kind/bug, triage/needs-information
