### ISSUE TITLE
Page rules custom cache key panics

### ISSUE THREAD

**Issue by mphoratiu** [cloudflare/terraform-provider-cloudflare#810] opened 2020-09-30 10:59 UTC
### Terraform Version
Terraform v0.12.28
+ provider.cloudflare v2.11.0

### Affected Resource(s)
- cloudflare_page_rule

### Terraform Configuration Files
Terraform plan
```hcl
Terraform will perform the following actions:

  # cloudflare_page_rule.rule14 will be updated in-place
~ resource "cloudflare_page_rule" "rule14" {
        id       = "a9ff648ed554af9b36c3480f2486313b"
        priority = 14
        status   = "active"
        target   = "*/target/url*"
        zone_id  = "123456-cloudflare-zone"

      ~ actions {
            always_use_https    = false
            disable_apps        = false
            disable_performance = false
            disable_railgun     = false
            disable_security    = false
            edge_cache_ttl      = 0
            waf                 = "off"

          + cache_key_fields {
              + cookie {
                  + check_presence = (known after apply)
                  + include        = (known after apply)
                }

              + header {
                  + check_presence = (known after apply)
                  + exclude        = (known after apply)
                  + include        = [
                      + "included-header",
                    ]
                }

              + host {}

              + query_string {
                  + exclude = (known after apply)
                  + ignore  = false
                  + include = (known after apply)
                }

              + user {}
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Configuration
```hcl
variable "cloudflare_token" {
}

variable cloudflare_zone_id {
  description = "The cloudflare zone ID we're managing"
  default     = "123456-cloudflare-zone"
}

terraform {
  backend "s3" {
    key    = "key/path/page_rules.tfstate"
    region = "us-east-1"
    bucket = "terraform-states-bucket"
  }
}

provider "cloudflare" {
  version   = "~> 2.0"
  api_token = var.cloudflare_token
}

# page rule with included header
resource "cloudflare_page_rule" "rule14" {
  zone_id  = var.cloudflare_zone_id
  target   = "*/target/url*"
  priority = "14"
  actions {
    cache_key_fields {
      cookie {}
      header {
        include = ["included-header"]
      }
      host {}
      query_string {}
      user {}
    }
  }
  waf = "off"
}
```

### Terraform state show the resource
```hcl
# cloudflare_page_rule.rule14:
resource "cloudflare_page_rule" "rule14" {
    id       = "a9ff648ed554af9b36c3480f2486313b"
    priority = 14
    status   = "active"
    target   = "*/target/url*"
    zone_id  = "123456-cloudflare-zone"

    actions {
        always_use_https    = false
        disable_apps        = false
        disable_performance = false
        disable_railgun     = false
        disable_security    = false
        edge_cache_ttl      = 0
        waf                 = "off"
    }
}
```

### Panic Output
https://gist.github.com/mphoratiu/040eabed4e0c0f8e13ed549c6aaf8506

### Expected Behavior
The page rule resource should add custom cache key with header.

### Actual Behavior
It panics.

### Steps to Reproduce
1. You have an existing page rule (the resource's state added above)
2. You add custom cache key configuration (in my case a header added in include)
3. run `terraform apply` and it panics
4. If I removed the resource and left the process re-create it, it worked.

**Comment by jacobbednarz** [comment] 2020-09-30 21:48
Have you tried the including the default values mentioned at #740?

**Comment by mphoratiu** [comment] 2020-10-02 14:32
On a different PR I've created a new dummy page rule having exactly the same definition and it created it without any errors.

I have other custom cache keys used in different page rules and they don't have defaults where I didn't want any option. 

The defaults are specified in the [page rules documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule).

**Comment by grogancolin** [comment] 2020-10-07 10:57
I think this is an _old_ page rule that was imported - new version of the provider can't handle it.

**Comment by avandendorpe** [comment] 2020-10-08 21:34
Hi, seeing this as well trying to add custom cache key actions to an existing page rule without a previous `cache_key_fields` spec:

```
2020-10-08T14:17:47.953-0700 [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: 2020/10/08 14:17:47 [DEBUG] cache_key_fields action to be applied: []interface {}{map[string]interface {}{"cookie":[]interface {}{map[string]interface {}{"check_presence":[]interface {}{}, "include":[]interface {}{}}}, "header":[]interface {}{map[string]interface {}{"check_presenc
2020-10-08T14:17:47.956-0700 [DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: panic: interface conversion: interface {} is nil, not map[string]interface {}
```

```
resource "cloudflare_page_rule" "cache-interface-css" {
  zone_id = var.cloudflare_zone_id
  target = "subdomain.${var.cloudflare_zone_name}/*.css"
  priority = 14

  actions {
    always_use_https = true
    true_client_ip_header = "on"
    cache_key_fields {
      header {}
      query_string {
        include = ["cache"]
      }
      user {}
      cookie {}
      host {}
    }
    cache_level = "cache_everything"
    edge_cache_ttl = 3600
  }
}
```

Plan
```
  # cloudflare_page_rule.cache-interface-css will be updated in-place
  ~ resource "cloudflare_page_rule" "cache-interface-css" {
        id       = "3f528491f1c3750e22f873174ea6e188"
      ~ priority = 1 -> 2
        status   = "active"
        target   = "subdomain.cloudflare.com/*.css"
        zone_id  = "3f528491f05d5d88ff5b419e4ea6e188"

      ~ actions {
            always_use_https      = true
            disable_apps          = false
            disable_performance   = false
            disable_railgun       = false
            disable_security      = false
            edge_cache_ttl        = 604800
            host_header_override  = "subdomain.s3.amazonaws.com"
            resolve_override      = "subdomain.cloudflare.com"
            true_client_ip_header = "on"

          + cache_key_fields {
              + cookie {
                  + check_presence = (known after apply)
                  + include        = (known after apply)
                }

              + header {
                  + check_presence = (known after apply)
                  + exclude        = (known after apply)
                  + include        = (known after apply)
                }

              + host {}

              + query_string {
                  + exclude = (known after apply)
                  + ignore  = true
                  + include = (known after apply)
                }

              + user {}
            }
        }
    }
```

**Comment by jacobbednarz** [comment] 2020-10-22 20:52
I managed to reproduce this as well as get it working. The resource is choking on the empty `host` value which wants  `resolved = (bool)` explicitly included however because the value is marked as `Computed` in the schema, it's not set before the API request is built for sending.

The fix for this one is easy enough on the surface

```diff
--- cloudflare/resource_cloudflare_page_rule.go
+++ cloudflare/resource_cloudflare_page_rule.go
@@ -372,7 +372,7 @@ func resourceCloudflarePageRule() *schema.Resource {
                                                                                                "resolved": {
                                                                                                        Type:     schema.TypeBool,
                                                                                                        Optional: true,
-                                                                                                       Computed: true,
+                                                                                                       Default:  false,
                                                                                                },
                                                                                        },
                                                                                },
```

However, I will put up a PR and run it through the test cases to make sure this won't introduce a regression.

**Closed** 2020-10-22 23:04 UTC
Labels: kind/bug, kind/crash, triage/accepted
