### ISSUE TITLE
account_id deprecated in provider, but not defined in resources, so warnings or errors are displayed

### ISSUE THREAD

**Issue by NJITman** [cloudflare/terraform-provider-cloudflare#1873] opened 2022-08-31 15:29 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.8
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.22.0
+ provider registry.terraform.io/dopplerhq/doppler v1.0.0
+ provider registry.terraform.io/hashicorp/aws v4.28.0
+ provider registry.terraform.io/hashicorp/random v3.3.2
```

### Affected resource(s)

- cloudflare_load_balancer_monitor
- cloudflare_load_balancer_pool
- cloudflare_load_balancer

### Terraform configuration files

```hcl
# Cloudflare Provider
provider "cloudflare" {
  email      = "email"
  api_key    = "api_key"
  account_id = "account_id"
}

resource "cloudflare_load_balancer_monitor" "tcp_monitor" {
  account_id = "account_id"
}
resource "cloudflare_load_balancer_pool" "load_balancer_pool" {
  account_id = "account_id"
}
resource "cloudflare_load_balancer" "load_balancer" {
  account_id = "account_id"
}
```

### Debug output

See actual output. No debug needed.

### Expected output

CloudFlare resource should properly deploy with account_id provided at the resource level and account_id removed from the provider.

### Actual output

Leaving account_id defined in provider, displays warning.  Removing account_id from provider and adding to resources, generates an error.

Warning
```
Warning: Argument is deprecated

  with provider["registry.terraform.io/cloudflare/cloudflare"],
  on main.tf line 143, in provider "cloudflare":
 143:   account_id = "account_id"

Use resource specific `account_id` attributes instead.
```

Errors
```
Error: Unsupported argument

  on modules\cloudflare\load-balancer\main.tf line 22, in resource "cloudflare_load_balancer_pool" "load_balancer_pool":
  22:   account_id = "account_id"

An argument named "account_id" is not expected here.

Error: Unsupported argument

  on modules\cloudflare\load-balancer\main.tf line 11, in resource "cloudflare_load_balancer_monitor" "tcp_monitor":
  11:   account_id  = "account_id"

An argument named "account_id" is not expected here.

Error: Unsupported argument

  on modules\cloudflare\load-balancer\main.tf line 37, in resource "cloudflare_load_balancer" "load_balancer":
  37:   account_id       = "account_id"

An argument named "account_id" is not expected here.
```

### Steps to reproduce

1. Add account_id to `cloudflare` provider (displays deprecated warning)
2. Add account_id to `cloudflare_load_balancer_monitor`, `cloudflare_load_balancer_pool` or `cloudflare_load_balancer` (displays error)

**Comment by jacobbednarz** [comment] 2022-08-31 20:47
this is a duplicate of #1836. you can track the progress via #1646

**Closed by jacobbednarz** 2022-08-31 20:47 UTC
Labels: triage/duplicate
