### ISSUE TITLE
Add data source for log fields to use with `cloudflare_logpush_job`

### ISSUE THREAD

**Issue by eddiehoffman** [cloudflare/terraform-provider-cloudflare#2014] opened 2022-11-08 15:16 UTC
### Current Terraform and Cloudflare provider version

terraform -v
Terraform v1.3.3

### Description

We would like to push all log fields. Instead of having a list of log fields that is manually updated and passed to `logpull_options` parameter on the `cloudflare_logpush_job`, it would be good if there was a data source which could be used to reference when setting up a log push job. Or just a way to just enable all fields.

Looking at the docs I can see that the following endpoint is available for fetching all fields available for a dataset and zone id:
`https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/logpush/datasets/<DATASET>/fields`

Ideally the data source would be able to query the above fetching a set of all the fields.

Currently we are manually maintaining a list and doing the following:

```hcl
locals {
  http_requests_fields = [
    "BotDetectionIDs",
    "BotScore",
    "BotScoreSrc",
    "BotTags",
    "CacheCacheStatus",
    "CacheReserveUsed",
    "CacheResponseBytes",
    "CacheTieredFill",
    ...
  ]
}

resource "cloudflare_logpush_job" "http_requests" {
  logpull_options     = "fields=${join(",", local.http_requests_fields)}&timestamps=rfc3339"
  dataset             = "http_requests"
}
```

### Use cases

Populating logpull_options with all fields.

### Potential Terraform configuration

```hcl
data "cloudflare_log_fields" "http_requests" {
  zone_id  = var.zone_id
  dataset = "http_requests"
}
```

**Comment by jacobbednarz** [comment] 2022-11-08 18:59
duplicate of #1005.

**Closed by jacobbednarz** 2022-11-08 18:59 UTC
Labels: kind/enhancement, needs-triage
