### ISSUE TITLE
Cannot Downgrade Enterprise Plan to Free Plan

### ISSUE THREAD

**Issue by spowell-kcc** [cloudflare/terraform-provider-cloudflare#1475] opened 2022-02-18 21:49 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.6
on windows_amd64
provider registry.terraform.io/cloudflare/cloudflare v3.9.1

Tested with Provider 3.9.1, Terraform 1.0.7, 1.0.11, 1.1.6 and Provider 2.27.0, Terraform 1.0.7.

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
resource "cloudflare_zone" "zone" {
    zone  = "test.domain.com"
    plan  = "enterprise"
}
```

### Debug output

[terraform.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/8100600/terraform.txt)

### Expected output

The zone plan should downgrade to free.

### Actual output

The zone plan fails to downgrade. This is similar to issue #667, except this is a downgrade, not an upgrade.

Terraform waits/loops for 20 minutes and then produces the following error:

`Error: plan ID change has not yet propagated`

The console output looks like this ...
```
module.cf_zone.module.cf_zone.cloudflare_zone.zone: Modifying... [id=redacted]
module.cf_zone.module.cf_zone.cloudflare_zone.zone: Still modifying... [id=redacted, 10s elapsed]
module.cf_zone.module.cf_zone.cloudflare_zone.zone: Still modifying... [id=redacted, 20s elapsed]
module.cf_zone.module.cf_zone.cloudflare_zone.zone: Still modifying... [id=redacted, 30s elapsed]
...
module.cf_zone.module.cf_zone.cloudflare_zone.zone: Still modifying... [id=redacted, 19m51s elapsed]
│ Error: plan ID change has not yet propagated
```

### Steps to reproduce

Attempt to downgrade any enterprise plan to a free plan via terraform.

### Additional factoids

This was submitted to Cloudflare support, but according to them the provider is not passing the correct API call to downgrade the zone, so I'm submitting it here.

Thanks!

**Comment by spher0boom** [comment] 2022-02-18 22:07
The entirety of the debug log was provided as the terraform.txt file attachment as the content was too long for the form.

**Comment by spher0boom** [comment] 2022-02-19 07:11
Ok, thank you. I will get our enterprise rep to open a support ticket with the API team then. If we can't downgrade we can't delete the zones.

**Comment by jacobbednarz** [comment] 2022-02-19 10:49
I’ve raised this with the billing team (the ones who own subscriptions) but a support ticket is also helpful.

**Comment by jacobbednarz** [comment] 2022-02-20 21:41
Do you have a support ticket number I can link this with? In the meantime, your account team can delete these zones.

**Comment by spher0boom** [comment] 2022-02-21 14:22
Here is the support ticket information:

Cannot downgrade plan in Terraform. | #2308161

We have API access to be able to downgrade and delete, so for now I'll create an external provider to make the API calls directly and do a pre-run on the assets before destruction.

Thanks!

**Comment by spher0boom** [comment] 2022-02-21 22:43
I tried doing the downgrade in an external provider, but forgot how many features are enabled via the enterprise plan. Downgrading the zone in the external provider causes a ton of errors for all the stuff that's removed (WAF rules, etc...) and the terraform fails.

To actually delete the zone I need to:
1. Run an apply and remove the fallback_origin setting.
2. Run a destroy, which deletes all the assets except the actual zone.
3. Run an API command outside of Terraform to delete the zone.
4. Remove all the state files so I don't get errors if the zone gets re-created.

It's certainly doable, but messy, and our desire was not to remove the state files (for auditing), so we'll have to find a way to manage those.

Hopefully the API team will be helpful and get this fixed.

Thanks!

**Comment by vlucaswang** [comment] 2022-02-21 23:53
> I tried doing the downgrade in an external provider, but forgot how many features are enabled via the enterprise plan. Downgrading the zone in the external provider causes a ton of errors for all the stuff that's removed (WAF rules, etc...) and the terraform fails.
> 
> To actually delete the zone I need to:
> 
> 1. Run an apply and remove the fallback_origin setting.
> 2. Run a destroy, which deletes all the assets except the actual zone.
> 3. Run an API command outside of Terraform to delete the zone.
> 4. Remove all the state files so I don't get errors if the zone gets re-created.
> 
> It's certainly doable, but messy, and our desire was not to remove the state files (for auditing), so we'll have to find a way to manage those.
> 
> Hopefully the API team will be helpful and get this fixed.
> 
> Thanks!

My experience for deleting/recreating zone without a failing drift pipeline:
- Add `count = 0` to all resouces.
- Run `terraform apply` to destroy all resources except the zone.
- Downgrade the zone to free plan via Patch API.
- Run `terraform apply` to destroy the zone.

This does not require you to remove the state files or codes.

**Comment by spher0boom** [comment] 2022-02-22 08:02
Support closed my previous ticket so I have opened a new one (2381168) and linked to this discussion.

**Comment by kanishkat** [comment] 2022-03-25 01:40
@spher0boom  I'm facing the same issue. I can't perform your workaround since I'm running the code via Jenkins. Did you receive any update for the ticket you opened?

**Comment by spher0boom** [comment] 2022-03-27 18:12
The ticket was confirmed as an issue on the back end and moved to our customer success manager with no ETA unfortunately.

**Comment by maxpain** [comment] 2022-04-03 12:46
The same problem.

**Comment by akinnane** [comment] 2022-09-29 15:29
I also have the same problem.

**Comment by jacobbednarz** [comment] 2022-11-16 00:14
closing this one out as it is a service issue that the team are looking into and nothing we can action from the terraform side.

**Closed by jacobbednarz** 2022-11-16 00:14 UTC
Labels: kind/bug, triage/accepted

**Comment by jacobbednarz** [comment] 2022-11-16 00:16
note: the dashboard now exposes this in the UI too if you need a simpler way to trigger and then manually update your state file to reflect that.
