### ISSUE TITLE
`cloudflare_record` should check the comment length

### ISSUE THREAD

**Issue by cimnine** [cloudflare/terraform-provider-cloudflare#2282] opened 2023-03-10 12:00 UTC
### Current Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0

### Description

A comment on a DNS record may not be longer than 50 characters. The provider should check this constraint before making a request.

When creating a new DNS records, the error returned by the API is just `Error: failed to create DNS record: DNS Validation Error (1004)`. Which leaves no clue that the comment was too long.

### Use cases

Whenever a comment is added to a record. Such comments may contain dynamic data, for which the length may not be known beforehand.

### Potential Terraform configuration

```hcl
resource "cloudflare_record" "main" {
  zone_id = var.cloudflare_zone_id
  name = var.cloudflare_record_name
  type = "CNAME"
  value = "myresources.ontheweb.com"
  proxied = true

  comment = "Points to the ${var.name} resources of the web app"
}
```

**Comment by jacobbednarz** [comment] 2023-03-10 18:46
duplicate of #2194

**Closed** 2023-03-10 18:46 UTC
Labels: triage/duplicate
