### ISSUE TITLE
Support for Cloudflare Application for private network with terraform

### ISSUE THREAD

**Issue by TirushV** [cloudflare/terraform-provider-cloudflare#2113] opened 2022-12-29 03:48 UTC
### Current Terraform and Cloudflare provider version

1.3.3 terraform version

### Description

Support for Cloudflare Application for private network with terraform

### Use cases

Testing VPN and SSM Alternative

### Potential Terraform configuration

 Not supported yet

**Comment by jacobbednarz** [comment] 2022-12-29 03:57
duplicate of #1974

**Closed by jacobbednarz** 2022-12-29 03:57 UTC
Labels: kind/enhancement, needs-triage
