### ISSUE TITLE
cloudflare_healthcheck health event notifications control

### ISSUE THREAD

**Issue by mihaiturcu** [cloudflare/terraform-provider-cloudflare#1438] opened 2022-02-09 13:55 UTC
### Current Terraform and Cloudflare provider version

Terraform v1.1.5

### Description

Hi,

Currently, there seems to be no way to configure Health Event Notifications to Fail only.
![image](https://user-images.githubusercontent.com/16454712/153215100-403daa9a-9916-44b1-9c82-89551445592b.png)

Could we add this?

Thanks

### Use cases

This is relevant for email integrations with services like PagerDuty / ServiceNow. 
If we can't send notifications only when something fails, we're creating incidents even when the service recovers.

### Potential Terraform configuration

```hcl
resource "cloudflare_healthcheck" "something" {
  address                = "something.example.com"
  check_regions          = ["ALL_REGIONS"]
  consecutive_fails      = 1
  consecutive_successes  = 1
  description            = "some desc"
  interval               = 30
  name                   = "some_name"
  retries                = 3
  suspended              = false
  timeout                = 5
  type                   = "HTTPS"
  zone_id                = var.zone_id
  notification_suspended = false
  notification_email_addresses = [
    "mail@example.com"
  ]
  port   = "443"
  method = "GET"
  path   = "/healthcheck"
  expected_codes = [
    "2xx"
  ]
  allow_insecure = true
  event_notification_only = "fail"
}
```

**Comment by jacobbednarz** [comment] 2022-05-06 05:22
the `notification` section of `cloudflare_healthcheck` are now deprecated so we won't be adding this; instead you should use `cloudflare_notification_policy` that should allow this functionality to work as intended.

**Closed by jacobbednarz** 2022-05-06 05:22 UTC
Labels: triage/unresolved
