### ISSUE TITLE
Tiered cache topology resource request

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1626] opened 2022-05-13 19:30 UTC
### Current Terraform and Cloudflare provider version

NA

### Description

Please create a resource for managing Tiered Cache Topology in order to set either the Smart Tiered Cache Topology or the Generic Global Tiered Topology

### Use cases

We need to set the default Tiered Cache Topology via terraform.

### Potential Terraform configuration

```hcl
resource "tiered_cache_topology" "this" {
...
}
```

**Comment by jacobbednarz** [comment] 2022-05-16 02:18
this looks to be a duplicate of #1626

**Closed by jacobbednarz** 2022-05-16 02:18 UTC
Labels: kind/enhancement, triage/accepted
