### ISSUE TITLE
cloudflare_certificate_pack cannot unmarshal string into Go struct field CertificatePack.result.primary_certificate of type int

### ISSUE THREAD

**Issue by silencesux** [cloudflare/terraform-provider-cloudflare#1145] opened 2021-08-02 15:54 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.3
+ provider registry.terraform.io/cloudflare/cloudflare v2.24.0
...

### Affected resource(s)

cloudflare_certificate_pack

### Terraform configuration files

```hcl
resource "cloudflare_certificate_pack" "example" {
  zone_id               = local.dns_zones_cf.id
  type                  = "advanced"
  hosts                 = ["example.com", "*.example.com", "*.${local.env}.example.com"]
  validation_method     = "txt"
  validity_days         = 30
  certificate_authority = "digicert"
  cloudflare_branding   = false
}
```

### Debug output

no debug

### Panic output

Error: failed to fetch certificate pack: error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field CertificatePack.result.primary_certificate of type int

### Expected output

the 'terraform plan' will be executed without errors after resource creation

### Actual output

Terraform Provider is expecting Int in field primary_certificate but receives String

### Steps to reproduce

1. create a resource cloudflare_certificate_pack
2. try to execute terraform plan

**Comment by jacobbednarz** [comment] 2021-08-02 19:33
Per the issue template, please provide the untruncated TF_LOG=DEBUG output with any sensitive information redacted.

**Comment by jacobbednarz** [comment] 2021-08-02 19:38
@gialloguitar the opposite; that commit fixes your issue leaving this issue as a potential duplicate. That fixes hasn't landed here yet so if you're using 2.24.0, it can't have broken your certificates 🙂

**Comment by jpenaq2** [comment] 2021-08-03 13:42
Just a heads up that this also started breaking our deployments late last week... had to remove the certificate pack from state in order to move forward.  The project was on 2.20.0, and I iterated through a versions to get it to succeed without luck.

**Comment by dli-spoton** [comment] 2021-08-03 17:54
Yeah, this broke today. Was able to plan and apply yesterday with no issues. The certs have been terraform managed for months now, and have not seen any changes. Provider version hasn't changed either.
Looking at the error, I'm guessing the API endpoint was change to return a str for CertificatePack.result.primary_certificate. The provider is expecting int, so it's failing when it's checking the current state during a plan/apply.

**Comment by garrettgalow** [comment] 2021-08-03 20:18
I believe this is a dupe of #1139

**Comment by jacobbednarz** [comment] 2021-08-03 22:57
Yep, let's track any progress in #1139.

**Closed** 2021-08-03 22:57 UTC
Labels: kind/bug, triage/needs-information
