### ISSUE TITLE
provider crashes when importing cloudflare_ruleset

### ISSUE THREAD

**Issue by ewhite62** [cloudflare/terraform-provider-cloudflare#2501] opened 2023-06-05 17:17 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

4.2, 4.7, 4.7.1

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "inf_request_header_transforms" {
  zone_id = var.zone_id
  name    = "transform rule to add a request header"
  kind    = "zone"
  phase   = "http_request_late_transform"

  dynamic "rules" {
    for_each = toset(var.inf_request_header_transforms)
    content {
      action = "rewrite"
      action_parameters {
        headers {
          name       = rules.value.name
          value      = rules.value.value
          operation  = "set"
        }
        headers {
          name       = rules.value.name
          expression = rules.value.expression
          operation  = "set"
        }

      }
      expression  = "true"
      description = rules.value.description
      enabled     = true
    }
  }
}
```

### Link to debug output

no debug since it panics

### Panic output

% terraform import module.inf.cloudflare_ruleset.inf_request_header_transforms 90001b768d8c4877a8a8d0fc15d97c2e
data.cloudflare_zones.zone: Reading...
data.cloudflare_zones.zone: Read complete after 0s [id=6b3452bfb2d4f757eef9def2de6f9cb0]
module.inf.cloudflare_ruleset.inf_request_header_transforms: Importing from ID "90001b768d8c4877a8a8d0fc15d97c2e"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.2.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 181 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).ImportState(0x1d9aea0?, {0x1d9aea0, 0xc000137ad0}, {{0xc0001e82e0?, 0x1c1a559?}}, 0xc0000fc2d0)
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:276 +0x448
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc0001f71e0, {0x1d9aea0, 0xc000137ad0}, 0xc000398c60, 0xc0005ff408)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_importresourcestate.go:104 +0x462
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc0001f71e0, {0x1d9aea0?, 0xc000137980?}, 0xc0008b0120)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_importresourcestate.go:44 +0x30b
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ImportResourceState({0xc00046a6f0, 0xc00046a750, {0xc0004ff6c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf6muxserver/mux_server_ImportResourceState.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc0000eb040, {0x1d9aea0?, 0xc0004fd440?}, 0xc0000f9630)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:846 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x1bb3020?, 0xc0000eb040}, {0x1d9aea0, 0xc0004fd440}, 0xc00025c000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014e1e0, {0x1d9fbb8, 0xc0005829c0}, 0xc000906120, 0xc000349800, 0x2396f98, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc00014e1e0, {0x1d9fbb8, 0xc0005829c0}, 0xc000906120, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v4.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

eric.white@AC02GJ1RCMD6Q zone_wd5.megaleo.com % terraform import module.inf.cloudflare_ruleset.inf_request_header_transforms 90001b768d8c4877a8a8d0fc15d97c2e 
eric.white@AC02GJ1RCMD6Q zone_wd5.megaleo.com % TF_LOG=DEBUG
eric.white@AC02GJ1RCMD6Q zone_wd5.megaleo.com % terraform import module.inf.cloudflare_ruleset.inf_request_header_transforms 90001b768d8c4877a8a8d0fc15d97c2e
data.cloudflare_zones.zone: Reading...
data.cloudflare_zones.zone: Read complete after 0s [id=6b3452bfb2d4f757eef9def2de6f9cb0]
module.inf.cloudflare_ruleset.inf_request_header_transforms: Importing from ID "90001b768d8c4877a8a8d0fc15d97c2e"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.2.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 244 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).ImportState(0x1d9aea0?, {0x1d9aea0, 0xc000ae9ad0}, {{0xc000ac4000?, 0x1c1a559?}}, 0xc0001b5180)
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:276 +0x448
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc0000f2160, {0x1d9aea0, 0xc000ae9ad0}, 0xc000a54360, 0xc000165408)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_importresourcestate.go:104 +0x462
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc0000f2160, {0x1d9aea0?, 0xc000ae9980?}, 0xc00041e4c0)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_importresourcestate.go:44 +0x30b
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ImportResourceState({0xc00045e6f0, 0xc00045e750, {0xc0001bb060, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf6muxserver/mux_server_ImportResourceState.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc000562dc0, {0x1d9aea0?, 0xc000ae8030?}, 0xc0001b4190)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:846 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x1bb3020?, 0xc000562dc0}, {0x1d9aea0, 0xc000ae8030}, 0xc0002dc0e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000332000, {0x1d9fbb8, 0xc000103520}, 0xc000a9e240, 0xc0004cfce0, 0x2396f98, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc000332000, {0x1d9fbb8, 0xc000103520}, 0xc000a9e240, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v4.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

a correct import of the resource

### Actual output

see panic output

### Steps to reproduce

1) terraform state show module.inf.cloudflare_ruleset.inf_request_header_transforms
```
resource "cloudflare_ruleset" "inf_request_header_transforms" {
    id      = "90001b768d8c4877a8a8d0fc15d97c2e"
    kind    = "zone"
```
...
terraform state rm module.inf.cloudflare_ruleset.inf_request_header_transforms
<upgrade to 4.x>
terraform import module.inf.cloudflare_ruleset.inf_request_header_transforms 90001b768d8c4877a8a8d0fc15d97c2e

**Comment by ewhite62** [comment] 2023-06-05 17:40
I had removed the resource from the state file, and now I am just trying to get back to my working baseline on 3.35 so we can continue working, but I cannot import the resource now
```│ Error: invalid id ("90001b768d8c4877a8a8d0fc15d97c2e") specified, should be in format "resourceType/resourceTypeID/rulesetID

**Comment by jacobbednarz** [comment] 2023-06-05 23:33
duplicate of #2502 which has the reproduction case and correct debug output.

**Closed** 2023-06-05 23:33 UTC
Labels: kind/bug, triage/needs-information
