### ISSUE TITLE
resource cloudflare_access_application doesn't include type private_ip

### ISSUE THREAD

**Issue by halradaideh** [cloudflare/terraform-provider-cloudflare#3073] opened 2024-01-21 08:26 UTC
### Current Terraform and Cloudflare provider version

tf 1.2.4
provider 4.22.0

### Description

the resource doesn't include the type
i imported the resource using the documentation, but it seems the provider doesn't support it

### Use cases

applications based on tcp 

### Potential Terraform configuration

resource "cloudflare_access_application" "routing_app" {
  name                      = "x"
  type                      = "private_ip"
}

**Comment by jacobbednarz** [comment] 2024-01-21 10:12
duplicate of #1974 and #2995

**Closed** 2024-01-21 10:12 UTC
Labels: kind/enhancement, needs-triage
