### ISSUE TITLE
Ruleset: handling creation of phase result to exceeded maximum number of zone rulesets for phase 'XxX' if already created via the dash

### ISSUE THREAD

**Issue by vences** [cloudflare/terraform-provider-cloudflare#1222] opened 2021-09-27 10:24 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
➜ terraform -v
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.1

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

"cloudflare_ruleset" is the resource affected. In the way it is created there is a first POST to create the phase and if a configuration was already created on the dash then it fail. 
You will need to delete the phase via API `DELETE` -> `https://api.cloudflare.com/client/v4/zones/{{zone_id}}/rulesets/:schema-ruleset-id`

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "terraform_standard_headers" {
  zone_id = var.cloudflare_zone_id
  name = "header modification"
  description = ""
  kind = "zone"
  phase = "http_request_late_transform"
  rules {
    action = "rewrite"
    action_parameters {
     headers {
        name = "header1"
        operation = "set"
        value = "Test"
      }
    }
    expression = "true"
    description = "Standard Origin Headers"
    enabled = true
  }
}
```

### Debug output

[terraform.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/7235419/terraform.log)

```
Error: error creating ruleset header modification: HTTP status 400: exceeded maximum number of zone rulesets for phase 'http_request_late_transform'
│ 
│   with cloudflare_ruleset.terraform_standard_headers,
│   on headers.tf line 1, in resource "cloudflare_ruleset" "terraform_standard_headers":
│    1: resource "cloudflare_ruleset" "terraform_standard_headers" {
```

Error should be seen on the first POST. I then delete the phase and apply again the configuration and all was fixed. The tricky thing here is when the headers is configured via the Dash removing the rules on the dash doesn't removed the phase and need to be done via API.

### Expected output

```
cloudflare_ruleset.terraform_standard_headers: Creating...
cloudflare_ruleset.terraform_standard_headers: Creation complete after 4s [id=<ID>]
```

### Actual output

```
Error: error creating ruleset header modification: HTTP status 400: exceeded maximum number of zone rulesets for phase 'http_request_late_transform'
│ 
│   with cloudflare_ruleset.terraform_standard_headers,
│   on headers.tf line 1, in resource "cloudflare_ruleset" "terraform_standard_headers":
│    1: resource "cloudflare_ruleset" "terraform_standard_headers" {
```

### Steps to reproduce

1. Create a header modification on the dash
2. Remove it and move your configuration to Terraform
3. Apply your Terraform configuration
4. You will get the error exceeded max number
5. Remove the ruleset via API
6. Apply again your configuration
7. It is a success

### Additional factoids

That apply to any other configuration done via Ruleset. The phase should not been created via dash otherwise you get that issue. I am not sure if the first POST can be handled in a better way to avoid that issue.

**Comment by jacobbednarz** [comment] 2021-09-27 11:11
Similar to #1210, I think this is one of those good but also bad things. It's good as people who try and manage the resource in the dash and Terraform will get the error (saving themselves a bit of a headache later) but bad because even the empty Ruleset will trigger the failure. 

I nearly dropped the initial POST request last week but I had a concern that changing to only PUT on it's own would override everything already there. If the resource is already present in the dash and someone applies a change, that will be lost which feels unexpected and the Terraform diff won't make sense to the end user since it will only show the creation of a new resource.

**Comment by vences** [comment] 2021-09-27 12:53
Thanks @jacobbednarz and sorry for the duplicate didn't see it when I was looking for similar bug (my search skill fail me :) )

I am not sure either what would be the best way. Can the error be more explicit for terraform, or running a test if the Ruleset is already there and advertise the user back, that may avoid some confusion linked to that error and let us be more self sufficient (without raising error or coming back to the account team)

**Comment by jacobbednarz** [comment] 2021-09-27 21:10
No sweat, that's totally fine. In the case of Rulesets, we have been passing the exception message straight back to the user as it is pretty descriptive to the cause. For this particular case, we could throw a more explicit message if the "exceeded maximum number" string was detected however how would you expect to differentiate entitlement issues versus dangling issues? In the case of the API error, they will both be the same, and it may be confusing to suggest cleaning up other rules if you've just exhausted the entitlement allocation.

**Comment by jacobbednarz** [comment] 2021-09-27 23:12
Side note, even if we remove the initial POST for the sake of using the entrypoint endpoint directly, I'd still want a GET to check if the phase exists to prevent blindly overwriting the existing Ruleset phase with whatever Terraform is trying to apply to prevent people from accidentally blowing away their existing configuration.

**Comment by jacobbednarz** [comment] 2021-09-28 04:17
I'm going to close this out as for now, this is marked as desirable behaviour. I'll have a chat with the teams internally and see if we want to change anything to enable clearer causes here.

**Closed by jacobbednarz** 2021-09-28 04:17 UTC
Labels: kind/bug, needs-triage
