### ISSUE TITLE
page_rule priority

### ISSUE THREAD

**Issue by ZebraFlesh** [cloudflare/terraform-provider-cloudflare#767] opened 2020-08-16 13:47 UTC
### Terraform Version
```
% terraform -v
Terraform v0.13.0
+ provider registry.terraform.io/terraform-providers/cloudflare v2.9.0
```

### Affected Resource(s)
- cloudflare_page_rule

### Terraform Configuration Files
```hcl
terraform {
  backend "local" {}
  required_providers {
    cloudflare = {
      source = "terraform-providers/cloudflare"
    }
  }
  required_version = "~> 0.13"
}

provider "cloudflare" {
  version = "~> 2.9"
}

variable "filter" {
  type    = string
}

variable "primary" {
  type    = string
  default = "dev"
}

variable "secondary" {
  type    = string
  default = "qa"
}

data "cloudflare_zones" "my-zone" {
  filter {
    name = "${var.filter}"
  }
}

resource "cloudflare_page_rule" "rule-4" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.secondary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.json"
  priority   = 4
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-3]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-3" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.secondary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.html"
  priority   = 3
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-2]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-2" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.primary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.json"
  priority   = 2
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-1]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-1" {
  zone_id  = data.cloudflare_zones.my-zone.zones[0].id
  target   = "${var.primary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.html"
  priority = 1
  status   = "active"
  actions {
    cache_level = "cache_everything"
  }
}
```

### Expected Behavior
Per the [solution in #187](https://github.com/cloudflare/terraform-provider-cloudflare/issues/187#issuecomment-450987683), this should have created page rules in the following order:
1. rule-1
2. rule-2
3. rule-3
4. rule-4

### Actual Behavior
Rules are created in reverse order. Cloudflare dashboard shows:
1. rule-4
2. rule-3
3. rule-2
4. rule-1

Script output:
```bash
% terraform apply -auto-approve  
data.cloudflare_zones.my-zone: Refreshing state...
data.cloudflare_zones.my-zone: Reading... [id=2020-08-16 13:28:46.484733 +0000 UTC]
data.cloudflare_zones.my-zone: Read complete after 0s [id=2020-08-16 13:28:47.242083 +0000 UTC]
cloudflare_page_rule.rule-1: Creating...
cloudflare_page_rule.rule-1: Creation complete after 1s [id=79c52b9c50092184fd7b02131e847bdd]
cloudflare_page_rule.rule-2: Creating...
cloudflare_page_rule.rule-2: Creation complete after 1s [id=9bdfaab23ccc67a5a1c9998c34e320ee]
cloudflare_page_rule.rule-3: Creating...
cloudflare_page_rule.rule-3: Creation complete after 1s [id=f4fb44c51dc451fc2abb8f11faa05200]
cloudflare_page_rule.rule-4: Creating...
cloudflare_page_rule.rule-4: Creation complete after 0s [id=e0c2d42cc0388b1a4e98dfe0253cece8]
```

### Steps to Reproduce
1. `terraform apply -var="filter=<zone filter string>"`

### Important Factoids
There are no page rules on this zone when I run this script. The solution as described in #187 made sense, but the output was the reverse of what I expected. So I tried reversing the `page_rule` resources (after a `terraform destroy`), but the output got even stranger:

```hcl
resource "cloudflare_page_rule" "rule-1" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.primary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.html"
  priority   = 1
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-2]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-2" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.primary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.json"
  priority   = 2
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-3]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-3" {
  zone_id    = data.cloudflare_zones.my-zone.zones[0].id
  target     = "${var.secondary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.html"
  priority   = 3
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-4]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-4" {
  zone_id  = data.cloudflare_zones.my-zone.zones[0].id
  target   = "${var.secondary}.${data.cloudflare_zones.my-zone.zones[0].name}/*.json"
  priority = 4
  status   = "active"
  actions {
    cache_level = "cache_everything"
  }
}
```

Result in Cloudflare dashboard:
1. rule-3
2. rule-2
3. rule-4
4. rule-1

Script output:
```bash
% terraform apply -auto-approve  
data.cloudflare_zones.my-zone: Refreshing state...
data.cloudflare_zones.my-zone: Reading... [id=2020-08-16 13:32:21.826561 +0000 UTC]
data.cloudflare_zones.my-zone: Read complete after 0s [id=2020-08-16 13:32:22.673509 +0000 UTC]
cloudflare_page_rule.rule-4: Creating...
cloudflare_page_rule.rule-4: Creation complete after 1s [id=e0c2d42cc0388b1a4e98dfe0253cece8]
cloudflare_page_rule.rule-3: Creating...
cloudflare_page_rule.rule-3: Creation complete after 0s [id=f4fb44c51dc451fc2abb8f11faa05200]
cloudflare_page_rule.rule-2: Creating...
cloudflare_page_rule.rule-2: Creation complete after 1s [id=9bdfaab23ccc67a5a1c9998c34e320ee]
cloudflare_page_rule.rule-1: Creating...
cloudflare_page_rule.rule-1: Creation complete after 1s [id=79c52b9c50092184fd7b02131e847bdd]
```

### References
- #187

**Comment by jacobbednarz** [comment] 2020-08-16 21:13
Thanks for raising this new issue! It's a vast improvement over #765 and provides enough detail that the maintainers can dig into to confirm whether or not there is a bug present 👏

**Comment by jacobbednarz** [comment] 2020-08-16 21:37
Looking over your issue and my local reproduction test case, the outcome looks as intended and correct (what you got in the first instance in your actual behaviour section). The highest priority rule is applied in position 1, second highest in position 2 and so on. 

The expected behaviour is what is off a bit; if you wanted the ordering to be rule-1, rule-2, rule-3 and finally rule-4, the correct incantation would have been:

```hcl
resource "cloudflare_page_rule" "rule-1" {
  // .. snip
  priority   = 4
}

resource "cloudflare_page_rule" "rule-2" {
  // .. snip
  priority   = 3
  depends_on = [cloudflare_page_rule.rule-1]
}

resource "cloudflare_page_rule" "rule-3" {
  // .. snip
  priority   = 2 
  depends_on = [cloudflare_page_rule.rule-2]
}

resource "cloudflare_page_rule" "rule-4" {
  // .. snip
  priority = 1
  depends_on = [cloudflare_page_rule.rule-3]
}
``` 

https://github.com/cloudflare/terraform-provider-cloudflare/issues/187#issuecomment-450987683 gives a full example of this in practice showing what (and how) the two systems interact and what you need to do in order to have it play nice in both.

**Comment by ZebraFlesh** [comment] 2020-08-17 19:39
> The expected behaviour is what is off a bit; if you wanted the ordering to be rule-1, rule-2, rule-3 and finally rule-4, the correct incantation would have been:

I tried the above and the cloudflare dashboard shows me an ordering of:
1. rule-2
2. rule-3
3. rule-1
4. rule-4

The explanation in #187 makes sense, but I have yet to observe behavior which matches the explanation. It's a bit crazy making.

**Comment by jacobbednarz** [comment] 2020-08-17 22:54
My example above had the `depends_on` in the reverse order which goes to show how confusing it is 🙂 This is still working as noted in the original PR, you will just need to adjust it to your rules.

```hcl
variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "cloudflare_zone_id" {}
variable "cloudflare_domain" {}

provider "cloudflare" {
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

resource "cloudflare_page_rule" "rule-1" {
  zone_id    = var.cloudflare_zone_id
  target     = "${var.cloudflare_domain}/*.1"
  priority   = 4
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-2]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-2" {
  zone_id    = var.cloudflare_zone_id
  target     = "${var.cloudflare_domain}/*.2"
  priority   = 3
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-3]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-3" {
  zone_id    = var.cloudflare_zone_id
  target     = "${var.cloudflare_domain}/*.3"
  priority   = 2
  status     = "active"
  depends_on = [cloudflare_page_rule.rule-4]
  actions {
    cache_level = "cache_everything"
  }
}

resource "cloudflare_page_rule" "rule-4" {
  zone_id  = var.cloudflare_zone_id
  target   = "${var.cloudflare_domain}/*.4"
  priority = 1
  status   = "active"
  actions {
    cache_level = "cache_everything"
  }
}

```

![](https://shares.jacobbednarz.com/b0hjd-qtuds-mviwc.png)

**Comment by jacobbednarz** [comment] 2020-08-17 22:55
Closing as this isn't a bug within the provider, just a misunderstanding on how to achieve the desired outcome.

**Closed by jacobbednarz** 2020-08-17 22:55 UTC

**Comment by ZebraFlesh** [comment] 2020-08-17 23:02
Thanks, that finally worked. Is there a place where this could be better documented? Clearly it's confusing.

**Comment by jacobbednarz** [comment] 2020-08-17 23:09
It's definitely difficult to grok the two systems at play here and their interactions. The documentation (and workarounds) is that PR thread. We could potentially put it on the website but it will still be the same content; just in a different place. The issue I created above was trying to take the concept in that thread, understand your use case and watch for bugs which was clearly too much to be doing in a single step.

**Comment by ZebraFlesh** [comment] 2020-08-18 00:05
@jacobbednarz I've read #187 and this issue, but I don't understand _why_ this works. Can you shed some light? For example, reading this HCL code, `rule-4` should be create first (because everything depends on it), but it's created with `priority = 1`. Yet `rule-1` eventually has `priority = 1`. That tells me `rule-1` is actually created before `rule-4` ... but then how does `depends_on` work?

**Comment by jacobbednarz** [comment] 2020-08-18 05:34
To best understand this, you need to think of the systems in two parts, not as one.

Terraform uses a declarative load order and you can chain dependencies. Take the following example:

```hcl
resource "cloudflare_page_rule" "rule-4" {
  // .. snip
  depends_on = [cloudflare_page_rule.rule-3]
}

resource "cloudflare_page_rule" "rule-3" {
  // .. snip
  depends_on = [cloudflare_page_rule.rule-2]
}

resource "cloudflare_page_rule" "rule-2" {
  // .. snip
  depends_on = [cloudflare_page_rule.rule-1]
}

resource "cloudflare_page_rule" "rule-1" {
  // .. snip
}
```

Terraform will walk the resource tree and discover the following relationships:

- `rule-4` requires `rule-3`; but
- `rule-3` requires `rule-2`; but
- `rule-2` requires `rule-1`; and
- `rule-1` has no dependencies

This means Terraform can create `rule-1` without any dependencies, so it does. Now that `rule-1` is satisfied, it can move back up the tree to `rule-2`, so on and so forth until it completes the transversal. 

_Note: You can visually check this in Terraform using `terraform graph`_

Now, diving into the Cloudflare side of things, it requires that `priority` values are sequential without any gaps. If it encounters a missing sequence, it will collapse it.

Using our understanding of Terraform's dependency chaining, we can now put the priorities in place where the lowest priority rule will be applied first. Here, that is `rule-1`.

**Comment by ZebraFlesh** [comment] 2020-08-18 13:09
Thanks, that's very helpful and was how I thought it worked. However, your example code above has inverse priorities from [the code that was demonstrated to work](https://github.com/cloudflare/terraform-provider-cloudflare/issues/767#issuecomment-675154546). That's where I'm confused: I _thought_ I had to do the ordering as you just described, but it turns out it needs to be reversed as in your earlier comment. Indeed, running this latest code gives rules in the order 4/3/2/1 instead of the desired 1/2/3/4 order.

Considering [your working code from earlier]((https://github.com/cloudflare/terraform-provider-cloudflare/issues/767#issuecomment-675154546):
```hcl
resource "cloudflare_page_rule" "rule-1" {
  // .. snip
  priority   = 4
  depends_on = [cloudflare_page_rule.rule-2]
}

resource "cloudflare_page_rule" "rule-2" {
  // .. snip
  priority   = 3
  depends_on = [cloudflare_page_rule.rule-3]
}

resource "cloudflare_page_rule" "rule-3" {
  // .. snip
  priority   = 2
  depends_on = [cloudflare_page_rule.rule-4]
}

resource "cloudflare_page_rule" "rule-4" {
  // .. snip
  priority = 1
}
```

With the explanation you just offered:
* rule-4 would be created first because of the dependency chain; it would have priority 1 because Cloudflare won't permit any holes in the priority
* rule-3 would be created next, with the listed priority 2
* rule-2 would be created next, with the listed priority 3
* rule-1 would be created last, with the listed priority 4

However, that's not what happens: the rules are created with a priority that matches the number in their name (1/2/3/4). This is where I'm confused and can't puzzle out an explanation for how it works.

**Comment by jacobbednarz** [comment] 2020-08-18 18:25
Do you mean the priority numbers in the UI? If so, they are reversed (per the screen shot and working example). You need to be looking at the API response which the highest priority gets put at the top.

**Comment by ZebraFlesh** [comment] 2020-08-18 18:29
Yes, I mean the priority numbers in the UI. 

> they are reversed (per the screen shot and working example)

Are you saying that the UI and the API give different responses for the same data? (I guess a better way of saying it is: the UI represents the data differently from the UI.)

**Comment by jacobbednarz** [comment] 2020-08-18 18:38
Correct - that **is not** the priority 🙂 Page rules are evaluated top to bottom  in that list. The priority, not shown, is what builds that ordering and you need to look at the API response to see it.

**Comment by ZebraFlesh** [comment] 2020-08-18 19:02
I looked at the CF API docs and I think this is finally starting to make sense: it looks like CF considers priority = 1 as low and priority = 100 as high; I had assumed that 1 was high and 100 was low. Thanks for taking the time and setting me on the right path!
