### ISSUE TITLE
Email Routing Support

### ISSUE THREAD

**Issue by cloudily** [cloudflare/terraform-provider-cloudflare#1594] opened 2022-05-04 00:48 UTC
### Current Terraform and Cloudflare provider version

3.12.2

### Description

Terraform support for Email Routing under Zone > Email > Routes would help manage email forwarding per domain.  Couldn't find any API docs for this; possibly since the feature is still in beta. Here's what I could found by looking at the network requests.

```
POST /api/v4/zones/{zoneId}/email/routing/rules
```

**Drop Example:**

```
Body:
{"enabled":true,"name":"Rule created at 2022-05-04T00:00:00.000Z","actions":[{"type":"drop"}],"matchers":[{"type":"literal","field":"to","value":"x@x.x"}]}

Response:
{"result":{"tag":"{32byteId}","name":"Rule created at 2022-05-04T00:00:00.000Z","matchers":[{"type":"literal","field":"to","value":"x@x.x"}],"actions":[{"type":"drop"}],"enabled":true},"success":true,"errors":[],"messages":[]}
```

**Forward Example:**

```
Body:
{"enabled":true,"name":"Rule created at 2022-05-04T00:00:00.000Z","actions":[{"type":"forward","value":["fwd@x.x"]}],"matchers":[{"type":"literal","field":"to","value":"x@x.x"}]}

Response:
{"result":{"tag":"{32byteId}","name":"Rule created at 2022-05-04T00:00:00.000Z","matchers":[{"type":"literal","field":"to","value":"x@x.x"}],"actions":[{"type":"forward","value":["fwd@x.x"]}],"enabled":true},"success":true,"errors":[],"messages":[]}
```

### Use cases

Managing email aliases through code. Adding new forwarding emails. Ability to disable, mark them as drop as needed.

### Potential Terraform configuration

```hcl
# enabled = true is default

resource "cloudflare_zone_email" "drop_at_domain" {
  type = "drop"
  to = "drop@domain"
}

resource "cloudflare_zone_email" "fwd_at_domain" {
  type = "forward"
  to = "fwd@domain"
  forward = "x@x"
}

resource "cloudflare_zone_email" "disabled_at_domain" {
  type = "forward"
  enabled = false
  to = "disabled@domain"
  forward = "x@x"
}
```

**Comment by jacobbednarz** [comment] 2022-05-04 01:04
duplicate of #1460. please subscribe to the issue to track updates.

**Closed by jacobbednarz** 2022-05-04 01:04 UTC
Labels: kind/enhancement, needs-triage
