### ISSUE TITLE
Duplicate ID assignment for multiple cloudflare_list_item resources

### ISSUE THREAD

**Issue by agesta23** [cloudflare/terraform-provider-cloudflare#2848] opened 2023-10-13 20:03 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.6.1
on darwin_arm64
```

### Affected resource(s)

`cloudflare_list_item`

### Terraform configuration files

```hcl
resource "cloudflare_list_item" "this_item" {
  for_each    = { for entry in var.ip_entries : entry.ip => entry }

  account_id  = var.account_id
  list_id     = cloudflare_list.this.id
  comment     = each.value.comment
  ip          = each.value.ip
}
```

### Link to debug output

https://gist.github.com/agesta23/83f8b7bf5eaa618a2c0b99dda4cdcd82

### Expected output

- When creating multiple Cloudflare list items using the cloudflare_list_item resource in a Terraform module, each resource should be assigned a unique ID based on the Cloudflare list item that was created.

### Actual output

- Upon running Terraform apply and examining the state, I found that different cloudflare_list_item resources were mapped to the same Cloudflare list item ID. 

### 1. Define Cloudflare resources:

- Create a cloudflare_list and cloudflare_list_item resources in your Terraform configuration.

```
resource "cloudflare_list" "this" {
  account_id  = var.account_id
  name        = var.name
  description = var.description
  kind        = "ip"
}

resource "cloudflare_list_item" "this_item" {
  for_each    = { for entry in var.ip_entries : entry.ip => entry }
  account_id  = var.account_id
  list_id     = cloudflare_list.this.id
  comment     = each.value.comment
  ip          = each.value.ip
}
```

### 2. Module Setup:

```
module "cloudflare_ip_list" {
  source      = "./path_to_your_module"
  account_id  = "your_account_id"
  name        = "my_ip_list"
  description = "This is a test IP list"
  ip_entries = [
    {
      ip      = "22.11.33.44"
      comment = "dummy ip 1"
    },
    {
      ip      = "22.11.33.55"
      comment = "dummy ip 2"
    },
    {
      ip      = "22.11.33.88"
      comment = "dummy ip 3"
    }
  ]
}
```
### 3. Configuration apply.

- Run `terraform apply` and confirm the creation of the resources.

### 4. Observe output(if defined) or state file

```
cloudflare_list_id = "redacted"
cloudflare_list_item_ids = [
  "506618aea5c64452b2a3397b69ac9ab6",
  "506618aea5c64452b2a3397b69ac9ab6",
  "506618aea5c64452b2a3397b69ac9ab6"
]
```

**Comment by danquack** [comment] 2023-10-21 03:25
I think this might be a duplicate of #2559

**Closed** 2023-10-21 05:34 UTC
Labels: triage/duplicate
