### ISSUE TITLE
Create a Data Provider for Cloudflare Access Service Token

### ISSUE THREAD

**Issue by beaudryj** [cloudflare/terraform-provider-cloudflare#2702] opened 2023-08-18 21:02 UTC
### Current Terraform and Cloudflare provider version

1.4.6

### Description

I have been working on a module that creates Access Apps, Tunnels, And Access App Policies. And I have just discovered that If I want to use `service_token` I need parse the API Responses on browser to actually fetch the ID of the service token I wish to use. Its kind of silly to have to do that and it would be nice if it was documented to do so on the access Policy app, or if there was a data provider I could use to pass human readable name to get GUID that I can use to pass to policy

The Current Error That is returned is also not super helpful in determining this being the issue - 

```
│ Error: error creating Access Policy for ID "": error from makeRequest: access.api.error.invalid_request: invalid 'include' configuration (12130)
│ 
│   with module.appset_tunnels["my-dashboard"].cloudflare_access_policy.policy,
│   on .terraform/modules/appset_tunnels/cloudflare.tf line 36, in resource "cloudflare_access_policy" "policy":
│   36: resource "cloudflare_access_policy" "policy" {
│
```

### Use cases

see description

### Potential Terraform configuration

```hcl
locals {
  tunnels = {
    devops-sandbox = {
      "my-dashboard" : {
        "service_endpoint" : "http://localhost:3000",
        "name" : "my-dashboard",
        "environment" : "${lower(var.environment)}",
        "namespace" : "mynamespace",
        "include_conditions" : {
          "service_token" : ["my_token"]
        },
        "cors_rules" : {
          "allow_all_headers" : true,
          "allow_all_methods" : true,
          "allow_all_origins" : true,
        }
      }
    }
  }
}


module "appset_tunnels" {
  for_each              = local.tunnels_exist ? local.tunnels[lower(var.environment)] : {}
  source                = "app.terraform.io/myinfra/bifrost/cloudflare"
  version               = "2.9.0"
  application           = each.key
  session_duration      = var.session_duration
  k8s_namespace         = each.value.namespace
  k8s_secret_name       = "${each.key}-cloudflared"
  k8s_configmap_name    = "${each.key}-cloudflared"
  service_endpoint      = each.value.service_endpoint
  cloudflare_account_id = var.cloudflare_account_id
  environment           = each.value.environment
  cors_settings         = try(each.value.cors_rules, null)
  include_conditions    = each.value.include_conditions
  require_conditions    = try(each.value.require_conditions, null)
  exclude_conditions    = try(each.value.exclude_conditions, null)

  providers = {
    cloudflare = cloudflare
    random     = random
    kubernetes = kubernetes
  }
}
```

**Comment by LennyCastaneda** [comment] 2023-08-21 21:34
Having a data provider would be very helpful for projects that have repos with small blast radius so those values can be used in other modules. Having to copy and paste a api response in browser is something Terraform DP should do...As an enterprise use I'm hoping this issue get prioritized so we can maintain our clean best practices in code.

**Comment by jacobbednarz** [comment] 2023-10-02 01:32
duplicate of #2336

**Closed by jacobbednarz** 2023-10-02 01:32 UTC
Labels: kind/enhancement, needs-triage
