### ISSUE TITLE
Multiple Actions in Page_Rule breaks

### ISSUE THREAD

**Issue by Josh-Love** [cloudflare/terraform-provider-cloudflare#1325] opened 2021-11-30 20:55 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
on darwin_arm64
provider registry.terraform.io/cloudflare/cloudflare v3.4.0

### Affected resource(s)

cloudflare_page_rule

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
    }
  }
}

provider "cloudflare" {
  account_id = var.cf_account_id
  email      = var.cf_email
  api_token  = var.cf_api_token
}

resource "cloudflare_page_rule" "base_rule" {
  zone_id = var.cf_zone_id
  target  = "my.domain.com/*"
  status  = "active"
  actions {
    always_use_https  = true
    browser_cache_ttl = 0
  }
}
```

### Debug output

2021-11-30T14:47:11.701-0600 [DEBUG] Adding temp file log sink: /var/folders/q4/5bpgpsc51f7fh85qnl_gnz700000gn/T/terraform-log2881000878
2021-11-30T14:47:11.701-0600 [INFO]  Terraform version: 1.0.11
2021-11-30T14:47:11.701-0600 [INFO]  Go runtime version: go1.17.2
2021-11-30T14:47:11.701-0600 [INFO]  CLI args: []string{"/opt/homebrew/bin/terraform", "apply", "-input=false", "-auto-approve"}
2021-11-30T14:47:11.701-0600 [DEBUG] Attempting to open CLI config file: /Users/xxxxxxx/.terraformrc
2021-11-30T14:47:11.701-0600 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-11-30T14:47:11.701-0600 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-11-30T14:47:11.701-0600 [DEBUG] ignoring non-existing provider search directory /Users/xxxxxxx/.terraform.d/plugins
2021-11-30T14:47:11.701-0600 [DEBUG] ignoring non-existing provider search directory /Users/xxxxxxx/Library/Application Support/io.terraform/plugins
2021-11-30T14:47:11.701-0600 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021-11-30T14:47:11.701-0600 [INFO]  CLI command args: []string{"apply", "-input=false", "-auto-approve"}
2021-11-30T14:47:11.702-0600 [DEBUG] New state was assigned lineage "63ea5e9f-057b-aba4-09fa-7db0e132cb35"
2021-11-30T14:47:11.716-0600 [DEBUG] checking for provisioner in "."
2021-11-30T14:47:11.716-0600 [DEBUG] checking for provisioner in "/opt/homebrew/bin"
2021-11-30T14:47:11.716-0600 [INFO]  Failed to read plugin lock file .terraform/plugins/darwin_arm64/lock.json: open .terraform/plugins/darwin_arm64/lock.json: no such file or directory
2021-11-30T14:47:11.716-0600 [INFO]  backend/local: starting Apply operation
2021-11-30T14:47:11.717-0600 [DEBUG] backend/local: Skipping interactive prompts for variables because input is disabled
2021-11-30T14:47:11.717-0600 [DEBUG] created provider logger: level=off
2021-11-30T14:47:11.759-0600 [INFO]  terraform: building graph: GraphTypeValidate
2021-11-30T14:47:11.759-0600 [DEBUG] ProviderTransformer: "cloudflare_page_rule.base_rule" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2021-11-30T14:47:11.759-0600 [DEBUG] ReferenceTransformer: "cloudflare_page_rule.base_rule" references: []
2021-11-30T14:47:11.759-0600 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" references: []
2021-11-30T14:47:11.759-0600 [DEBUG] Starting graph walk: walkValidate
2021-11-30T14:47:11.759-0600 [DEBUG] created provider logger: level=off
2021-11-30T14:47:11.804-0600 [INFO]  backend/local: apply calling Plan
2021-11-30T14:47:11.804-0600 [INFO]  terraform: building graph: GraphTypePlan
2021-11-30T14:47:11.805-0600 [DEBUG] ProviderTransformer: "cloudflare_page_rule.base_rule (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2021-11-30T14:47:11.805-0600 [DEBUG] ReferenceTransformer: "cloudflare_page_rule.base_rule (expand)" references: []
2021-11-30T14:47:11.805-0600 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" references: []
2021-11-30T14:47:11.805-0600 [DEBUG] Starting graph walk: walkPlan
2021-11-30T14:47:11.805-0600 [DEBUG] created provider logger: level=off
2021-11-30T14:47:11.848-0600 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" changed the config value, but that value is unused
2021-11-30T14:47:11.849-0600 [DEBUG] Resource instance state not found for node "cloudflare_page_rule.base_rule", instance cloudflare_page_rule.base_rule
2021-11-30T14:47:11.849-0600 [DEBUG] ReferenceTransformer: "cloudflare_page_rule.base_rule" references: []
2021-11-30T14:47:11.849-0600 [DEBUG] refresh: cloudflare_page_rule.base_rule: no state, so not refreshing
2021-11-30T14:47:11.850-0600 [WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_page_rule.base_rule, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .priority: planned value cty.NumberIntVal(1) for a non-computed attribute
      - .actions[0].disable_apps: planned value cty.False for a non-computed attribute
      - .actions[0].disable_security: planned value cty.False for a non-computed attribute
      - .actions[0].disable_railgun: planned value cty.False for a non-computed attribute
      - .actions[0].disable_performance: planned value cty.False for a non-computed attribute
2021-11-30T14:47:11.853-0600 [INFO]  backend/local: apply calling Apply
2021-11-30T14:47:11.853-0600 [INFO]  terraform: building graph: GraphTypeApply
2021-11-30T14:47:11.853-0600 [DEBUG] Resource state not found for node "cloudflare_page_rule.base_rule", instance cloudflare_page_rule.base_rule
2021-11-30T14:47:11.853-0600 [DEBUG] ProviderTransformer: "cloudflare_page_rule.base_rule (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2021-11-30T14:47:11.853-0600 [DEBUG] ProviderTransformer: "cloudflare_page_rule.base_rule" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/cloudflare/cloudflare"]
2021-11-30T14:47:11.853-0600 [DEBUG] ReferenceTransformer: "cloudflare_page_rule.base_rule" references: []
2021-11-30T14:47:11.853-0600 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" references: []
2021-11-30T14:47:11.853-0600 [DEBUG] ReferenceTransformer: "cloudflare_page_rule.base_rule (expand)" references: []
2021-11-30T14:47:11.853-0600 [DEBUG] Starting graph walk: walkApply
2021-11-30T14:47:11.853-0600 [DEBUG] created provider logger: level=off
2021-11-30T14:47:11.896-0600 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" changed the config value, but that value is unused
2021-11-30T14:47:11.899-0600 [WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_page_rule.base_rule, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .priority: planned value cty.NumberIntVal(1) for a non-computed attribute
      - .actions[0].disable_apps: planned value cty.False for a non-computed attribute
      - .actions[0].disable_security: planned value cty.False for a non-computed attribute
      - .actions[0].disable_railgun: planned value cty.False for a non-computed attribute
      - .actions[0].disable_performance: planned value cty.False for a non-computed attribute
2021-11-30T14:47:11.899-0600 [INFO]  Starting apply for cloudflare_page_rule.base_rule
2021-11-30T14:47:11.899-0600 [DEBUG] cloudflare_page_rule.base_rule: applying the planned Create change

### Expected output

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual output

Error: failed to create page rule: HTTP status 400: Page Rule validation failed: See messages for details. (1004)

> with cloudflare_page_rule.base_rule,
> on cloudflare.tf line 21, in resource "cloudflare_page_rule" "base_rule":
> 21: resource "cloudflare_page_rule" "base_rule" {

### Steps to reproduce

terraform init
terraform validate
terraform plan
terraform apply -input=false -auto-approve

### Additional factoids

If you comment out one of the actions, it will successfully add the page rule. 

This bug does not seem to care about which action is being used, but once there is more than one, the error is thrown. 

Try running this (works):
```
actions {
    # always_use_https = true
    browser_cache_ttl = 0
  }
```

Then this (works): 
```
actions {
    always_use_https = true
    # browser_cache_ttl = 0
}
```

But this breaks:
```
actions {
    always_use_https = true
    browser_cache_ttl = 0
}
```

**Comment by jacobbednarz** [comment] 2021-11-30 21:20
please paste the entire Terraform log, the API calls are missing and the validation message which is causing the error here will be present.

**Comment by Josh-Love** [comment] 2021-11-30 22:46
Sure thing, here is the API call that failed:

```
---[ REQUEST ]---------------------------------------
PUT /client/v4/zones/xxxxxxxxxxxxxxxxxxx/pagerules/xxxxxxxxxxxxxxx HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.0.11 terraform-plugin-sdk/2.8.0 terraform-provider-cloudflare/3.4.0
Content-Length: 284
Authorization: Bearer xxxxxxxxxxxxxxxxxxx
Content-Type: application/json
Accept-Encoding: gzip

{
 "targets": [
  {
   "target": "url",
   "constraint": {
    "operator": "matches",
    "value": "my.domain.com/*"
   }
  }
 ],
 "actions": [
  {
   "id": "always_use_https",
   "value": true
  },
  {
   "id": "browser_cache_ttl",
   "value": 0
  }
 ],
 "priority": 1,
 "status": "active",
 "modified_on": "0001-01-01T00:00:00Z",
 "created_on": "0001-01-01T00:00:00Z"
}
-----------------------------------------------------: timestamp=2021-11-30T16:27:10.480-0600
2021-11-30T16:27:10.907-0600 [INFO]  provider.terraform-provider-cloudflare_v3.4.0: 2021/11/30 16:27:10 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Connection: close
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6b678067d90f2877-DFW
Content-Type: application/json
Date: Tue, 30 Nov 2021 22:27:10 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Sun, 25 Jan 1981 05:00:00 GMT
Pragma: no-cache
Server: cloudflare
HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{
 "success": false,
 "errors": [
  {
   "code": 1004,
   "message": "Page Rule validation failed: See messages for details."
  }
 ],
 "messages": [
  {
   "code": 1,
   "message": ".settings: \"always_use_https\" may not be used with \"any setting\"",
   "type": null
  }
 ],
 "result": null
}
-----------------------------------------------------: timestamp=2021-11-30T16:27:10.906-0600
```

Also, now that I have these https requests in the logs, I think this may be isolated to the `always_use_https` action. I was able to get multiple actions other actions to work when not using that one. 

Working: 
```
actions {
    host_header_override = "my.domain.com"
    browser_cache_ttl    = 0
    edge_cache_ttl       = 1
  }
```

**Comment by jacobbednarz** [comment] 2021-11-30 22:55
correct, the error message is present in that response and the behaviour is intended. 

closing off as expected behaviour.

**Closed** 2021-11-30 22:55 UTC
Labels: kind/support

**Comment by eleleung** [comment] 2022-02-15 21:04
I'm also experiencing this exact issue with a 400 Bad Request being returned when using the `always_use_https` rule - @Josh-Love did you ever figure out what was causing it?

**Comment by Josh-Love** [comment] 2022-02-16 16:31
@eleleung The error message that comes back is: `"always_use_https" may not be used with "any setting".`

Seems like it is expected that if you add the pagerule action of "always_use_https", then you cannot add any other actions. Not sure why the limitation is there, but seems to be the case.

**Comment by eleleung** [comment] 2022-02-21 14:39
@Josh-Love thanks. It turns out that you can use `automatic_https_rewrites` in conjunction with other actions and it seems to have the same effect as `always_use_https`

**Comment by alexkuck-cf** [comment] 2022-06-06 16:25
> @eleleung The error message that comes back is: "always_use_https" may not be used with "any setting".
>
>Seems like it is expected that if you add the pagerule action of "always_use_https", then you cannot add any other actions. Not sure why the limitation is there, but seems to be the case.

Confirming this is expected behavior. `always_use_https` causes Cloudflare's edge to immediately return a 301 to https. Because of the 301, no other settings can be applied.



> @Josh-Love thanks. It turns out that you can use automatic_https_rewrites in conjunction with other actions and it seems to have the same effect as always_use_https

`automatic_https_rewrites` is not equal to `always_use_https`. The former rewrites the links within a webpage to https, he latter returns a 301 to https.

The solution is to create two page rules:

- Page Rule 1 - Target is http://www.example.com. `always_use_https` will cause Cloudflare reply with a 301 to https://www.example.com. No other action can be applied.
- Page Rule 2 - Target is https://www.example.com. Set your multiple actions on this page rule. All traffic that triggers page rule 1 will then trigger this page rule.

**Comment by eleleung** [comment] 2022-06-08 11:04
@alexkuck-cf thanks for clarifying that. It wasn't obvious to me at the time what the correct solution is but I will implement what you've suggested

**Comment by jason-swissre** [comment] 2022-08-16 15:31
Strangly this seems to not fail if you also include the page_priority field
