### ISSUE TITLE
Impossible to have rulesets in different terraform state for a single zone

### ISSUE THREAD

**Issue by lewisn40** [cloudflare/terraform-provider-cloudflare#2588] opened 2023-07-05 21:34 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.1
on windows_amd64
\+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0

### Affected resource(s)

- cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "this" {
  zone_id = data.cloudflare_zone.this.id
  name    = "Append ${var.env} to path"
  kind    = "zone"
  phase   = "http_request_transform"

  rules {
    action = "rewrite"
    action_parameters {
      uri {
        path {
          expression = "concat(\"/${var.env}\",http.request.uri.path)"
        }
      }
    }
    description = "Append ${var.env} to path"
    expression  = "(http.host eq \"${var.env}.example.com\")"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/lewisn40/17371221f2204fa196c30260bdeff8f8

### Expected output

We would like to be able to manage multiple rulesets in the same zone and for the same phase, but from different terraform states.

### Actual output

Depending on the terraform description, it is either replacing the ruleset and all included rules with the latest version of the plan:
```
  # cloudflare_ruleset.this must be replaced
-/+ resource "cloudflare_ruleset" "this" {
      ...
      ~ name        = "Append dev to path" -> "Append qa to path" # forces replacement
      ...
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

or complaining about exisiting similar configuration
```
Error: failed to create ruleset "http_request_transform"
│
│   with cloudflare_ruleset.dev,
│   on main.tf line 21, in resource "cloudflare_ruleset" "dev":
│   21: resource "cloudflare_ruleset" "dev" {
│
│ A similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first import the  
│ existing rules using cf-terraforming. You can find details about how to do this at
│ https://developers.cloudflare.com/terraform/additional-configurations/ddos-managed-rulesets/#optional-delete-existing-rulesets-to-start-from-scratch```

### Steps to reproduce

1. Create a terraform resource with a dynamic ruleset based on some variables
2. Run and apply the plan with a first configuration `terraform plan -var env=dev`
3. Re-run the plan with a new configuration `terraform plan -var env=qa`

### Additional factoids

This scenario is overly simplified, but for backward compatibility we need to use a single zone for our dev and qa environments.  The fact that transform and origin rules must be managed in a single terraform state is a major blocker for us.

### References

I feel it might be related to https://github.com/cloudflare/terraform-provider-cloudflare/issues/2488

**Comment by jacobbednarz** [comment] 2023-07-05 21:39
duplicate of #2423. you cannot manage individual rules outside of the ruleset itself.

**Closed by jacobbednarz** 2023-07-05 21:39 UTC
Labels: kind/bug, needs-triage, triage/debug-log-attached
