### ISSUE TITLE
Data source for ruleset does return empty rules when cloudflare go client does return rules

### ISSUE THREAD

**Issue by ami-descope** [cloudflare/terraform-provider-cloudflare#2915] opened 2023-11-07 15:42 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.6.3
on darwin_arm64

terraform {
  required_providers {
     cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }

}

### Affected resource(s)

* ruleset data source

### Terraform configuration files

```hcl
terraform {
  required_providers {
     cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

data "cloudflare_rulesets" "example" {
  zone_id = "b0568fbe68169ce1aec3c6f82fca4d6b"
  filter {
    phase = "http_ratelimit"
  }
}

output "example" {
  value = data.cloudflare_rulesets.example.rulesets
}

provider "cloudflare" {
  api_token = "REDUCTED"
}
```

### Link to debug output

https://gist.github.com/ami-descope/27667da8769816c38b429b18af6da2bf

### Expected output

the rules should not be empty!

```terraform
{
          + description = ""
          + id          = "be7027900a384d6b9a83d67ae4e13f83"
          + kind        = "zone"
          + name        = "domain-rate-limit"
          + phase       = "http_ratelimit"
          + rules       = []
          + version     = "1"
        },
```

the code for the read in the provider calls the getRuleset
https://github.com/cloudflare/terraform-provider-cloudflare/blob/e389b2aec324e072b091e550b0336016b32e817b/internal/framework/service/rulesets/resource.go#L192C27-L192C37

and I wrote a short go client with the same code

```go
package main

import (
	"context"
	"fmt"
	"github.com/cloudflare/cloudflare-go"
	"log"
)

func main() {
	api, err := cloudflare.NewWithAPIToken("REDUCTED")
	if err != nil {
		log.Fatal(err)
	}

	// Most API calls require a Context
	ctx := context.Background()
	rc := &cloudflare.ResourceContainer{
		Level:      cloudflare.ZoneRouteLevel,
		Identifier: "b0568fbe68169ce1aec3c6f82fca4d6b",
		Type:       cloudflare.ZoneType,
	}

	fmt.Println("fetching ruleset")
	r, err := api.GetRuleset(ctx, rc, "be7027900a384d6b9a83d67ae4e13f83")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("rules %+v", r)
}
```

the result of this call is showing the rules!

```console
go run main.go
fetching ruleset
rules {ID:be7027900a384d6b9a83d67ae4e13f83 Name:domain-rate-limit Description: Kind:zone Version:0x140002a87d0 LastUpdated:2023-11-07 00:01:00.479991 +0000 UTC Phase:http_ratelimit Rules:[{ID:afab56c157c74681be8fa7380a4289a6 Version:0x140002a87e0 Action:block ActionParameters:<nil> Expression:(ends_with(http.host, "domain.dev") and http.host ne "console.domain.dev" and not starts_with(http.request.uri.path, "/.well-known") and not starts_with(http.request.uri.path, "/scim") and not any(http.request.headers["x-domain-sdk-go-version"][*] contains ".") and not any(http.request.headers["x-domain-sdk-python-version"][*] contains ".") and not any(http.request.headers["x-domain-sdk-node-version"][*] contains ".")) Description:default - 100/min LastUpdated:2023-11-07 00:01:00.479991 +0000 UTC Ref:afab56c157c74681be8fa7380a4289a6 Enabled:0x1400009ede0 ScoreThreshold:0 RateLimit:0x140000aa780 ExposedCredentialCheck:<nil> Logging:<nil>}] ShareableEntitlementName:}%
```

so the expected output should have been:

```terraform
{
          + description = ""
          + id          = "be7027900a384d6b9a83d67ae4e13f83"
          + kind        = "zone"
          + name        = "domain-rate-limit"
          + phase       = "http_ratelimit"
          + rules       = [
           {
              name: domain-rate-limit 
              description: ""
              kind: zone
              ...
            }
          ]
          + version     = "1"
        },
```

### Actual output

{
          + description = ""
          + id          = "be7027900a384d6b9a83d67ae4e13f83"
          + kind        = "zone"
          + name        = "domain-rate-limit"
          + phase       = "http_ratelimit"
          + rules       = []
          + version     = "1"
        },

### Steps to reproduce

run this TF code

```terraform
terraform {
  required_providers {
     cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

data "cloudflare_rulesets" "example" {
  zone_id = "b0568fbe68169ce1aec3c6f82fca4d6b"
}

output "example" {
  value = data.cloudflare_rulesets.example.rulesets
}

provider "cloudflare" {
  api_token = "REDUCTED"
}
```

run this go code
```go
package main

import (
	"context"
	"fmt"
	"github.com/cloudflare/cloudflare-go"
	"log"
)

func main() {
        zoneId := "b0568fbe68169ce1aec3c6f82fca4d6b"
	api, err := cloudflare.NewWithAPIToken("REDUCTED")
	if err != nil {
		log.Fatal(err)
	}

	// Most API calls require a Context
	ctx := context.Background()
	rc := &cloudflare.ResourceContainer{
		Level:      cloudflare.ZoneRouteLevel,
		Identifier: zoneId,
		Type:       cloudflare.ZoneType,
	}

	fmt.Println("fetching ruleset...")
	r, err := api.GetRuleset(ctx, rc, zoneId)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("rules %+v", r)
}
```

### Additional factoids
you dont track rules in a ruleset resource:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/e389b2aec324e072b091e550b0336016b32e817b/internal/framework/service/rulesets/resource.go#L305-L313

_No response_

**Comment by jacobbednarz** [comment] 2023-11-07 23:54
the code for the [data source](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/data_source_rulesets.go) is separate to the resource you've referenced here. it looks like you've got steered down the wrong track early in the debugging here which has led you astray into the wrong portion of the codebase. 

taking a look at your reproduction case, you seem to be missing the [`include_rules`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/rulesets#include_rules) which would give you the rules. out of the box, we don't include the rules which aligns with the data source expectations here. can you try including that attribute and let me know if you're still having issues?

**Comment by ami-descope** [comment] 2023-11-08 00:44
My original problem is with pulumi import, so I know that the import calls read, how do I include rules on the import cause what happens is that import is successful but rules are empty

**Comment by jacobbednarz** [comment] 2023-11-08 03:09
if you're having issues with pulumi, i'd recommend opening an issue with their repositories as we don't support that directly or use it myself.

as for the import - within the `Import`, we set the identifier and the `Read` operation builds the state the write. from what i recall, we don't do anything explicitly for creation/import of rules.

i'm closing this off since you mentioned the issue is in pulumi and there isn't anything further we need to do here. if you decide to use the data source, you will need to remember the notes from above.

**Closed by jacobbednarz** 2023-11-08 03:09 UTC
Labels: kind/bug, needs-triage, triage/debug-log-attached

**Comment by ami-descope** [comment] 2023-11-08 03:18
This isn't a pulumi issue please reopen this and read my comments a simple terraform import does not import rules in the rule set so that's a bug with the provider since the go client does fetch them

**Comment by jacobbednarz** [comment] 2023-11-08 03:34
ruleset rules are currently imported when using `Import`. we have an example of this coverage in the acceptance test suite. 

https://github.com/cloudflare/terraform-provider-cloudflare/blob/e389b2aec324e072b091e550b0336016b32e817b/internal/framework/service/rulesets/resource_test.go#L63-L101

i've also manually verified this works as expected on a test zone.


```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
    }
  }
}

provider "cloudflare" {}

resource "cloudflare_ruleset" "terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_managed"
  zone_id = "0d555506aec9767e661a2e19e6d4e711"
  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
      overrides {
        rules {
          action  = "block"
          enabled = false
          id      = "7aeb2faf29284398aeb782e54875e938"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "7babab188b3c40ae87b93ec451f4fd5b"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "23ee7cebe6e8443e99ecf932ab579455"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "76f9871c8e88445b807c9ebcd440c742"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "cd7bd3dbe8fd4add9926ad50068b2a17"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "34da2a5e0a95425d9b0e44f07c641d63"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "2fe273498e964f0bb20ac022d5a14a5e"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "47631a04883d4d7cab6bd7b83478adcb"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "977ad8daef224ecdbe475c7ab3ab3365"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "bdd776b4f296477f960acc346dfa618e"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "49449f901cab4a01b2591ab836babcca"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "d6f6d394cb01400284cfb7971e7aed1e"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "d9aeff22f1024655937e5b033a61fbc5"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "525329e705aa4fa596e126366d02615e"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "8bb4bf582f704b61980fceff442561a8"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "15b0616fe67a439a8a3852410cadd290"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "00bee3de44184f7f8a6ad10910f04e13"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "7b1cfed7fd4047c6949c4d054751ef80"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "d8c7dbf00ec546e48e3c4340486c3ee2"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "ff8b8608c2c14bf5b3de621b6fc2309c"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "71b7793c77e24287861b82f0ec97cf32"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "40cba5ee3a014208958da0855ddfd8e3"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "5dd38056f4cd43fca7f198e6384f1856"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "d384de3d016d414dbf4d14caaa83212b"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "aa3411d5505b4895b547d68950a28587"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "ac89e3a915594a139fc370dece6a8e28"
        }
      }
      version = "latest"
    }
    enabled    = false
    expression = "true"
  }
  rules {
    action = "execute"
    action_parameters {
      id = "4814384a9e5d4991b9815dcfc25d2f1f"
      overrides {
        categories {
          category = "paranoia-level-3"
          enabled  = false
        }
        categories {
          category = "paranoia-level-4"
          enabled  = false
        }
        rules {
          action          = "managed_challenge"
          id              = "6179ae15870a4bb7b2d480d4843b323c"
          score_threshold = 25
        }
      }
      version = "latest"
    }
    enabled    = false
    expression = "true"
  }
}
```

```
terraform import cloudflare_ruleset.terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982 zone/0d555506aec9767e661a2e19e6d4e711/64a2203f3c0246bebc2f39b886d54982
cloudflare_ruleset.terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982: Importing from ID "zone/0d555506aec9767e661a2e19e6d4e711/64a2203f3c0246bebc2f39b886d54982"...
cloudflare_ruleset.terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982: Import prepared!
  Prepared cloudflare_ruleset for import
cloudflare_ruleset.terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982: Refreshing state... [id=64a2203f3c0246bebc2f39b886d54982]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```json
{
  "version": 4,
  "terraform_version": "1.5.4",
  "serial": 1,
  "lineage": "ca82835c-cf99-df22-40dc-20dec35306a1",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "cloudflare_ruleset",
      "name": "terraform_managed_resource_64a2203f3c0246bebc2f39b886d54982",
      "provider": "provider[\"registry.terraform.io/cloudflare/cloudflare\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": null,
            "description": "",
            "id": "64a2203f3c0246bebc2f39b886d54982",
            "kind": "zone",
            "name": "default",
            "phase": "http_request_firewall_managed",
            "rules": [
              {
                "action": "execute",
                "action_parameters": [
                  {
                    "additional_cacheable_ports": null,
                    "algorithms": [],
                    "automatic_https_rewrites": null,
                    "autominify": [],
                    "bic": null,
                    "browser_ttl": [],
                    "cache": null,
                    "cache_key": [],
                    "content": null,
                    "content_type": null,
                    "cookie_fields": null,
                    "disable_apps": null,
                    "disable_railgun": null,
                    "disable_zaraz": null,
                    "edge_ttl": [],
                    "email_obfuscation": null,
                    "from_list": [],
                    "from_value": [],
                    "headers": [],
                    "host_header": null,
                    "hotlink_protection": null,
                    "id": "efb7b8c949ac4650a09736fc376e9aee",
                    "increment": null,
                    "matched_data": [],
                    "mirage": null,
                    "opportunistic_encryption": null,
                    "origin": [],
                    "origin_cache_control": null,
                    "origin_error_page_passthru": null,
                    "overrides": [
                      {
                        "action": null,
                        "categories": [],
                        "enabled": null,
                        "rules": [
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "7aeb2faf29284398aeb782e54875e938",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "7babab188b3c40ae87b93ec451f4fd5b",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "23ee7cebe6e8443e99ecf932ab579455",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "76f9871c8e88445b807c9ebcd440c742",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "cd7bd3dbe8fd4add9926ad50068b2a17",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "34da2a5e0a95425d9b0e44f07c641d63",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "2fe273498e964f0bb20ac022d5a14a5e",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "47631a04883d4d7cab6bd7b83478adcb",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "977ad8daef224ecdbe475c7ab3ab3365",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "bdd776b4f296477f960acc346dfa618e",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "49449f901cab4a01b2591ab836babcca",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "d6f6d394cb01400284cfb7971e7aed1e",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "d9aeff22f1024655937e5b033a61fbc5",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "525329e705aa4fa596e126366d02615e",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "8bb4bf582f704b61980fceff442561a8",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "15b0616fe67a439a8a3852410cadd290",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "00bee3de44184f7f8a6ad10910f04e13",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "7b1cfed7fd4047c6949c4d054751ef80",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "d8c7dbf00ec546e48e3c4340486c3ee2",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "ff8b8608c2c14bf5b3de621b6fc2309c",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "71b7793c77e24287861b82f0ec97cf32",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "40cba5ee3a014208958da0855ddfd8e3",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "5dd38056f4cd43fca7f198e6384f1856",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "d384de3d016d414dbf4d14caaa83212b",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "log",
                            "enabled": false,
                            "id": "aa3411d5505b4895b547d68950a28587",
                            "score_threshold": null,
                            "sensitivity_level": null
                          },
                          {
                            "action": "block",
                            "enabled": false,
                            "id": "ac89e3a915594a139fc370dece6a8e28",
                            "score_threshold": null,
                            "sensitivity_level": null
                          }
                        ],
                        "sensitivity_level": null
                      }
                    ],
                    "phases": null,
                    "polish": null,
                    "products": null,
                    "read_timeout": null,
                    "request_fields": null,
                    "respect_strong_etags": null,
                    "response": [],
                    "response_fields": null,
                    "rocket_loader": null,
                    "rules": null,
                    "ruleset": null,
                    "rulesets": null,
                    "security_level": null,
                    "serve_stale": [],
                    "server_side_excludes": null,
                    "sni": [],
                    "ssl": null,
                    "status_code": null,
                    "sxg": null,
                    "uri": [],
                    "version": "latest"
                  }
                ],
                "description": "",
                "enabled": false,
                "exposed_credential_check": [],
                "expression": "true",
                "id": "126d03a8086d43bebb53e3778ba71074",
                "last_updated": "2023-01-30 01:33:09.294346 +0000 UTC",
                "logging": [],
                "ratelimit": [],
                "ref": "126d03a8086d43bebb53e3778ba71074",
                "version": "1"
              },
              {
                "action": "execute",
                "action_parameters": [
                  {
                    "additional_cacheable_ports": null,
                    "algorithms": [],
                    "automatic_https_rewrites": null,
                    "autominify": [],
                    "bic": null,
                    "browser_ttl": [],
                    "cache": null,
                    "cache_key": [],
                    "content": null,
                    "content_type": null,
                    "cookie_fields": null,
                    "disable_apps": null,
                    "disable_railgun": null,
                    "disable_zaraz": null,
                    "edge_ttl": [],
                    "email_obfuscation": null,
                    "from_list": [],
                    "from_value": [],
                    "headers": [],
                    "host_header": null,
                    "hotlink_protection": null,
                    "id": "4814384a9e5d4991b9815dcfc25d2f1f",
                    "increment": null,
                    "matched_data": [],
                    "mirage": null,
                    "opportunistic_encryption": null,
                    "origin": [],
                    "origin_cache_control": null,
                    "origin_error_page_passthru": null,
                    "overrides": [
                      {
                        "action": null,
                        "categories": [
                          {
                            "action": null,
                            "category": "paranoia-level-3",
                            "enabled": false
                          },
                          {
                            "action": null,
                            "category": "paranoia-level-4",
                            "enabled": false
                          }
                        ],
                        "enabled": null,
                        "rules": [
                          {
                            "action": "managed_challenge",
                            "enabled": null,
                            "id": "6179ae15870a4bb7b2d480d4843b323c",
                            "score_threshold": 25,
                            "sensitivity_level": null
                          }
                        ],
                        "sensitivity_level": null
                      }
                    ],
                    "phases": null,
                    "polish": null,
                    "products": null,
                    "read_timeout": null,
                    "request_fields": null,
                    "respect_strong_etags": null,
                    "response": [],
                    "response_fields": null,
                    "rocket_loader": null,
                    "rules": null,
                    "ruleset": null,
                    "rulesets": null,
                    "security_level": null,
                    "serve_stale": [],
                    "server_side_excludes": null,
                    "sni": [],
                    "ssl": null,
                    "status_code": null,
                    "sxg": null,
                    "uri": [],
                    "version": "latest"
                  }
                ],
                "description": "",
                "enabled": false,
                "exposed_credential_check": [],
                "expression": "true",
                "id": "e22c1c8ac6614d64baf8424205c06fd6",
                "last_updated": "2023-01-30 01:33:09.294346 +0000 UTC",
                "logging": [],
                "ratelimit": [],
                "ref": "e22c1c8ac6614d64baf8424205c06fd6",
                "version": "1"
              }
            ],
            "zone_id": "0d555506aec9767e661a2e19e6d4e711"
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
  "check_results": null
}
```

if you're still seeing issues, i'd recommend opening a new issue *after* you've managed to replicate it with only the terraform provider (not pulumi) and you have clear reproduction steps. the one provided here doesn't demonstrate the issue or articulate what steps you're taking to get the outcome you are.

**Comment by ami-descope** [comment] 2023-11-08 13:27
OK thanks for the details!
