### ISSUE TITLE
Terraform Destroy returns "credentials are not set correctly" but Terraform Apply works 

### ISSUE THREAD

**Issue by code2exe** [cloudflare/terraform-provider-cloudflare#1040] opened 2021-04-21 11:09 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v0.15.0
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1
+ provider registry.terraform.io/vancluever/acme v2.4.0

### Affected resource(s)

cloudflare_origin_ca_certificate
cloudflare_record

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.20.0"
    }
  }
}

provider "cloudflare" {

  # Configuration options
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
    # api_token = var.cloudflare_api_token
  api_user_service_key = var.cloudflare_api_user_service_key
}

resource "cloudflare_record" "okta" {
  name = "_oktaverification.${var.okta_custom_domain_prefix}"
  zone_id = var.cloudflare_zone_id
  type = "TXT"
  ttl = 1
  value = ********
}

 resource "tls_private_key" "example" {
   algorithm = "RSA"
 }

 resource "tls_cert_request" "example" {
   key_algorithm   = tls_private_key.example.algorithm
   private_key_pem = tls_private_key.example.private_key_pem

   subject {
     common_name  = "${var.domain_name}"
     organization = var.org
   }
 }

 resource "cloudflare_origin_ca_certificate" "example" {
   csr                = tls_cert_request.example.cert_request_pem
   hostnames          = [ "${var.domain_name}", "*.${var.domain_name}" ]
   request_type       = "origin-rsa"
   requested_validity = 365
 }

 resource "local_file" "certificate" { 
   filename = "${path.module}/certificate_request.pem"
   content = tls_cert_request.example.cert_request_pem
 }

 resource "local_file" "mykey" { 
   filename = "${path.module}/private_key.pem"
   content = tls_private_key.example.private_key_pem
 }

 resource "local_file" "origin_ca" { 
   filename = "${path.module}/origin_ca_tls.pem"
   content = cloudflare_origin_ca_certificate.example.certificate
 }
```

### Debug output

│ Error: credentials are not set correctly
│
│   on modules\cloudflare\main.tf line 10, in provider "cloudflare":
│   10: provider "cloudflare" {
│
╵

This is the full output

https://gist.github.com/code2exe/a2c76b5412b867f0a2955b4c95081c25

### Expected output

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

### Actual output

 Error: credentials are not set correctly
│
│   on modules\cloudflare\main.tf line 10, in provider "cloudflare":
│   10: provider "cloudflare" {

### Steps to reproduce

terraform destroy

### Additional factoids

The `terraform destroy` command doesn't work but if I comment out the resource I want to delete and run `terraform apply`, it then destroys the desired resource as should have during `terraform destroy`

**Comment by jacobbednarz** [comment] 2021-04-22 04:22
@code2exe are you able to provide the untruncated `TF_LOG=DEBUG` output please? I suspect this is because you have email/key _and_ `api_user_service_key` in use and the authentication mechanism is getting confused however we'll need the output to be certain.

**Comment by code2exe** [comment] 2021-04-22 10:48
> @code2exe are you able to provide the untruncated `TF_LOG=DEBUG` output please? I suspect this is because you have email/key _and_ `api_user_service_key` in use and the authentication mechanism is getting confused however we'll need the output to be certain.

Hi @jacobbednarz 

Yes, you're right. I used the email/key and `api_user_service_key`.  My intention is to create Origin CA certificate and the `api_user_service_key` is required for it.

I have tried to use only `api_token` but I still get that error

**Comment by jacobbednarz** [comment] 2021-04-26 00:47
re: `TF_LOG=DEBUG` output, i need the untruncated version. unfortunately there isn't enough context in that to show what the issue is and what HTTP requests are happening. feel free to redact/scrub any sensitive details before providing it.

**Comment by code2exe** [comment] 2021-04-26 02:35
> re: `TF_LOG=DEBUG` output, i need the untruncated version. unfortunately there isn't enough context in that to show what the issue is and what HTTP requests are happening. feel free to redact/scrub any sensitive details before providing it.

Here is the full output you requested for?

https://gist.github.com/code2exe/01bcf4a1985cb1ef5212b2517e8cf09f

**Comment by code2exe** [comment] 2021-05-07 07:10
> > re: `TF_LOG=DEBUG` output, i need the untruncated version. unfortunately there isn't enough context in that to show what the issue is and what HTTP requests are happening. feel free to redact/scrub any sensitive details before providing it.
> 
> Here is the full output you requested for?
> 
> https://gist.github.com/code2exe/01bcf4a1985cb1ef5212b2517e8cf09f

Hello @jacobbednarz  Any updates on this?

**Comment by jacobbednarz** [comment] 2022-09-28 03:43
closing this one out since there have been multiple improvements in how the authentication works and is handled internally by the provider. 

i'd recommend trying this again with the latest version and if it is still an issue, open a new ticket with the details.

**Closed by jacobbednarz** 2022-09-28 03:43 UTC
Labels: kind/bug, needs-triage
