### ISSUE TITLE
cloudflare logpush job fails if challenge file does not exist from previous runs

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#1009] opened 2021-03-30 18:04 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform version

0.14.9

### Affected resource(s)

cloudflare_logpush_job

### Terraform configuration files
```terraform
resource "cloudflare_logpush_ownership_challenge" "ownership_challenge" {
  depends_on = [google_storage_bucket_iam_policy.add-cf-storage-admin]
  zone_id = var.zoneid
  destination_conf = "gs://${replace(var.global_zonename,".","-")}-logs/logs"
}
data "google_storage_bucket_object_content" "challenge_data" {
  bucket = google_storage_bucket.log-storage.name
  name = cloudflare_logpush_ownership_challenge.ownership_challenge.ownership_challenge_filename

}
resource "cloudflare_logpush_job" "cf_logpush" {
  depends_on = [data.google_storage_bucket_object_content.challenge_data]
  enabled = true
  zone_id = var.zoneid
  name = "all-logs"
  logpull_options = "fields=ParentRayID,RayID,SecurityLevel,SmartRouteColoID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339,sample=1.0"
  destination_conf = "gs://${replace(var.global_zonename,".","-")}-logs/logs"
  ownership_challenge = data.google_storage_bucket_object_content.challenge_data.content
  dataset = "http_requests"
} 
```

### Expected output

logpush job gets created

### Actual output

Error: "ownership_challenge": required field is not set

  on .terraform/modules/LogPush/main.tf line 49, in resource "cloudflare_logpush_job" "cf_logpush":
  49: resource "cloudflare_logpush_job" "cf_logpush" {

### Steps to reproduce

1. paste the code with required supporting provider code
2 execute

### Additional factoids

if i comment the code for logpush and run the challenge resource first separately, then uncomment the logpush resource and run the apply again, it works as expected.

**Comment by jacobbednarz** [comment] 2021-03-30 19:06
duplicate of #954

**Closed as completed** 2021-03-30 19:06 UTC
Labels: triage/duplicate
