### ISSUE TITLE
cloudflare_ruleset produced inconsistent result for preserve_query_string

### ISSUE THREAD

**Issue by florianmutter** [cloudflare/terraform-provider-cloudflare#2408] opened 2023-05-03 10:23 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "stylebop_com_redirect_rules" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_dynamic_redirect"
  zone_id = data.cloudflare_zone.stylebop_com.id
  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 301
        target_url {
          expression = "concat(\"https://www.peek-cloppenburg.de\", http.request.uri.path)"
        }
      }
    }
    description = "Redirect Invoice URL to www.peek-cloppenburg.de"
    enabled     = true
    expression  = "(ends_with(http.host, \"stylebop.com\") and starts_with(http.request.uri.path, \"/s3media\"))"
  }

  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 301
        target_url {
          expression = "concat(\"https://www.peek-cloppenburg.de/de/stylebop\", http.request.uri.path)"
        }
      }
    }
    description = "Redirect to www.peek-cloppenburg.de"
    enabled     = true
    expression  = "(ends_with(http.host, \"stylebop.com\"))"
  }
}
```

### Link to debug output

https://gist.github.com/florianmutter/86feee086b4319fecce056e6e26aa341

### Expected output

No changes for resource.

### Actual output

Error: Provider produced inconsistent result after apply

When applying changes to cloudflare_ruleset.stylebop_com_redirect_rules, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].action_parameters[0].from_value[0].preserve_query_string: was null, but now cty.False.

### Steps to reproduce

1. Create redirect rule in cloudflare dashboard
2. Create configuration in terraform
3. Import existing redirect rule into terraform state
4. Run `terraform apply`

**Comment by jacobbednarz** [comment] 2023-05-05 05:35
thanks for the issue and reproduction case here. this is partially caused by the underlying Go library so i've addressed that in cloudflare/cloudflare-go#1275 and will push up the provider fix once i resolve some local development issues i'm having.

**Comment by cnk** [comment] 2023-05-07 17:34
@jacobbednarz I am getting a very similar error but in my case the error starts when I add a "skip" rule to my cloudflare. I see your cloudflare-go change is merged. Should I just ignore this message until the next cloudflare-go release (which based on previous cadence should be in the next couple of weeks)? The skip rule is created - it just appears to be a problem recording the terraform state thereof.

**Comment by jacobbednarz** [comment] 2023-05-08 00:05
@cnk if you're hitting this specific issue (same field names, error messages, etc) you can follow along here and it will note once it is released and ready to be updated to. otherwise, if you're getting a different issue, i'd recommend opening an issue specific to your setup/output to have it triaged as it may be something different and i can only speculate at this point.

**Closed** 2023-05-11 04:22 UTC
Labels: kind/bug, triage/accepted, triage/debug-log-attached, provider/internals, workflow/synced
