### ISSUE TITLE
404s on page rules

### ISSUE THREAD

**Issue by riuvshyn** [cloudflare/terraform-provider-cloudflare#933] opened 2021-02-03 14:06 UTC
each time I run tf plan / apply it fails on page rules with this:
```
Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"
```

reproduced on 2.17.0 and 2.18.0 provider versions

### Terraform version
13.05

### Affected resource(s)
page_rules

### Debug output
```
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: 181
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: {
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "result": {
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "id": "3815a507b2437f1f8e5e5b3b96c4cd22",
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "targets": [
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: {
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "target": "url",
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "constraint": {
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "operator": "matches",
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "value": "https:\/\/oc.mydomain.com\/remote.php\/dav\/uploads\/*"
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: }
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: }
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: ],
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "actions": [
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: {
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "id": "waf",
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "value": "off"
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: }
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: ],
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "priority": 40,
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "status": "active",
.terraform-provider-cloudflare_v2.18.0: "created_on": "2020-11-06T15:57:46.000000Z",
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "modified_on": "2020-12-06T12:29:07.000000Z"
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: },
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "success": true,
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "errors": [],
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: "messages": []
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: }
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: 0
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0:
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0:
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: -----------------------------------------------------
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: 2021/02/03 14:10:53 [DEBUG] Cloudflare Page Rule read configuration: cloudflare.PageRule{ID:"3815a507b2437f1f8e5e5b3b96c4cd22", Targets:[]cloudflare.PageRuleTarget{cloudflare.PageRuleTarget{Target:"url", Constraint:struct { Operator string "json:\"operator\""; Value string "json:\"value\"" }{Operator:"matches", Value:"https://oc.mydomain.com/remote.php/dav/uploads/*"}}}, Actions:[]cloudflare.PageRuleAction{cloudflare.PageRuleAction{ID:"waf", Value:"off"}}, Priority:40, Status:"active", ModifiedOn:time.Time{wall:0x0, ext:63742854547, loc:(*time.Location)(nil)}, CreatedOn:time.Time{wall:0x0, ext:63740275066, loc:(*time.Location)(nil)}}
2021-02-03T14:10:53.247+0200 [DEBUG] plugin.terraform-provider-cloudflare_v2.18.0: 2021/02/03 14:10:53 [DEBUG] Cloudflare Page Rule actions configuration: map[string]interface {}{"waf":"off"}

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

2021-02-03T14:10:53.250+0200 [WARN] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

### Expected behavior
not fail

### Steps to reproduce
just do tf plan / apply

### Important factoids
amount of 404s each run is different.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jamiemil** [comment] 2021-02-03 17:34
I have similar issues when trying to run terraform to update worker config.

Output -

> VS-LON-MAC90:cloudflare_builder ben.milburn$ ./run_terraform.sh vivastreet.cl apply
Enter passphrase for key '/Users/ben.milburn/.ssh/id_rsa':
Already up to date.
Provisioning vivastreet.cl...

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
cloudflare_worker_route.worker_route_redirect: Refreshing state... [id=d3d823e958b04c75b16a4bd46e52a1d9]
cloudflare_page_rule.page_rule_3: Refreshing state... [id=cb2ba457e22aff6d67e05178fd0ecd16]
cloudflare_record.MX_vivastreet_cl_b3a5c0df0c1885e6363c44554fcc1da9: Refreshing state... [id=b3a5c0df0c1885e6363c44554fcc1da9]
cloudflare_record.CNAME__f0c33cf6fc14c8580a0aacc394e1e700_web08_vivastreet_cl_a6e4c0cf34fffcf5403147556694c5d4: Refreshing state... [id=a6e4c0cf34fffcf5403147556694c5d4]
cloudflare_page_rule.page_rule_1: Refreshing state... [id=ba2bc5731474bdb5e851d8a62da6e56f]
cloudflare_record.TXT_key2__domainkey_marketing_vivastreet_cl_788306b2d51dd28afa6025d266a948d2: Refreshing state... [id=788306b2d51dd28afa6025d266a948d2]
cloudflare_record.TXT_default__domainkey_vivastreet_cl_1ce3bde1a34424099b11c4b8934e6149: Refreshing state... [id=1ce3bde1a34424099b11c4b8934e6149]
cloudflare_record.CNAME_star_web10_vivastreet_cl_ee069966f5b0fdac8a93e67c4f408752: Refreshing state... [id=ee069966f5b0fdac8a93e67c4f408752]
cloudflare_record.CNAME_admin_vivastreet_cl_3b9bf59f190047aab7262e2d6815eb33: Refreshing state... [id=3b9bf59f190047aab7262e2d6815eb33]
cloudflare_record.CNAME_bounce_vivastreet_cl_fbb0ad1dc1aeccfa64e3849c1246c905: Refreshing state... [id=fbb0ad1dc1aeccfa64e3849c1246c905]
cloudflare_record.CNAME_star_web09_vivastreet_cl_c33bbdb851a630d16402e4f0608d2aa0: Refreshing state... [id=c33bbdb851a630d16402e4f0608d2aa0]
cloudflare_record.TXT_scph0318__domainkey_vivastreet_cl_a089243762af4c3f8e1b4ad71e661433: Refreshing state... [id=a089243762af4c3f8e1b4ad71e661433]
cloudflare_custom_pages.custom_pages_500_errors: Refreshing state... [id=c879292aa0f1a3d30e58d669d98f21d7]
cloudflare_record.TXT_marketing_vivastreet_cl_2fefbd084759efe3ca6aac09b3691a5a: Refreshing state... [id=2fefbd084759efe3ca6aac09b3691a5a]
cloudflare_page_rule.page_rule_2: Refreshing state... [id=684b32faeead48cbc98a682e92d741e7]
cloudflare_logpush_job.logpush_job: Refreshing state... [id=16844]
cloudflare_record.CNAME_m_vivastreet_cl_da239eb264d4e79c4a378974c5143fdc: Refreshing state... [id=da239eb264d4e79c4a378974c5143fdc]
cloudflare_record.MX_vivastreet_cl_1e0577c4313742d8dbee69c54d6ad537: Refreshing state... [id=1e0577c4313742d8dbee69c54d6ad537]
cloudflare_page_rule.page_rule_5: Refreshing state... [id=29c6080ef38cc5ff6e55015bfc688b05]
cloudflare_record.CNAME__25af09c4c9ed96aba45f86e2c864353c_web05_vivastreet_cl_17b4dbd8585e32693e93ac4989f704ec: Refreshing state... [id=17b4dbd8585e32693e93ac4989f704ec]
cloudflare_page_rule.page_rule_7: Refreshing state... [id=5003a73894f02205f2943cabf36416e1]
cloudflare_zone_settings_override.zone_settings_override: Refreshing state... [id=268e2c62f566bc03b67aa12a35ce6986]
cloudflare_record.CNAME_star_web03_vivastreet_cl_2a85c58a691cabe35663f05f22ed8b35: Refreshing state... [id=2a85c58a691cabe35663f05f22ed8b35]
cloudflare_record.MX_vivastreet_cl_92a71b345d4bfc5514f4ee58737175d3: Refreshing state... [id=92a71b345d4bfc5514f4ee58737175d3]
cloudflare_record.TXT__dmarc_marketing_vivastreet_cl_668a03ae423d4550062e70addcd27cda: Refreshing state... [id=668a03ae423d4550062e70addcd27cda]
cloudflare_logpush_ownership_challenge.ownership_challenge: Refreshing state... [id=b4ecd3e22c95255839d10329f61d5d21]
cloudflare_zone.zone: Refreshing state... [id=268e2c62f566bc03b67aa12a35ce6986]
cloudflare_filter.filter_country: Refreshing state... [id=ef7dafd56ee646dfa218f8198b1946d8]
cloudflare_page_rule.page_rule_saved_search: Refreshing state... [id=aa52e92b68d32548e3364e5170ec91d7]
cloudflare_record.CNAME_secure_vivastreet_cl_840e8c4c8a896036c096060b633906b7: Refreshing state... [id=840e8c4c8a896036c096060b633906b7]
cloudflare_record.TXT_default__domainkey_sitemail_vivastreet_cl_7cf87fe1bb9f16518d2bc2d3b040a8cc: Refreshing state... [id=7cf87fe1bb9f16518d2bc2d3b040a8cc]
cloudflare_record.CNAME__7f69993e06735ae0640b6e24cf71ed3a_payments_vivastreet_cl_311eafbfef8107cfa1d7b0c5180cba9c: Refreshing state... [id=311eafbfef8107cfa1d7b0c5180cba9c]
cloudflare_record.CNAME_n3ph4yuh2o5j_vivastreet_cl_450f2ef9e749d2ecd880003a273ddca3: Refreshing state... [id=450f2ef9e749d2ecd880003a273ddca3]
cloudflare_record.TXT_vivastreet_cl_ebb7245c4dc6caa8c6dfe40e733ea258: Refreshing state... [id=ebb7245c4dc6caa8c6dfe40e733ea258]
cloudflare_record.CNAME_star_web01_vivastreet_cl_773b871cc84b18c9d985c3ddc77be4f2: Refreshing state... [id=773b871cc84b18c9d985c3ddc77be4f2]
cloudflare_record.CNAME__7f8716a3fff9fd9f981198de6f62af7f_web03_vivastreet_cl_2eb9793f3f2a435d53bdc5342e8b9436: Refreshing state... [id=2eb9793f3f2a435d53bdc5342e8b9436]
cloudflare_record.MX_vivastreet_cl_eb2bfd983d1f5c989dac4edaef814458: Refreshing state... [id=eb2bfd983d1f5c989dac4edaef814458]
cloudflare_record.CNAME__00bd03c1ba13208f039783d3c002f6b2_web02_vivastreet_cl_baa897b34bb28155a3e3dee4fb6263d0: Refreshing state... [id=baa897b34bb28155a3e3dee4fb6263d0]
cloudflare_record.CNAME_payments_vivastreet_cl_2f365cea25a4fbdd2cf10d7977ce3ac6: Refreshing state... [id=2f365cea25a4fbdd2cf10d7977ce3ac6]
cloudflare_record.MX_usermail_vivastreet_cl_cd9dbcaf9e5d1d97c75806a13238bfa1: Refreshing state... [id=cd9dbcaf9e5d1d97c75806a13238bfa1]
cloudflare_record.CNAME__75cc69c04ce3b14ceedf02db13d26b1b_web07_vivastreet_cl_c5760f35fb102635bbe3ba9fd0d4b548: Refreshing state... [id=c5760f35fb102635bbe3ba9fd0d4b548]
cloudflare_record.MX_vivastreet_cl_53f6a175cbb67730dc390f910f55978e: Refreshing state... [id=53f6a175cbb67730dc390f910f55978e]
cloudflare_record.CNAME__216f2f80658f64d134505a57f987ad47_vivastreet_cl_593816c504560baac188ba6aff84d985: Refreshing state... [id=593816c504560baac188ba6aff84d985]
cloudflare_record.CNAME_star_web07_vivastreet_cl_38dede4a738a64970ddd777dc54f4cce: Refreshing state... [id=38dede4a738a64970ddd777dc54f4cce]
cloudflare_record.MX_sitemail_vivastreet_cl_061cf06aa2f0028abee2dad938cb678d: Refreshing state... [id=061cf06aa2f0028abee2dad938cb678d]
cloudflare_record.CNAME_gr425yrqdab4_m_vivastreet_cl_78ea9bfed4f13b91b6468b6190bef433: Refreshing state... [id=78ea9bfed4f13b91b6468b6190bef433]
cloudflare_record.MX_marketing_vivastreet_cl_b4f5724bbe547dd7040b176deaae0f2e: Refreshing state... [id=b4f5724bbe547dd7040b176deaae0f2e]
cloudflare_record.CNAME_viva-origin: Refreshing state... [id=bf265eb78b316862e508442d6d4de572]
cloudflare_record.CNAME_post_vivastreet_cl_d708c9fc55584abbcc3443869fbd48ca: Refreshing state... [id=d708c9fc55584abbcc3443869fbd48ca]
cloudflare_record.CNAME__d19c566adc6f1642d4f356beab6f2e71_web04_vivastreet_cl_bcf460bf8626b0cf6dac6c0a22c6a6fa: Refreshing state... [id=bcf460bf8626b0cf6dac6c0a22c6a6fa]
cloudflare_record.CNAME_star_web02_vivastreet_cl_b327013a2021e9cf520dc0c42e17e4c0: Refreshing state... [id=b327013a2021e9cf520dc0c42e17e4c0]
cloudflare_page_rule.page_rule_4: Refreshing state... [id=2b4c953062c247fbf55eefbf0c0a0c2e]
cloudflare_record.CNAME__0fdfcb4bcdc3490cea64867e6eb9d47b_web09_vivastreet_cl_245aba0e7da3a9b83e6f4c273a1bb56c: Refreshing state... [id=245aba0e7da3a9b83e6f4c273a1bb56c]
cloudflare_record.A_vivastreet_cl_c2ac6643e9f28a028095401431e0243a: Refreshing state... [id=c2ac6643e9f28a028095401431e0243a]
cloudflare_record.CNAME__48601ac8c07a82de8b8589d24a061383_vivastreet_cl_552d038c2a72e4599d949d91b502873f: Refreshing state... [id=552d038c2a72e4599d949d91b502873f]
cloudflare_record.CNAME__bfa348f640a3b5a21915c4e78f17bdec_web40_vivastreet_cl_c67f29e588b077e54da1ec31a39af4f9: Refreshing state... [id=c67f29e588b077e54da1ec31a39af4f9]
cloudflare_record.TXT_vivastreet_cl_4b2d2aa951c3255b6d39a92065b518df: Refreshing state... [id=4b2d2aa951c3255b6d39a92065b518df]
cloudflare_record.CNAME_link_vivastreet_cl_abf270b4ac0ef7fee4adca571529dd3b: Refreshing state... [id=abf270b4ac0ef7fee4adca571529dd3b]
cloudflare_record.CNAME_star_web08_vivastreet_cl_7e7102f2048711db47f454fbbe8f7035: Refreshing state... [id=7e7102f2048711db47f454fbbe8f7035]
cloudflare_record.TXT_sitemail_vivastreet_cl_7b7b34071f442dcedda0ab39e9b1d0c9: Refreshing state... [id=7b7b34071f442dcedda0ab39e9b1d0c9]
cloudflare_record.CNAME_search_vivastreet_cl_c425c30fee3b9f79fad6a139e6b6e7aa: Refreshing state... [id=c425c30fee3b9f79fad6a139e6b6e7aa]
cloudflare_record.CNAME_star_vivastreet_cl_337d74c65c082bb6f2843ebd67bb481b: Refreshing state... [id=337d74c65c082bb6f2843ebd67bb481b]
cloudflare_record.CNAME_vs-static-assets: Refreshing state... [id=bbbe6951c03ae4ece8e06224a159d40f]
cloudflare_record.CNAME_star_web04_vivastreet_cl_f29e0a8dca98375bb5a6c41704de6913: Refreshing state... [id=f29e0a8dca98375bb5a6c41704de6913]
cloudflare_record.MX_vivastreet_cl_7ebb5d62809ab6b1fa63438561336560: Refreshing state... [id=7ebb5d62809ab6b1fa63438561336560]
cloudflare_record.MX_vivastreet_cl_d06af09e34a64f8a54296fd58c37e4ab: Refreshing state... [id=d06af09e34a64f8a54296fd58c37e4ab]
cloudflare_record.CNAME__0fa9ff46713d8b5ca00d8bc9ed552cce_web01_vivastreet_cl_f4be503570bd43ae9017fb5933206762: Refreshing state... [id=f4be503570bd43ae9017fb5933206762]
cloudflare_record.TXT__domainkey_marketing_vivastreet_cl_477308dbf98647e834305cdd7f904f12: Refreshing state... [id=477308dbf98647e834305cdd7f904f12]
cloudflare_filter.filter_referer: Refreshing state... [id=5e94aa5b7a334f2b82d92115ad9c7340]
cloudflare_record.CNAME__b70cf9b97bfe467a6663214b6e307ca0_web10_vivastreet_cl_7f78a6446fa6e5cd786a1ebc7ca17d42: Refreshing state... [id=7f78a6446fa6e5cd786a1ebc7ca17d42]
cloudflare_record.CNAME_www_vivastreet_cl_2af000558ee7c0b74a12c0c1854c1754: Refreshing state... [id=2af000558ee7c0b74a12c0c1854c1754]
cloudflare_record.CNAME_star_web05_vivastreet_cl_e5a76d3449a185bb93a609645d8bbce5: Refreshing state... [id=e5a76d3449a185bb93a609645d8bbce5]
cloudflare_record.CNAME_ayuda_vivastreet_cl_e6aaa5667dff24a40cb0df71adcd2aa4: Refreshing state... [id=e6aaa5667dff24a40cb0df71adcd2aa4]
cloudflare_filter.filter_ip: Refreshing state... [id=2904f109fa814a9b8af4dbbbe38c6e6f]
cloudflare_firewall_rule.firewall_rule_block_countries: Refreshing state... [id=a7e69859e51c4c7e9b09b2bee47838c8]
cloudflare_firewall_rule.firewall_rule_block_referers: Refreshing state... [id=df17f5b0f5224e249193a8a08b39326a]
cloudflare_firewall_rule.firewall_rule_restrict_staging: Refreshing state... [id=76922aba162c4297a1135df8f686e834]

Error: error from makeRequest: HTTP status 404: content "404 page not found\n"

**Comment by jacobbednarz** [comment] 2021-02-03 18:44
@riuvshyn I'm afraid I need more information for the reproduction steps and configuration as this doesn't reproduce on just any configuration. Are you able to provide a bare minimum reproduction case on a new installation?

**Comment by jacobbednarz** [comment] 2021-02-03 18:48
@jamiemil if your issue isn't the same as the original one (resources, steps, etc) please open a new issue following the issue template provided so we can track them separately.

**Comment by canthefason** [comment] 2021-02-03 19:00
We're already in touch with the CF support team regarding this issue, but wanted to share some context here which would help to reproduce it.

After we start running Terraform in debug mode, not sure if it is limited to, but we identified that `/client/v4/zones/:zoneid/custom_pages/:custom_page_type` endpoint is returning sporadic 404s. And regardless of Terraform, even a basic curl request is giving the exact same response.

**Comment by jacobbednarz** [comment] 2021-02-03 19:16
Thanks @canthefason. Looks like this is potential a larger issue with the API and not just Terraform. Let's put this on hold until the internal tickets are addressed.

**Comment by jacobbednarz** [comment] 2021-02-03 19:19
NOTE: In the meantime, don't `terraform apply` changes as most resources that hit 404's will remove the resources from the state file and may end up with undesirable side effects.

**Comment by jacobbednarz** [comment] 2021-02-03 20:47
@riuvshyn @jamiemil @canthefason this issue has been mitigated internally and wasn't related to page rules (or Terraform at all) but instead a change to the custom pages service which, unfortunately, the Terraform output doesn't convey well at all. To make matters worse, reproduction wasn't consistent making the diagnosis more annoying than it needs to be. I'm hoping to have a dig into the debug output in the near future and see what we can do about surfacing more useful errors in these scenarios.

Can you please check your Terraform runs again and confirm you're seeing the issue resolved on your end before I close this out?

**Comment by canthefason** [comment] 2021-02-03 20:52
thanks for checking in @jacobbednarz, it is all looking good right now.

**Comment by jacobbednarz** [comment] 2021-02-03 21:47
awesome, i'm going to close this out but feel free to either ping here or the support tickets if you need more information.

**Closed by jacobbednarz** 2021-02-03 21:47 UTC
Labels: kind/bug, triage/not-reproducible

**Comment by riuvshyn** [comment] 2021-02-04 08:39
@jacobbednarz awesome! yeh page_rules were just a red herring...
