### ISSUE TITLE
`cloudflare_zone_settings_override` import is not supported

### ISSUE THREAD

**Issue by gerbyzation** [cloudflare/terraform-provider-cloudflare#2805] opened 2023-09-29 09:45 UTC
### Current Terraform and Cloudflare provider version

Terraform 1.5.3
cloudflare provider 4.15.0

### Description

Currently the provider does not support import for the `cloudflare_zone_settings_override` resource.
```
╷
│ Error: resource cloudflare_zone_settings_override doesn't support import
```

### Use cases

We want to move an existing zone into cloudflare state. As it's already deployed and in use recreating is difficult.

**Comment by jacobbednarz** [comment] 2023-09-29 10:08
duplicate of #377

**Comment by gerbyzation** [comment] 2023-09-29 10:08
Apologies - must have misspelled when searching!

**Closed by jacobbednarz** 2023-09-29 10:08 UTC
Labels: kind/enhancement, needs-triage
