### ISSUE TITLE
Support for ruleset rules

### ISSUE THREAD

**Issue by rickradinger** [cloudflare/terraform-provider-cloudflare#2576] opened 2023-07-03 03:39 UTC
### Current Terraform and Cloudflare provider version

3.x

### Description

Add support for ruleset rules

### Use cases

With Cloudflare moving from Firewall rules to rulesets, the terraform code appears to only support the rulesets as a whole.  There is no support for managing rules within rulesets.  This would allow for a template of rules to be managed, deployed and maintained by terraform while still allowing for one off changes or additions to a ruleset.  With only having the ability to modify a ruleset through terraform and not individual ruleset rules as is available through the Cloudflare API (https://developers.cloudflare.com/api/operations/createZoneRulesetRule) this limits use in Terraform.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment] 2023-07-03 03:43
duplicate of #2423

**Closed by jacobbednarz** 2023-07-03 03:43 UTC
Labels: kind/enhancement, needs-triage
