### ISSUE TITLE
Trailing period (.) in record value makes the record always act like it's out-of-date

### ISSUE THREAD

**Issue by SyntaxColoring** [cloudflare/terraform-provider-cloudflare#820] opened 2020-10-10 08:17 UTC
CNAME records (and possibly other records) whose value ends with a `.` will always show as "will be updated in-place," even if no update is actually necessary.

This appears to be because Cloudflare strips the `.` when the record is added, which causes it to always look out-of-sync with the Terraform configuration.

### Terraform Version

Terraform v0.13.3

### Affected Resource(s)
- cloudflare_record

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 2.11"
    }
  }
}

provider "cloudflare" {
  api_token = "[redacted]"
}

resource "cloudflare_zone" "my_zone" {
  zone = "example.com"
  paused = "true"
}

resource "cloudflare_record" "my_cname" {
  zone_id = cloudflare_zone.my_zone.id
  type = "CNAME"
  name = "foo"
  value = "example.org."
}
```

### Debug Output

https://gist.github.com/SyntaxColoring/291d72cb0f8f1058020dbe06d9ca3fde

### Expected Behavior

If you run two `terraform apply`s in a row, the second one should be a no-op, showing no changes.

### Actual Behavior

The second `terraform apply`, and all `terraform apply`s thereafter, show this:

```
  ~ resource "cloudflare_record" "my_cname" {
        created_on  = "2020-10-10T07:48:44.035567Z"
        data        = {}
        hostname    = "foo.example.com"
        id          = "d19f451a92593e19c771b2266f022abd"
        metadata    = {
            "auto_added"             = "false"
            "managed_by_apps"        = "false"
            "managed_by_argo_tunnel" = "false"
            "source"                 = "primary"
        }
        modified_on = "2020-10-10T07:48:44.035567Z"
        name        = "foo"
        priority    = 0
        proxiable   = true
        proxied     = false
        ttl         = 1
        type        = "CNAME"
      ~ value       = "example.org" -> "example.org."
        zone_id     = "c2d9cadc42c798f9bf3ef0158cdbdab6"
    }
```

### Steps to Reproduce

1. `terraform apply` and confirm.
2. `terraform apply` again.

### Important Factoids

None.

### References

None.

**Comment by jacobbednarz** [comment] 2020-10-10 09:10
Thanks for the report!

This is a duplicate of #184 and I’ve expanded upon the reasoning a bit in #154

Do let me know if you have any thoughts though!

**Closed by jacobbednarz** 2020-10-10 09:10 UTC
