### ISSUE TITLE
Cloudflare Worker Custom Domain Trigger missing

### ISSUE THREAD

**Issue by tooboredtocode** [cloudflare/terraform-provider-cloudflare#2305] opened 2023-03-20 17:09 UTC
### Current Terraform and Cloudflare provider version
```
Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0
```

### Description

The terraform provider currently supports every worker trigger besides Custom Domains, so support for them would be appreciated.

### Use cases

This would allow users to replace the current way, of making a proxied route to `::100` or `100::` and defining a worker route, with the recommended custom domains.

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_domain" "my_domain" {
  zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
  domain      = "example.com"
  script_name = cloudflare_worker_script.my_script.name
}
```

**Comment by jacobbednarz** [comment] 2023-03-20 20:33
duplicate of #1921

**Closed by jacobbednarz** 2023-03-20 20:33 UTC
Labels: kind/enhancement, needs-triage

**Comment by tooboredtocode** [comment] 2023-03-21 12:15
By bad, i did my best to search for an open issue but apparently I missed it.
