### ISSUE TITLE
mTLS Client Certificates to be supported by the provider

### ISSUE THREAD

**Issue by dgdevops** [cloudflare/terraform-provider-cloudflare#1283] opened 2021-10-28 14:52 UTC
### Current Terraform and Cloudflare provider version

```
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.3.0
```

### Description

The current version of the provider doesn't support the creation of Client Certificates that can be used for mTLS authentication. Based on the documentation [https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs] only the `cloudflare_access_mutual_tls_certificate` resource is supported.

### Use cases

To create/revoke/delete Client Certificates with Infrastructure-as-code in mind the provider should be able to manage these certs from code.

### Potential Terraform configuration

```hcl
resource "cloudflare_mutual_tls_client_certificate" "my_cert" {
  zone_id                 = "1d5fdc9e88c8a8c4518b068cd94331fe"
  name                    = "My Client Cert"
  private_key_type        = "managed"
  validity                = "10"  
}
```

**Comment by jacobbednarz** [comment] 2021-11-01 03:00
i think this is a duplicate of #1044. please sing out if it's not and we can revisit to different the issues from one another.

**Closed by jacobbednarz** 2021-11-01 03:00 UTC
Labels: kind/enhancement, needs-triage
