### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing in v2.19.1

### ISSUE THREAD

**Issue by raben2** [cloudflare/terraform-provider-cloudflare#994] opened 2021-03-12 08:50 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform version

Terraform v0.14.7

Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

Cloudflare cname records failing when running terraform plan

### Terraform configuration files

resource "cloudflare_record" "domain" {
  count   = length(var.services)
  zone_id = var.cloudflare_zone_id
  name    = format("%s-%s.%s", element(var.services, count.index), var.env, var.domain)
  value   = azurerm_public_ip.ingress.fqdn
  type    = "CNAME"
  ttl     = 300
}

### Debug output

2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: panic: runtime error: invalid memory address or nil pointer dereference
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x103cdac]
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: goroutine 40 [running]:
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareRecordRead(0xc00064eb60, 0x13417c0, 0xc000192780, 0xc00064eb60, 0x0)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_record.go:442 +0xacc
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00027ddd0, 0xc000642af0, 0x13417c0, 0xc000192780, 0xc000720a50, 0x0, 0x0)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:460 +0x129
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0007204b8, 0x1516240, 0xc000355980, 0xc000644900, 0xc0007204b8, 0xc000355980, 0xc0005cfba0)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x12fd8c0, 0xc0007204b8, 0x1516240, 0xc000355980, 0xc0006448a0, 0x0, 0x1516240, 0xc000355980, 0xc0002dd180, 0x25c)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00056c380, 0x1521a00, 0xc000601980, 0xc000584400, 0xc00009c8d0, 0x1c0c510, 0x0, 0x0, 0x0)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).handleStream(0xc00056c380, 0x1521a00, 0xc000601980, 0xc000584400, 0x0)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003d6290, 0xc00056c380, 0x1521a00, 0xc000601980, 0xc000584400)
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: 	google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021-03-12T09:26:50.881+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain[0]": visit complete
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain[1]": visit complete
2021-03-12T09:26:50.881+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/2.19.1/linux_amd64/terraform-provider-cloudflare_v2.19.1 pid=25137 error="exit status 2"
2021/03/12 09:26:50 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain": dynamic subgraph encountered errors
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain": visit complete
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain (expand)": dynamic subgraph encountered errors
2021/03/12 09:26:50 [TRACE] vertex "cloudflare_record.domain (expand)": visit complete
2021/03/12 09:26:50 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/cloudflare/cloudflare\"] (close)" errored, so skipping

### Panic output

2021-03-12T09:26:50.877+0100 [DEBUG] plugin.terraform-provider-cloudflare_v2.19.1: panic: runtime error: invalid memory address or nil pointer dereference

### Expected output

cloudflare_record.domain[0]: Refreshing state... [id=6c09d820eef0b66bdb3d82772645ea1d]
cloudflare_record.domain[1]: Refreshing state... [id=47d4d85b9d17ed5096f8595e240684f4]

### Actual output

Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing

### Steps to reproduce

teraform plan

**Comment by jacobbednarz** [comment] 2021-03-12 09:16
duplicate of #988

**Closed** 2021-03-12 09:16 UTC
Labels: kind/bug, needs-triage
