### ISSUE TITLE
when creating cloudflare_api_token with permission for logs Write on the zone level, permission is assigned on the account level

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#1004] opened 2021-03-25 19:36 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform version

0.14.8

### Affected resource(s)

cloudflare_api_token

### Terraform configuration files

resource "cloudflare_api_token" "zone_tokens" {
  for_each                               = local.zonemap
  name                                   = "${each.key}-key"
  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["Logs Write"],
    ]
    resources = {
        "com.cloudflare.api.account.${var.account_id}" = "*"
    }
  }
  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["DNS Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Access: Apps and Policies Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["SSL and Certificates Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Zone Settings Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Zone Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Firewall Services Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Page Rules Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Workers Routes Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Logs Write"],
    ]
    resources = {
        "com.cloudflare.api.account.zone.${each.value}" = "*"
    }
  }
}

### Expected output

token created with permissions for Logs Write on the zone level

### Actual output

token created with permissions for Logs Write on the account  level

### Steps to reproduce

execute the code above

### Additional factoids

in the api docs for permissions : https://developers.cloudflare.com/api/tokens/create/permissions
logs write, like many others exists on both account and zone level, all work fine with the exception of the logs write so far.

<img width="1072" alt="cloudflare-tf" src="https://user-images.githubusercontent.com/7430707/112532939-ca571600-8d7f-11eb-9c3a-e2be73dee9ee.png">

**Comment by vital4ik** [comment] 2021-03-25 20:04
here is the proper screenshot, where even when account level log write is added separately,  zone level log write still saves it as account level log write:
<img width="1035" alt="cf2" src="https://user-images.githubusercontent.com/7430707/112536337-b9100880-8d83-11eb-9f21-d7745fe18d45.png">

**Comment by vital4ik** [comment] 2021-03-25 20:33
on another note, when i correct the key in the UI afters its created in terraform by changing one of those account:logs write to zone:logs write, that part of the key functions as expected

**Comment by vitdolphin** [comment] 2021-06-02 19:14
hi @jacobbednarz  , any plans to get this fixed?

**Comment by vital4ik** [comment] 2021-06-02 19:21
they are not done right since when i try to use it, it fails with permission error, until i get into UI and fix it there manually. then things works, but i run the module again, it reverts it to the state where its assigned to account 2 times
________________________________

**Comment by vitdolphin** [comment] 2021-06-02 19:26
> Hey, first of all if you want to use `Logs Write` permission only on the zone, you should remove the account level permission:
> 
> ```
> policy {
>   permission_groups = [
>     data.cloudflare_api_token_permission_groups.all.permissions["Logs Write"],
>   ]
>   resources = {
>     "com.cloudflare.api.account.${var.account_id}" = ""
>   }
> }
> ```
> 
> Second, you are right about UI. Even after removing above permission, UI shows Logs Write on the account level. But opening dev tools in your browser or using CF rest api will show you that permissions are done just right.
> 
> tl:dr It is UI bug and thus not related to terraform provider.

the issue is, even if i remove the account part, and only assign it on the zone level it still assigns it on the account level:

````terraform 
policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["DNS Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Access: Apps and Policies Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["SSL and Certificates Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Zone Settings Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Zone Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Firewall Services Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Page Rules Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Workers Routes Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["Logs Write"],
    ]
    resources = {
      "com.cloudflare.api.account.zone.${each.value}" = "*"
    }
````
this still assigns it on the account level only.  after i run this, i have to manually go and fix this in UI for each zone separately

**Comment by kloty** [comment] 2022-06-03 05:46
I think it's because of the current wrong structure of `cloudflare_api_token_permission_groups` data source. 

[The code](https://github.com/cloudflare/terraform-provider-cloudflare/blob/acb8cd3805fe4ccfee79f573d319f87baab8c707/internal/provider/data_source_api_token_permission_groups.go#L38) that creates the map for data source depends on the objects returned by the Permission Group List API like following. 

```
for _, v := range permissions {
	permissionDetails[v.Name] = v.ID
	ids = append(ids, v.ID)
}
```

However, some permission group objects share names but have different IDs because they have different levels. e.g) zone, account

```
# Response of GET user/tokens/permission_groups 
        ...
        {
            "id": "3e0b5820118e47f3922f7c989e673882",
            "name": "Logs Write",
            "description": "Grants write access to logpush jobs",
            "scopes": [
                "com.cloudflare.api.account.zone"
            ]
        },
        {
            "id": "96163bd1b0784f62b3e44ed8c2ab1eb6",
            "name": "Logs Write",
            "description": "Grants write access to logpush jobs",
            "scopes": [
                "com.cloudflare.api.account"
            ]
        },
                {
            "id": "1e13c5124ca64b72b1969a67e8829049",
            "name": "Access: Apps and Policies Write",
            "description": "Grants write access to Cloudflare Access account resources",
            "scopes": [
                "com.cloudflare.api.account"
            ]
        },
        {
            "id": "959972745952452f8be2452be8cbb9f2",
            "name": "Access: Apps and Policies Write",
            "description": "Grants write access to Cloudflare Access zone resources",
            "scopes": [
                "com.cloudflare.api.account.zone"
            ]
        },
        ...
```

**Comment by abulfat-m** [comment] 2022-06-07 10:28
any ETA on when this can be fixed plz?

**Closed** 2022-11-16 03:39 UTC
Labels: kind/bug, triage/accepted, service/iam
