### ISSUE TITLE
Ability to read cloudflare_api_token R2/S3 equivalent keys

### ISSUE THREAD

**Issue by sjlu** [cloudflare/terraform-provider-cloudflare#2873] opened 2023-10-24 12:47 UTC
### Current Terraform and Cloudflare provider version

Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.15.0

### Description

Today the API value of the token is produced but the S3 equivalent keys are not. Wondering if there's a way to provide those keys through Terraform so that they can be referenced in other resources.

### Use cases

For example, getting the S3 equivalent keys and passing it to an Elastic Beanstalk environment.

### Potential Terraform configuration

```hcl
resource "cloudflare_api_token" "r2" {
  name = "r2"

  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.r2["Workers R2 Storage Bucket Item Read"],
      data.cloudflare_api_token_permission_groups.all.r2["Workers R2 Storage Bucket Item Write"]
    ]
    resources = {
      "com.cloudflare.edge.r2.bucket.*" = "*"
    }
  }
}

resource "some_other_resource" "r2" {
  r2_access_key = cloudflare_api_token.r2_access_key
  r2_secret_key = cloudflare_api_token.r2_secret_key
}
```

**Comment by jacobbednarz** [comment] 2023-10-24 22:11
duplicate of #2713, specifically https://github.com/cloudflare/terraform-provider-cloudflare/issues/2713#issuecomment-1694723003

**Closed by jacobbednarz** 2023-10-24 22:11 UTC
Labels: kind/enhancement, needs-triage

**Comment by sjlu** [comment] 2023-10-24 22:13
Makes sense, docs would be nice!
