### ISSUE TITLE
`cloudflare_ruleset` inline rules can change order of rules resulting in a difficult plan

### ISSUE THREAD

**Issue by nitrocode** [cloudflare/terraform-provider-cloudflare#3357] opened 2024-06-13 06:14 UTC
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.8.2
Cloudflare provider v4

### Affected resource(s)

- cloudflare_ruleset

### Terraform configuration files

```hcl
# Zone-level WAF Managed Ruleset
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "zone"
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
    }
    expression  = "(http.host eq \"example.host.com\")"
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled     = true
    order       = 1
  }

  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
    }
    expression  = "(http.host eq \"example.host.com\")"
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled     = true
    order       = 2
  }
}
```

### Link to debug output

n/a

### Expected output

n/a

### Actual output

n/a

### Steps to reproduce

terraform init
terraform plan

### Additional factoids

Problem: when creating a new rule in between other rules, the plan is difficult to read. 

Proposal: explicitly setting the order in hcl and have the provider order the data when hitting the api

The order argument for the resource can be optional

### References

- related #2690

**Comment by jacobbednarz** [comment] 2024-06-13 07:44
thanks but this is a duplicate of the attached issue and doesn't add anything new. 

ordering in the resource is explicit and that service design isn't changing any time soon.

**Closed by jacobbednarz** 2024-06-13 07:44 UTC
Labels: kind/bug, triage/needs-information

**Comment by nitrocode** [comment] 2024-06-13 11:41
This is a tad hasty. It's actually not a duplicate.

The linked issue is for the specific attribute drift.

The issue here is the difficulty in reviewing plans when a rule is modified in the middle of other rules which shifts all the rules proceeding it by 1 making the plan painful to read.

**Comment by jacobbednarz** [comment] 2024-06-13 20:46
got it - i misunderstood the ask here. my apologies. 

ordering of the rules is explicit and built into the resource using the schema and coupled with a PUT, this behaviour is expected as when you are updating the entirety of the ruleset with a new rule in the middle of others m, you are in fact bumping rule 1 to position 2, rule 2 to position 3, etc 

adding a priority field has been floated internally and at the moment, it is not feasible and won't be implemented due to the problems and unpredictable behaviour it has created (previously in the firewall rule resource and page rules). making the field optional wouldn't improve the situation either; it would likely make it worse as you could then have conflicting ordering of the ruleset rules.

**Comment by nitrocode** [comment] 2024-06-14 06:13
Yes a priority argument would be ideal. Perhaps a separate resource where order is mandated? That way the argument is no longer optional

```hcl
resource "cloudflare_ruleset_ordered" "default" {
  # ...
}
```

May I also ask, if this was floated around internally, what were the reasons against a priority argument?

**Comment by jacobbednarz** [comment] 2024-06-14 07:23
the ordering is already mandated and explicitly included in the current resource so i'm unsure what would differ in your proposed solution. 

there have been multiple attempts at having priority as a non-sequential, non-explicit concept with resources (firewall rules, page rules, etc) and all have encountered issues with collisions (setting different resources to the same) unexpected behaviour when encountering gaps (see #187 for details) in ordering or edge cases introduced because of needing additional server side filtering to work out the intended execution order on updates. 

for those, and lots more reasons, not having priority explicitly built in isn't something that we're looking at as an option here in the future.

**Comment by nitrocode** [comment] 2024-06-14 07:30
Sign... If only the api supported individual resources like aws_security_group_rule

Ok fair enough. Thank you for considering.

**Comment by jacobbednarz** [comment] 2024-06-14 07:50
unfortunately, similar issues with an individual ruleset rule resource (and why we don't have it today). 

we have API endpoints for ruleset rules however, it is largely there to support the dash and has some quirks that the dash is fine with but you'll need workarounds to make it work properly outside of that.

**Comment by marcuscraske** [comment] 2024-09-02 18:02
Why would you not allow specifying a `weight` (e.g. 1-999) attribute, and sorting the rules by said `weight`?

And then on the API, you could allow singular rules to be updated, and internally you could pull the other rules and order them by the weight, and push an update internally? So effectively, the `weight` attribute is just meta-data, like description, used only by the API...

And by default, the weight is `1`. And where rules have the same weight, you sort alphabetically by `name`.

And for the migration path for existing config, you take the existing order of rules and apply the weight sequentially, as to retain their existing order today.
