### ISSUE TITLE
Re-adding users with expired invites shows "add" user on plan phase, and fails to add on apply

### ISSUE THREAD

**Issue by bengtrj** [cloudflare/terraform-provider-cloudflare#875] opened 2020-11-25 17:04 UTC
### Terraform version
Terraform `v0.12.29`
provider.cloudflare `v2.13.2`

### Affected resource(s)
`cloudflare_users.cloudflare_account_member`

### Terraform configuration files
```
module "cloudflare_users" {
  source = "../modules/cloudflare_users"

  providers = {
    cloudflare = cloudflare.production
  }

  super_admins = [
    "redacted"
  ]

  admins = [
    "redacted"
  ]

  read_only = [
    "someone.with.expired.invite@email.com",
  ]
}
```

### Debug output
Unfortunately I already solved the issue by revoking the expired invite, and didn't know about this bug report specifics until I decided to report as a bug.

### Panic output
N/A

### Expected behavior
When I run `terraform plan`, if this is the output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cloudflare_users.cloudflare_account_member.cloudflare_admin_read_only["someone.with.expired.invite@email.com"] will be created
  + resource "cloudflare_account_member" "cloudflare_admin_read_only" {
      + email_address = "someone.with.expired.invite@email.com"
      + id            = (known after apply)
      + role_ids      = [
          + "f2b20eaa1a5d4af42b53ac16238c99c7",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Then when I run `terraform apply` it should succeed.

### Actual behavior
With the above `terraform apply` output, when I run `terraform apply` it fails with this error message:
```
(...)
module.cloudflare_users.cloudflare_account_member.cloudflare_admin_read_only["someone.with.expired.invite@email.com"]: Creating...

Error: error creating Cloudflare account member: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"Account member already exists for email address\"}],\"messages\":[],\"result\":null}"

  on ../modules/cloudflare_users/main.tf line 19, in resource "cloudflare_account_member" "cloudflare_admin_read_only":
  19: resource "cloudflare_account_member" "cloudflare_admin_read_only" {
```

When I was confronted by this error, I was confused because the `plan` phase told me otherwise (the user didn't exist). While chatting with my team we found out that the email was already added in a past `terraform apply` and the invitation expired.

So I expect that either:
- expired invitations don't show as "create" when `terraform plan` is ran or;
- when `terraform apply` runs existing invites for that user gets automatically revoked;
- the error message is clear about the fact that the user has an expired invitation that should be revoked;

I know that this is a hard problem to solve, but in a nutshell I had the impression that the `plan` phase checks the existence of the user itself, while the `apply` creates an invite and not the user, so if an expired invite exists it fails to created it (probably because of a consistency check at the database level or something similar).

### Steps to reproduce
- Run `terraform apply` to create new users;
- Let their invitations expire
- Run `terraform plan` again against the same account
- the behaviour described above happens

### Important factoids
N/A

### References
N/A

**Comment by jacobbednarz** [comment] 2020-11-25 20:08
Appreciate you raising this one! There are a few things to cover that I've inlined below.

> When I run `terraform plan` if this is the output:

During the `plan` stage, the primary goal is for Terraform to check what it has in the state file and compare that to the remote API. Here, you see the user is showing as needing to be created as the user ID was not found in the remote API. This happens because internally, Cloudflare deletes a user after the invitation expires. The Terraform provider accounts for this and if it [receives a 404 on the response, it yanks the resource from the state](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_account_member.go#L51-L54).

> Then when I run `terraform apply` it should succeed.

This is the bit that deviates from my past experience and understanding. On the Cloudflare side, the record is removed entirely so the resource should be removed from the state and recreated fresh with a new ID. This happens opaquely behind the schenes and isn't something that can be referenced or check as the API response will always return a 404 at this point (i.e. no ability to check for "pending-invite" status or similar). Internally, the behaviour we exhibit is that the account is recreated and the invitation is resent, not that the email address is already in use. Are you sure this was the case? It wasn't added via the UI? I've got a test case awaiting the expiring TTL however it will be good to confirm this on your side too.

> So I expect that either:
>
> - expired invitations don't show as "create" when `terraform plan` is ran or;
> - when terraform apply runs existing invites for that user gets automatically revoked;
> - the error message is clear about the fact that the user has an expired invitation that should be revoked;
>
> [...] while the `apply` creates an invite and not the user, so if an expired invite exists it fails to created it 

Hopefully, my first point covers the first item in this list however the other two aren't possible from the provider (or underlying libraries) at the moment as the invitation process is tied to the creation of a new user account; not independent to it.

**Comment by jacobbednarz** [comment] 2020-12-11 05:43
I've just checked back on this one and I haven't experienced the behaviour described here. The record is totally missing and the account can be re-invited without conflicts. I'm going to close this one off due to lack of reproducibility however if you have any new information that might help surface the potential bug, don't hesitate to report it back here and we can revisit.

**Closed by jacobbednarz** 2020-12-11 05:43 UTC
Labels: kind/bug, needs-triage
