### ISSUE TITLE
Smart Tiered Cache Middle Tier Support

### ISSUE THREAD

**Issue by jordanfelle** [cloudflare/terraform-provider-cloudflare#2560] opened 2023-06-28 12:42 UTC
### Current Terraform and Cloudflare provider version

Terraform v1.4.5
on linux_amd64

### Description

Smart Tiered Cache now has a middle tier config to enable regional cache. We would like to control this in terraform.

### Use cases

We want to control all settings in terraform and until this is available in the provider we can't set it.

### Potential Terraform configuration

```hcl
resource "cloudflare_tiered_cache" "example" {
  zone_id    = "0da42c8d2132a9ddaf714f9e7c920711"
  cache_type = "smart"
middle_tier = "regional"
}
```

**Comment by jordanfelle** [comment] 2023-06-28 12:42
<img width="759" alt="chrome_2023-06-28_08-39-02" src="https://github.com/cloudflare/terraform-provider-cloudflare/assets/13684686/5f11d529-6981-4bd3-8344-8d2009f81f1a">

**Comment by jacobbednarz** [comment] 2023-06-28 21:07
duplicate of #2545

**Closed by jacobbednarz** 2023-06-28 21:07 UTC
Labels: kind/enhancement, needs-triage
