### ISSUE TITLE
re-add the ability to turn on bot management

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#1001] opened 2021-03-22 18:02 UTC
### Current Terraform version

0.14.7

### Description

missing the ability in the provider to enable "bot management" - "javascript detections"

### Use cases

unable to enable the feature via the cloudflare provider

### Potential Terraform configuration

none exist

**Comment by jacobbednarz** [comment] 2021-03-22 19:14
duplicate of #693

**Closed by jacobbednarz** 2021-03-22 19:14 UTC
Labels: kind/enhancement, needs-triage
