### ISSUE TITLE
Terraform resources tainted and can't be re-created after mistakenly seted wrong credentials

### ISSUE THREAD

**Issue by Nmishin** [cloudflare/terraform-provider-cloudflare#831] opened 2020-10-22 08:50 UTC
### Terraform version

Terraform v0.13.4
+ provider registry.terraform.io/terraform-providers/cloudflare v2.12.0

### Affected resource(s)

All Cloudflare resources.

### Terraform configuration files

```
cat main.tf 
resource "cloudflare_zone_settings_override" "main" {
  zone_id = var.cloudflare_zone_id
  settings {
    always_online               = lookup(var.cloudflare_zone_settings, "always_online", "on")
  }
}
```

```
cat variables.tf 
variable cloudflare_zone_id {}
variable cloudflare_zone_settings {}
```

```
cat cloudflare.auto.tfvars 
cloudflare_zone_id = "zone_id"

cloudflare_zone_settings = {
    always_online = "on"
}
```

### Debug output

https://gist.github.com/Nmishin/535bc43694cc16e172483395fcc8c5a9

### Expected behavior

Error with "HTTP status 403"

### Actual behavior

Resources marked as tainted and terraform tried to delete it but fail with strange errors.

### Steps to reproduce

export CLOUDFLARE_API_KEY
export CLOUDFLARE_EMAIL

terraform apply
terraform destroy

export wrong CLOUDFLARE_API_TOKEN

terraform apply (will fails obviously)

unset CLOUDFLARE_API_TOKEN

terraform apply - will fails with errors like:

`Error: invalid zone setting "mirage" (value: ) found - cannot be set as it is read only`

in next time error can be:

`Error: invalid zone setting "http2" (value: ) found - cannot be set as it is read only`

Or error "Error: error from makeRequest: HTTP status 400":
https://gist.github.com/Nmishin/f72163aa9e0f34f378b79931a187e748

**Comment by jacobbednarz** [comment] 2020-10-22 10:07
Thanks for raising the issue! 

From initial investigations, this is caused by a number of factors, some of which we won't solve here as they are to do with Terraform's state management but others which I can shed some light on. Let's break it down. 

To start with, your credentials here aren't particularly problematic in their own. Out of the box, the provider has a hierarchy and fallback of API token => API key so once you've unset the wrong API token, your credentials will be fine to go again. I'd recommend looking into a better credential management tool (such as [`cf-vault`](https://github.com/jacobbednarz/cf-vault)) to handle the environment when you're running these types of commands to prevent a "dirty" environment. 

As you did have incorrect credentials and you tried to perform a resource update which failed, you'll need to manually correct it. Either through `terraform untaint` or `terraform state rm ...` and import or recreate. This isn't something the provider can address as it's Terraform core and is working as intended. 

The zone override is an interesting one and something we're investigating via #533. It looks the same cause as the linked issue as could be related to read only cause based on your subscription level or the defaults and how the API handles state changes. As such, I'm going to close this as a duplicate and focus the efforts on that issue to avoid the confusion with the other issues mentioned here. 

Do let me know if you have any other questions!

**Closed** 2020-10-22 10:08 UTC
Labels: triage/duplicate
