### ISSUE TITLE
Inconsistent state produced with new `allow_override` property.

### ISSUE THREAD

**Issue by rquadling** [cloudflare/terraform-provider-cloudflare#1163] opened 2021-08-25 15:17 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.25.0
+ provider registry.terraform.io/hashicorp/aws v3.55.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected resource(s)

cloudflare_record.a_record

### Terraform configuration files

```hcl
locals {
  a_records = [
    {
      name    = "bastion"
      value   = module.bastion_instance.result
      proxied = false
    }
  ]
}

main_tld = "co.uk"
tlds = {
  "co.uk" = "*******************************1"
  "ie"    = "*******************************2"
}

resource "cloudflare_record" "a_record" {
  for_each = zipmap(
    [for set in setproduct(local.a_records, keys(var.tlds)) : format("%s.%s", set[0].name, set[1])],
    [for set in setproduct(local.a_records, values(var.tlds)) : merge(set[0], { zone_id : set[1] })]
  )
  zone_id = each.value.zone_id
  type    = "A"
  name    = each.value.name
  proxied = each.value.proxied
  value   = each.value.value
}
```

### Debug output

As part of the plan output ...

```
  # cloudflare_record.a_record["bastion.co.uk"] will be updated in-place
  ~ resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
        id              = "1******************************2"
        name            = "bastion"
      ~ value           = "1.2.3.4" -> (known after apply)
        # (11 unchanged attributes hidden)
    }

  # cloudflare_record.a_record["bastion.ie"] will be updated in-place
  ~ resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
        id              = "3******************************4"
        name            = "bastion"
      ~ value           = "1.2.3.4" -> (known after apply)
        # (11 unchanged attributes hidden)
    }
```

(The actual address hasn't changed, though I've replaced it with `1.2.3.4`).

In the output to the log file (using `TF_LOG=DEBUG TF_LOG_PATH=debug.log`),
```json
        {
          "index_key": "bastion.ie",
          "schema_version": 1,
          "attributes": {
            "allow_overwrite": null,  <<<<<<<<<<<<<<< Not 'false' as expected by the plan - maybe?
            "created_on": "2021-04-01T12:21:06.463626Z",
            "data": {},
            "hostname": "bastion.SNIPPED.ie",
            "id": "*******************************3",
            "metadata": {
              "auto_added": "false",
              "managed_by_apps": "false",
              "managed_by_argo_tunnel": "false",
              "source": "primary"
            },
            "modified_on": "2021-08-16T16:53:12.931766Z",
            "name": "bastion",
            "priority": 0,
            "proxiable": true,
            "proxied": false,
            "timeouts": null,
            "ttl": 1,
            "type": "A",
            "value": "1.2.3.4",
            "zone_id": "*******************************2"
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjozMDAwMDAwMDAwMCwidXBkYXRlIjozMDAwMDAwMDAwMH0sInNjaGVtYV92ZXJzaW9uIjoiMSJ9",
          "dependencies": [
            "data.aws_caller_identity.current",
            "module.bastion_instance.data.external.awscli_program",
            "module.bastion_instance.data.local_file.awscli_results_file",
            "module.bastion_instance.local_file.awscli_results_file",
            "module.bastion_instance.random_string.awscli_output_temp_file_name"
          ]
        }
```

### Expected output

Not an error.

### Actual output

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for cloudflare_record.a_record["bastion.co.uk"] to include new values learned so far during apply, provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid
│ new value for .allow_overwrite: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to reproduce

Using the latest versions and update an a_record.

### Additional factoids

We recently upgraded from Terraform 1.0.1 to 1.0.5 and the Cloudflare provider from 2.21.0 to 2.25.0

The plan shows `+ allow_overwrite = false` as a change. This is not one we are making.

There are no relevant entries in the section "Objects have changed outside of Terraform".

We've tried adding `allow_overwrite = false` to the `a_record` ... no change.

In the debug output the value in is null, rather than false.

In addition to the 2 A records in this project, there are 8 CNAME records that are not exhibiting this problem. The plan does not show them as changing.

**Comment by rquadling** [comment] 2021-08-25 16:27
I removed and re-added the A records using Terraform and all seems to be OK. If there was something I've missed, it would be nice to know (or if there's a bug and more input is needed).

If not, then TPTB can close this ticket.

**Comment by jacobbednarz** [comment] 2021-10-18 00:11
closing as the information hasn't been provided and reapplying the resource will update this in place for anyone else hitting this.

**Closed by jacobbednarz** 2021-10-18 00:11 UTC
Labels: triage/needs-information

**Comment by foood** [comment] 2021-11-29 11:21
@jacobbednarz 
Having the same issue. (I've not using for_each)
When adding new record to the terraform, old records (that already in the state and have the same value but different name) have `+ allow_overwrite = false` in the plan.

After apply new record have added, but apply failed with:
`Error: Provider produced inconsistent final plan
When expanding the plan for cloudflare_record.api to include new values
learned so far during apply, provider
"registry.terraform.io/cloudflare/cloudflare" produced an invalid new value
for .allow_overwrite: was cty.False, but now null.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.`
Then next apply have not shown any errors.

Hope it will help to reproduce and fix the issue.
Thanks in advance.

**Comment by huguesalary** [comment] 2022-03-16 16:02
I've noticed this error usually happens when a value is set to its default, and as such is removed from the provider's object.

For example, I suspect in the cloudflare API `allow_overwrite` default value is `false`. 

When the plan is applied, terraform sets the value of `allow_overwrite` to `false`, but because `false` is the default, the `allow_overwrite` field isn't returned by the API and this ends up being `null` in the code, triggering this error.

**Comment by linxcat** [comment] 2022-09-16 19:44
This is STILL AN ISSUE in the very latest versions of the cloudflare provider

**Comment by johnpipi** [comment] 2022-12-19 17:58
Still an issue with the latest

**Comment by tobikris** [comment] 2023-04-02 14:08
4.2.0 has this issue as well.
