### ISSUE TITLE
Provider produced invalid plan (v3.34.0)

### ISSUE THREAD

**Issue by jeffreymlewis** [cloudflare/terraform-provider-cloudflare#2224] opened 2023-02-08 18:57 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
% terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.34.0
```

### Affected resource(s)

```
cloudflare_access_application
cloudflare_record
```

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "main" {
  zone_id                   = "129387123981967421794619841279834"
  name                      = "hostname-domain"
  domain                    = "hostname.domain"
  type                      = "self_hosted"
  session_duration          = "24h"
  allowed_idps              = ["88888888-1111-2222-1232-444444444444"]
  auto_redirect_to_identity = true
}


resource "cloudflare_record" "argo_tunnel" {
  zone_id = "234234234234234874623"
  name    = hostname.domain
  value   = "234324234-234234-242-24.another.domain"
  type    = "CNAME"
  proxied = true
}
```

### Link to debug output

n/a

### Expected output

I expected terraform plan to complete successfully

### Actual output

```
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].app_launcher_visible:
│ planned value cty.True for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].same_site_cookie_attribute:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].custom_deny_message:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].service_auth_401_redirect:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].skip_interstitial:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].custom_deny_url:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].http_only_cookie_attribute:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].enable_binding_cookie:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["hostname.domain"].logo_url:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].custom_deny_message:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].service_auth_401_redirect:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].skip_interstitial:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].custom_deny_url:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].http_only_cookie_attribute:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].enable_binding_cookie:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].logo_url:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].app_launcher_visible:
│ planned value cty.True for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_access_application.main["argocd.holler-dev.io"].same_site_cookie_attribute:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for cloudflare_record.argo_tunnel["argocd.holler-dev.io"].tags:
│ planned value cty.SetValEmpty(cty.String) for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for cloudflare_record.argo_tunnel["argocd.holler-dev.io"].comment:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_record.argo_tunnel["argocd.holler-dev.io"].allow_overwrite:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_record.argo_tunnel["hostname.domain"].comment:
│ planned value cty.StringVal("") for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_record.argo_tunnel["hostname.domain"].tags:
│ planned value cty.SetValEmpty(cty.String) for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid
│ value for
│ cloudflare_record.argo_tunnel["hostname.domain"].allow_overwrite:
│ planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

```

### Steps to reproduce

1. Apply with provider version `3.30.0`
2. Run `terraform init -upgrade` to upgrade to version `3.34.0`
3. Run `terraform apply` and observe the error

**Comment by jacobbednarz** [comment] 2023-02-09 00:33
duplicate of #2193 and #2190

**Closed by jacobbednarz** 2023-02-09 00:33 UTC
Labels: kind/bug, triage/needs-information
