### ISSUE TITLE
cloudflare_ruleset -  set_config action

### ISSUE THREAD

**Issue by psiservices-bscott** [cloudflare/terraform-provider-cloudflare#2285] opened 2023-03-14 15:10 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.34.0

### Affected resource(s)

resource "cloudflare_ruleset"

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "bic_java1x_disable" {
  zone_id     = var.zone_id
  name        = "BIC-Java1-Disable"
  description = "BIC-Java1-Disable"
  kind        = "zone"
  phase       = "http_config_settings"

  rules {
    action = "set_config"
    action_parameters {
      bic               = false
      email_obfuscation = false
    }
    expression  = "(http.user_agent contains \"Java/1.\")"
    description = "BIC-Java1-Disable"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/psiservices-bscott/b512955f87e7c5bcffe5c1b1c8c724fc

### Expected output

Create the configuration ruleset.

### Actual output

Error: error creating ruleset BIC-Java1-Disable: action parameters are required for the set_config action (20113)
│
│   with cloudflare_ruleset.bic_java1x_disable,
│   on ruleset.tf line 37, in resource "cloudflare_ruleset" "bic_java1x_disable":
│   37: resource "cloudflare_ruleset" "bic_java1x_disable" {

### Steps to reproduce

Try running above terraform to create resource.

**Comment by jacobbednarz** [comment] 2023-03-14 22:06
duplicate of #2164

**Closed by jacobbednarz** 2023-03-14 22:06 UTC
Labels: kind/bug, needs-triage, triage/debug-log-attached
