### ISSUE TITLE
resources should not require account_id when configured in the provider config

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/terraform-provider-cloudflare#1337] opened 2021-12-10 17:25 UTC
### Current Terraform and Cloudflare provider version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.4.0

### Description

many resources _require_ the `account_id` parameter.  These should be optional if you've configured the provider with an account_id.  Even resources that might take either a zone_id or account_id parameter to hit a particularly scoped endpoint should fall back to the account_id set in the provider if neither are provided.

### Use cases

This simplifies the configuration.

### Potential Terraform configuration

```hcl
provider "cloudflare" {
  account_id = "...."
}

resource "cloudflare_access_identity_provider" "okta" {
  name = "My IDP"
  type = "saml"
  config { ... }
}

resource "cloudflare_argo_tunnel" "this" {
  name   = var.name
  secret = random_id.tunnel_secret.b64_std
}
```

**Comment by jacobbednarz** [comment] 2021-12-10 18:18
If I’m understanding this correctly, this issue is a duplicate of #873. The long term goal is that the provider configuration is deprecated in favour of individual resources attributes to allow finer grain targeting.

**Closed by jacobbednarz** 2021-12-10 18:18 UTC
Labels: kind/enhancement, needs-triage

**Comment by tjstansell** [comment] 2021-12-10 20:00
It's not the same as #873 and I think it's the wrong direction to remove the provider config.  That doesn't make sense to me, as when you're managing a set of resources, you're generally doing so within the context of a single account.  Having to pass the account_id to every resource and every module you write to do that is silly when you can just provide the account_id in the provider config.

**Comment by tjstansell** [comment] 2021-12-10 20:09
For inspiration, just look at the `aws` provider that lets you set a role to assume, which region to interact with, and a set of default tags to apply to any resources.  That's the right use of being a provider -- to simplify things.  Since you already support account_id in the provider, it seemed logical to just use that as a default value for resources.  The same could be said for zone_id, actually ... you could define a provider with those defaults and then not have to specify them individually in every resource.  It's about flexibility and letting us decide how best to codify our configuration.  Removing the provider config is a step in the wrong direction.

**Comment by jacobbednarz** [comment] 2021-12-10 20:49
I’m afraid this isn’t like the AWS provider; the concept of a Tenant doesn’t exist there nor does it makes sense given the way AWS IAM and resources are managed. Tenants are some of our biggest consumers so improving the UX there is quite important not to mention better for resource explicitness. There aren’t any drawbacks to introducing this other than repeating the values for non-tenant users which can be solved using a variable. 

While I appreciate your feedback, at this stage, we’re still moving ahead with moving the association (account and zone IDs) to the individual resources. If you’d like to define those details at a provider level, you can use variables and reference them in your resources.

**Comment by jacobbednarz** [comment] 2021-12-10 20:58
> as when you're managing a set of resources, you're generally doing so within the context of a single account. 

I also forgot to mention, this isn’t the case. Majority of the Terraform provider consumers (free through to enterprise) have more than a single account. Last I checked a few months ago, it’s still a 65/35 split with the multiple accounts increasing since I first started tracking it.

**Comment by tjstansell** [comment] 2021-12-10 21:56
Oh, i agree that most folks have multiple cloudflare accounts.   We do.  I would guess that each account is managed via a separate terraform repo, though, and so a single provider instance manages a single account's set of resources.  That way different people could manage different accounts without all having to access the same state store.  Regardless, thanks for the response even though I disagree on the direction.
