### ISSUE TITLE
Rule resource (for ruleset)

### ISSUE THREAD

**Issue by yevhenvolchenko** [cloudflare/terraform-provider-cloudflare#2907] opened 2023-11-02 21:43 UTC
### Current Terraform and Cloudflare provider version

Terraform: 1.6.3
Cloudflare provider: 4.18.0

### Description

A rule resource, that can be added to an existing ruleset

### Use cases

We frequently add new domains and WAF rules specific to those domains. At the moment there is no way to package an application in a single, independent TF module, because all the rules must be in a single TF resource

This problem was not present in pre-RulesetAPI era, BTW

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment] 2023-11-02 21:48
duplicate of #2423 and #2688

**Closed by jacobbednarz** 2023-11-02 21:48 UTC
Labels: kind/enhancement, needs-triage

**Comment by petero-dk** [comment] 2024-05-29 22:54
I added a workaround using multiple repositories here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/3027#issuecomment-2138260815
