### ISSUE TITLE
cloudflare_record resource data attribute is not Idempotent

### ISSUE THREAD

**Issue by dkirrane** [cloudflare/terraform-provider-cloudflare#1159] opened 2021-08-18 14:48 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version
```
terraform {
  required_version = "1.0.4"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "2.25.0"
    }
  }
}
```

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "www" {
  zone_id = "XXXXXXXXX"
  name    = "test-foo"
  value   = "test-foo.foo.com"
  type    = "CNAME"
  proxied = true
}
```

### Debug output

```
cloudflare_record.www: Refreshing state... [id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # cloudflare_record.www has been changed
  ~ resource "cloudflare_record" "www" {
      + data            = {}
        id              = "XXXXXXXX"
        name            = "test-foo"
        # (11 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

### Expected output

I's expect zero changes in Terraform plan.

### Actual output

```
  # cloudflare_record.www has been changed
  ~ resource "cloudflare_record" "www" {
      + data            = {}
        id              = "XXXXXXXX"
        name            = "test-foo"
        # (11 unchanged attributes hidden)
    }
 ```

### Steps to reproduce

1. terraform init
2. terraform plan -out my.tfplan
3. terraform apply "my.tfplan"
4. terraform plan -out my.tfplan
5. Plan shows there are changes but there shouldn't be any

**Comment by jacobbednarz** [comment] 2021-08-18 19:53
duplicate of #1095

**Closed by jacobbednarz** 2021-08-18 19:53 UTC
Labels: kind/bug, needs-triage
