### ISSUE TITLE
Handle '@' in record name and values

### ISSUE THREAD

**Issue by innovate-invent** [cloudflare/terraform-provider-cloudflare#738] opened 2020-07-15 20:09 UTC
### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
- cloudflare_record

### Expected Behavior
Automatically resolve '@' to root domain before comparing to state

### Actual Behavior
Marks resource as changed as cloudflare resolves '@' to the root domain in the resulting state.
Resource was not actually changed.

### Steps to Reproduce
Use '@' in the name or value field of a cloudflare_record

**Comment by jacobbednarz** [comment] 2020-07-15 21:48
Given the following configuration on provider v2.8, I'm unable to reproduce the issue you've raised. 

```hcl
variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "cloudflare_zone_id" {}

provider "cloudflare" {
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

resource "cloudflare_record" "foo" {
  zone_id = var.cloudflare_zone_id
  name    = "@"
  value   = "test txt value"
  type    = "TXT"
  ttl     = "600"
}
```

```
$ terraform init && terraform apply -var "cloudflare_email=$CF_EMAIL" -var "cloudflare_api_key=$CF_API_KEY" -var "cloudflare_zone_id=$CF_ZONE_ID"

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.cloudflare: version = "~> 2.8"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_record.foo will be created
  + resource "cloudflare_record" "foo" {
      + created_on  = (known after apply)
      + hostname    = (known after apply)
      + id          = (known after apply)
      + metadata    = (known after apply)
      + modified_on = (known after apply)
      + name        = "@"
      + proxiable   = (known after apply)
      + proxied     = false
      + ttl         = 600
      + type        = "TXT"
      + value       = "test txt value"
      + zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_record.foo: Creating...
cloudflare_record.foo: Creation complete after 1s [id=28a1be2c1071efe05a0a4d9d186a0189]
```

Subsequent runs do not trigger a replacement and the resource is managed as expected.

```
$ terraform apply -var "cloudflare_email=$CF_EMAIL" -var "cloudflare_api_key=$CF_API_KEY" -var "cloudflare_zone_id=$CF_ZONE_ID"
cloudflare_record.foo: Refreshing state... [id=28a1be2c1071efe05a0a4d9d186a0189]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Can you please provide a full reproduction test case like the one I've posted above?

If you're encountering issues with importing and then attempting to manage DNS records, you can check out https://github.com/terraform-providers/terraform-provider-cloudflare/issues/735#issuecomment-658399736 which covers more about the issue and why it happens.

**Comment by innovate-invent** [comment] 2020-07-15 22:04
Sorry, this doesn't appear to happen during terraform apply but terraform plan:
```
  # cloudflare_record.burkholderia_ca_www will be updated in-place
  ~ resource "cloudflare_record" "burkholderia_ca_www" {
        created_on  = "2020-07-15T20:31:39.944226Z"
        data        = {}
        hostname    = "www.burkholderia.ca"
        id          = "c2cff333e46093946a30e937b22f561f"
        metadata    = {
            "auto_added"             = "false"
            "managed_by_apps"        = "false"
            "managed_by_argo_tunnel" = "false"
            "source"                 = "primary"
        }
        modified_on = "2020-07-15T20:31:39.944226Z"
        name        = "www"
        priority    = 0
        proxiable   = true
        proxied     = true
        ttl         = 1
        type        = "CNAME"
      ~ value       = "burkholderia.ca" -> "@"
        zone_id     = "59335e737b561e0e8d6e3c3888f8a1dc"
    }
```

**Comment by jacobbednarz** [comment] 2020-07-15 22:07
I get the same results even with a plan. Can you please provide a full reproduction test case for me to investigate further? Without it, there isn't any more I can do.
GitHub <notifications@github.com> wrote:
“Sorry, this doesn't appear to happen during terraform apply but terraform plan:

  # cloudflare_record.burkholderia_ca_www will be updated in-place
  ~ resource "cloudflare_record" "burkholderia_ca_www" {
        created_on  = "2020-07-15T20:31:39.944226Z"
        data        = {}
        hostname    = "www.burkholderia.ca"
        id          = "c2cff333e46093946a30e937b22f561f"
        metadata    = {
            "auto_added"             = "false"
            "managed_by_apps"        = "false"
            "managed_by_argo_tunnel" = "false"
            "source"                 = "primary"
        }
        modified_on = "2020-07-15T20:31:39.944226Z"
        name        = "www"
        priority    = 0
        proxiable   = true
        proxied     = true
        ttl         = 1
        type        = "CNAME"
      ~ value       = "burkholderia.ca" -> "@"
        zone_id     = "59335e737b561e0e8d6e3c3888f8a1dc"
    }”

**Comment by jacobbednarz** [comment] 2020-08-12 21:18
Closing this off due to no feedback provided. Please let me know if you can put together a reproduction test case demonstrating the issue and we can revisit.

**Closed by jacobbednarz** 2020-08-12 21:18 UTC

**Comment by innovate-invent** [comment] 2020-11-05 21:03
I just came back around to this. It appears you are testing only the name attribute.
try:
```hcl
resource "cloudflare_record" "foo" {
  zone_id = var.cloudflare_zone_id
  name    = "www"
  value   = "@"
  type    = "CNAME"
  ttl     = "600"
}
```

**Comment by innovate-invent** [comment] 2021-01-09 02:04
@jacobbednarz can you re-open this issue?

**Comment by jacobbednarz** [comment] 2021-01-22 04:51
At this stage, I don't think the trade offs are worth aliasing `@` as a `value` to the current zone due to the number of edge cases it will open up in the provider and potential performance degradations it may introduce. The remote API does not return the alias which means we'd need to be making HTTP calls everytime we needed to validate this value against the schema. Some users have thousands of DNS records which would introduce far longer `plan` and `apply` times for very little return.

If you want to reuse a single value, I'd recommend using a Terraform local variable.
