### ISSUE TITLE
getting: Polish WebP conversion can be only triggered when Polish setting is enabled

### ISSUE THREAD

**Issue by jakshi** [cloudflare/terraform-provider-cloudflare#495] opened 2019-10-05 09:29 UTC
When I try to enable polish and webp in cloudflare_zone_settings_override resource I get:

Error: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1020,\"message\":\"Polish WebP conversion can be only triggered when Polish setting is enabled\"},{\"code\":1006,\"message\":\"Unrecognized zone setting name\"}],\"messages\":[],\"result\":null}"

According to documentation in https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html#webp:

webp. Note that the value specified will be ignored unless polish is turned on (i.e. is "lossless" or "lossy") 

So I expect it to be ignored (or have polish enabled and then webp enabled) instead of getting the error.

$ terraform --version
Terraform v0.12.9
+ provider.aws v2.30.0
+ provider.cloudflare v2.0.0
+ provider.template v2.1.2

**Comment by maetthu** [comment] 2019-10-07 20:31
I'm getting the same error. It happens when creating a new cloudflare_zone_settings_override resource. Disabling webp, create resource with polish enabled, set webp to on again seems to work for me.

**Comment by ZebraFlesh** [comment] 2020-08-04 18:55
This happens for me in an existing `cloudflare_zone_settings_override` resource.
```bash
$terraform -version
Terraform v0.12.28
+ provider.aws v3.0.0
+ provider.cloudflare v2.9.0
```

**Comment by jacobbednarz** [comment] 2021-01-22 04:40
@jakshi @maetthu @ZebraFlesh can one of you please provide a reproduction case for this one? I'm not sure I have enough to go off here.

**Comment by ZebraFlesh** [comment] 2021-01-22 17:28
Pretty straight forward, use a resource similar to the following:
```hcl
resource "cloudflare_zone_settings_override" "test-resource" {
  zone_id = <your zone id>
  settings {
    polish           = "lossy"
    webp             = "on"  # webp needs to enabled after polish; it's a two step process that cannot be achieved in a single commit
  }
}
```

**Comment by KyleNesium** [comment] 2021-03-20 11:47
Terraform v0.12.30
+ provider.cloudflare v2.6.0

Settings
```
    # speed
    polish           = "lossy"
    webp             = "on"
```
 
Output:
```

[2021-03-20T11:29:39.141Z] Error: HTTP status 400: Polish WebP conversion can be only triggered when Polish setting is enabled (1020)

[2021-03-20T11:29:39.141Z] Error: HTTP status 400: Polish WebP conversion can be only triggered when Polish setting is enabled (1020)
```

the polish setting was persisted, but the webp was not. On the second run both seem to apply fine.

`[2021-03-20T11:44:31.609Z]           ~ webp                        = "off" -> "on"
`

**Comment by vital4ik** [comment] 2021-04-09 18:07
i think the solution would be to make webp to have a block and put polish setting inside the webp block?

**Comment by zicodes** [comment] 2021-10-04 11:54
This is still an issue with. Same result as @KyleNesium described

Terraform v1.0.8
provider.cloudflare v3.1.0

**Comment by perosb** [comment] 2022-06-03 11:44
> i think the solution would be to make webp to have a block and put polish setting inside the webp block?

or the other way around
```
polish {
  mode = "lossy"
  webp = "on"
  avif = "on"
}
```

**Comment by jacobbednarz** [comment] 2023-02-10 04:34
closing this as unresolved since there isn't anything we can do at the moment. the zone settings management will be overhauled in a future release and this is on the list to get some attention so we'll address it there (and not in the current resource).

**Closed by jacobbednarz** 2023-02-10 04:34 UTC
Labels: triage/needs-information

**Comment by fholzer** [comment] 2025-07-30 14:02
I feel like this should be reopened. It was marked as not planned when v3 was the latest version. In the closing [comment](https://github.com/cloudflare/terraform-provider-cloudflare/issues/495#issuecomment-1425161266) it was stated that this issue will be resolved the "zone settings management will be overhaul". Now on v5 this problem persists.

Maybe I'm missing something, but to me it seems that it's still not possible to apply all settings in a single TF run. At the time of writing AFAIK the only way to apply zone settings is by using the `cloudflare_zone_setting` resource. Regardless of how this is set up, either using `for_each` to iterate over a list of settings, or be creating separate instances of `cloudflare_zone_setting` resources, there's no way to tell TF to "create"/set one after the other. TF's dependency tree works on resources, not resources instances.

This leads to a situation where "multiple commits" are the suggested solution. This might be the quick fix for a real simple Cloudflare setup, not so much when managing hundreds of zones, using nested modules, etc.

@jacobbednarz
