### ISSUE TITLE
cloudflare_access_policy duplicates access group in same access policy

### ISSUE THREAD

**Issue by NikolaeVarius** [cloudflare/terraform-provider-cloudflare#889] opened 2020-12-09 15:42 UTC
### Terraform version

Terraform v0.13.4
+ provider registry.terraform.io/cloudflare/cloudflare v2.14.0
+ provider registry.terraform.io/hashicorp/aws v3.20.0

### Affected resource(s)
cloudflare_access_policy

### Terraform configuration files
```
resource "cloudflare_access_policy" "whatever" {
  application_id = whatever
  account_id     = whatever
  name           = "11 Employees"
  decision       = "allow"

  include {
    group = [local.cloudflare_access_group]
  }
}

```

![bug1](https://user-images.githubusercontent.com/8305363/101650937-7d3a7880-3a0a-11eb-9155-d3ce6f3cb520.png)

### Debug output
Will provide if requested, need to do some scrubbing.

### Expected behavior
TF should not be trying to create a new resource. 

### Actual behavior
State already existed. However it attempted to create a new resource. When I let it create it, it simply just added a second same .policy group.
![bug2](https://user-images.githubusercontent.com/8305363/101651203-cc80a900-3a0a-11eb-85a6-731ba1403f23.png)

After that, it seems to have an infinite problem with the priority, where it always tries to reset priority to null, applying it doesn't do anything it always has that change. If remove the 1st policy, it still creates the second one. Attempting to see if setting priority to 1 errors with invalid priority error.

### Steps to reproduce
Have no idea what got into this state. This was not touched since It was first set up, and I know for a fact it worked fine. This was something I noticed when attempting to upgrade the providers to latest.

I have a staging instance that uses the same configs and have not seen this issue there

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment] 2020-12-10 06:54
Can you please provide the TF_LOG=DEBUG output per the issue template? 

Without a reproduction case or some breadcrumbs on how this occurs, there isn't really a great deal we can do here as it could be a local issue which isn't resolvable by the provider.

**Comment by abeluck** [comment] 2020-12-18 16:27
We are experiencing this issue also, it is relatively easy to reproduce:

1. Create an application
```hcl
resource "cloudflare_access_application" "default" {
  zone_id                   = var.cloudflare_zone_id
  name                      = var.app_name
  domain                    = var.app_domain
  session_duration          = "12h"
  auto_redirect_to_identity = true
}
```

2. Create access policies
```hcl
resource "cloudflare_access_policy" "allow_super_admins" {
  zone_id        = var.cloudflare_zone_id
  application_id = cloudflare_access_application.default.id
  name           = "Super Admins"
  precedence     = 1
  decision       = "allow"
  include {
    group = [
      var.cloudflare_client_admin_group_id
    ]
  }
}
resource "cloudflare_access_policy" "allow_users" {
  zone_id        = var.cloudflare_zone_id
  application_id = cloudflare_access_application.default.id
  name           = "Users"
  precedence     = 2
  decision       = "allow"
  include {
    group = [
      var.cloudflare_client_user_group_id
    ]
  }
}
resource "cloudflare_access_policy" "default_deny" {
  zone_id        = var.cloudflare_zone_id
  application_id = cloudflare_access_application.default.id
  name           = "Deny Public"
  precedence     = 100
  decision       = "deny"
  include {
    everyone = true
  }
}
```
3. After applying, go to the Access dashboard and edit one of the created policies. Do something simple like add an email or a group, or change the order.
4. Run an apply again

Results: Rather than detecting configuration drift, terraform seems to forget about the original policies it created and attempts to create new policies.

**Comment by jacobbednarz** [comment] 2021-01-28 05:04
@abeluck the issue you've outlined above is caused by editting policies in the UI which actually generates a totally new policy instead of updating the old one. As editting the policy in the UI deletes the previous one, Terraform is doing as intended and trying to maintain the state it knows about (the UI one then becomes not managed by Terraform).

I'll check internally why this is however if you are managing resources in Terraform, you shouldn't be using the UI to update them. Not all resources handle partial changes and in some cases, will try to recreate them and if you're not aware of the underlying API calls, you could experience undesirable consequences.

**Comment by jacobbednarz** [comment] 2021-01-28 19:47
I've confirmed this is intentional and unfortunately, not able to be changed in it's current state. Going back to my last comment, this is one of the resources that if you have under source control, you shouldn't be editting outside of Terraform.

Closing this off as there isn't any action we can take at the moment to resolve.

**Closed by jacobbednarz** 2021-01-28 19:47 UTC
Labels: kind/bug, needs-triage

**Comment by abeluck** [comment] 2021-01-29 11:06
@jacobbednarz thanks for the detailed information. It would be helpful if a warning/note could be added to the documentation pages for these resources where manual editing and terraform control are mutually exclusive.
