### ISSUE TITLE
cloudflare_ruleset can't be independent of its rules

### ISSUE THREAD

**Issue by mooseracerPT** [cloudflare/terraform-provider-cloudflare#3226] opened 2024-04-04 00:13 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
```

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "magic_transit_example" {
  account_id  = "f037e56e89293a057740de681ac9abbe"
  name        = "account magic transit"
  description = "example magic transit ruleset description"
  kind        = "root"
  phase       = "magic_transit"

  rules {
    action      = "allow"
    expression  = "tcp.dstport in { 32768..65535 }"
    description = "Allow TCP Ephemeral Ports"
  }
}
```

### Link to debug output

n/a

### Expected output

This is a suggestion to create a new optional resource `cloudflare_ruleset_rule` that you could attach to an existing `cloudflare_ruleset`, say via a data lookup. My use case is that I want to have multiple terraform workspaces (environments) each handling their own rule for the ruleset. With this pattern I could create an empty ruleset for the phase, and then control individual rules from their respective environment's workspace.

### Actual output

With the current implementation of `cloudflare_ruleset` I'm forced to handle all possible rules on a phase at the same time. This means the code for it needs to live outside my existing workspaces, and needs to lookup all the values it needs to construct the rules.

### Steps to reproduce

This is a design issue.

**Comment by jacobbednarz** [comment] 2024-04-04 00:17
duplicate of #3210

**Closed** 2024-04-04 00:16 UTC
Labels: kind/bug, triage/needs-information

**Comment by petero-dk** [comment] 2024-05-29 22:54
I added a workaround using multiple repositories here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/3027#issuecomment-2138260815
