### ISSUE TITLE
Decouple cloudflare_ruleset and the rules associated with it

### ISSUE THREAD

**Issue by afoley-st** [cloudflare/terraform-provider-cloudflare#2614] opened 2023-07-12 21:10 UTC
### Current Terraform and Cloudflare provider version

```
Terraform v1.1.9
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.5.3. You can update by downloading from https://www.terraform.io/downloads.html
```

Provider Version:
```hcl
cloudflare = {
    source  = "cloudflare/cloudflare"
    version = "= 3.31.0"
}
```

### Description

 It would be nice if you could update a `cloudflare_ruleset` and add rules to it from different terraform solutions/backends. As it stands, it seems I can only have one `cloudflare_ruleset` per phase in a zone, so its very difficult/cumbersome to add rules unless I aggregate everything into one `terraform apply`.

### Use cases

If I have multiple terraform solutions across multiple clouds, I might want to deploy them separately. I would then like all public egress IPs from any instances created by those separate solutions to be added to rules within a cloudflare ruleset so that my known IPs can access my cloudflare-gated network.

As of now, I would have to deploy those pieces of infrastructure, fetch their IPs, and then aggregate their IPs in some `cloudflare_ruleset`, but that is quite cumbersome.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "managed_ruleset" {
  kind       = "zone"
  name     = "default"
  phase    = "http_request_firewall_custom"
  zone_id = "my-zone-id"
}

resource "cloudflare_ruleset_rule" "some_rule_for_gcp" {
  action = "skip"
  action_parameters {
    ruleset = "cloudflare_ruleset.managed_ruleset.id"
  }
  description = "Allow GCP Hosts"
  enabled     = true
  expression  = "(ip.src in {my-ip/32})"
  logging {
    enabled = false
    status  = "enabled"
  }
}

resource "cloudflare_ruleset_rule" "some_rule_for_aws" {
  action = "skip"
  action_parameters {
    ruleset = "cloudflare_ruleset.managed_ruleset.id"
  }
  description = "Allow AWS Hosts"
  enabled     = true
  expression  = "(ip.src in {my-ip/32})"
  logging {
    enabled = false
    status  = "enabled"
  }
}

```

### References

AWS Did something similar with security group rules: 

https://registry.terraform.io/providers/hashicorp/aws/3.42.0/docs/resources/security_group_rule

**Comment by jacobbednarz** [comment] 2023-07-12 21:13
duplicate of #2423

**Closed** 2023-07-12 21:13 UTC
Labels: kind/enhancement, needs-triage
